/**
 * GitHub-style emoji shortcodes for `:` typeahead in composers / title.
 * Compact list of common gemoji names (search by name / aliases).
 * Insertion uses `:name:` shortcode (renders as emoji on github.com).
 */

export type EmojiEntry = {
  /** Primary shortcode without colons */
  name: string;
  /** Unicode emoji glyph for menu preview */
  emoji: string;
  /** Extra search tokens (aliases, keywords) */
  aliases?: readonly string[];
};

/**
 * Curated GitHub-common shortcodes. Keep pure + searchable without a runtime fetch.
 * Order ≈ popularity for empty-query suggestions.
 */
export const EMOJI_SHORTCODES: readonly EmojiEntry[] = [
  { name: '+1', emoji: '👍', aliases: ['thumbsup', 'yes'] },
  { name: '-1', emoji: '👎', aliases: ['thumbsdown', 'no'] },
  { name: 'smile', emoji: '😄', aliases: ['happy', 'smiley'] },
  { name: 'laughing', emoji: '😆', aliases: ['lol', 'satisfied'] },
  { name: 'blush', emoji: '😊' },
  { name: 'smiley', emoji: '😃' },
  { name: 'relaxed', emoji: '☺️' },
  { name: 'smirk', emoji: '😏' },
  { name: 'heart_eyes', emoji: '😍' },
  { name: 'kissing_heart', emoji: '😘' },
  { name: 'kissing_closed_eyes', emoji: '😚' },
  { name: 'flushed', emoji: '😳' },
  { name: 'relieved', emoji: '😌' },
  { name: 'satisfied', emoji: '😆' },
  { name: 'grin', emoji: '😁' },
  { name: 'wink', emoji: '😉' },
  { name: 'stuck_out_tongue_winking_eye', emoji: '😜' },
  { name: 'stuck_out_tongue_closed_eyes', emoji: '😝' },
  { name: 'grinning', emoji: '😀' },
  { name: 'kissing', emoji: '😗' },
  { name: 'kissing_smiling_eyes', emoji: '😙' },
  { name: 'stuck_out_tongue', emoji: '😛' },
  { name: 'sleeping', emoji: '😴' },
  { name: 'worried', emoji: '😟' },
  { name: 'frowning', emoji: '😦' },
  { name: 'anguished', emoji: '😧' },
  { name: 'open_mouth', emoji: '😮' },
  { name: 'grimacing', emoji: '😬' },
  { name: 'confused', emoji: '😕' },
  { name: 'hushed', emoji: '😯' },
  { name: 'expressionless', emoji: '😑' },
  { name: 'unamused', emoji: '😒' },
  { name: 'sweat_smile', emoji: '😅' },
  { name: 'sweat', emoji: '😓' },
  { name: 'disappointed_relieved', emoji: '😥' },
  { name: 'weary', emoji: '😩' },
  { name: 'pensive', emoji: '😔' },
  { name: 'disappointed', emoji: '😞' },
  { name: 'confounded', emoji: '😖' },
  { name: 'fearful', emoji: '😨' },
  { name: 'cold_sweat', emoji: '😰' },
  { name: 'persevere', emoji: '😣' },
  { name: 'cry', emoji: '😢' },
  { name: 'sob', emoji: '😭' },
  { name: 'joy', emoji: '😂' },
  { name: 'astonished', emoji: '😲' },
  { name: 'scream', emoji: '😱' },
  { name: 'tired_face', emoji: '😫' },
  { name: 'angry', emoji: '😠' },
  { name: 'rage', emoji: '😡' },
  { name: 'triumph', emoji: '😤' },
  { name: 'sleepy', emoji: '😪' },
  { name: 'yum', emoji: '😋' },
  { name: 'mask', emoji: '😷' },
  { name: 'sunglasses', emoji: '😎' },
  { name: 'dizzy_face', emoji: '😵' },
  { name: 'imp', emoji: '👿' },
  { name: 'smiling_imp', emoji: '😈' },
  { name: 'neutral_face', emoji: '😐' },
  { name: 'no_mouth', emoji: '😶' },
  { name: 'innocent', emoji: '😇' },
  { name: 'alien', emoji: '👽' },
  { name: 'yellow_heart', emoji: '💛' },
  { name: 'blue_heart', emoji: '💙' },
  { name: 'purple_heart', emoji: '💜' },
  { name: 'heart', emoji: '❤️', aliases: ['love', 'red_heart'] },
  { name: 'green_heart', emoji: '💚' },
  { name: 'broken_heart', emoji: '💔' },
  { name: 'heartbeat', emoji: '💓' },
  { name: 'heartpulse', emoji: '💗' },
  { name: 'two_hearts', emoji: '💕' },
  { name: 'revolving_hearts', emoji: '💞' },
  { name: 'cupid', emoji: '💘' },
  { name: 'sparkling_heart', emoji: '💖' },
  { name: 'sparkles', emoji: '✨' },
  { name: 'star', emoji: '⭐' },
  { name: 'star2', emoji: '🌟' },
  { name: 'dizzy', emoji: '💫' },
  { name: 'boom', emoji: '💥', aliases: ['collision'] },
  { name: 'anger', emoji: '💢' },
  { name: 'exclamation', emoji: '❗' },
  { name: 'question', emoji: '❓' },
  { name: 'grey_exclamation', emoji: '❕' },
  { name: 'grey_question', emoji: '❔' },
  { name: 'zzz', emoji: '💤' },
  { name: 'dash', emoji: '💨' },
  { name: 'sweat_drops', emoji: '💦' },
  { name: 'notes', emoji: '🎶' },
  { name: 'musical_note', emoji: '🎵' },
  { name: 'fire', emoji: '🔥', aliases: ['hot', 'flame'] },
  { name: 'hankey', emoji: '💩', aliases: ['poop', 'shit'] },
  { name: 'thumbsup', emoji: '👍' },
  { name: 'thumbsdown', emoji: '👎' },
  { name: 'ok_hand', emoji: '👌' },
  { name: 'punch', emoji: '👊', aliases: ['facepunch'] },
  { name: 'fist', emoji: '✊' },
  { name: 'v', emoji: '✌️' },
  { name: 'wave', emoji: '👋' },
  { name: 'hand', emoji: '✋' },
  { name: 'open_hands', emoji: '👐' },
  { name: 'point_up', emoji: '☝️' },
  { name: 'point_down', emoji: '👇' },
  { name: 'point_left', emoji: '👈' },
  { name: 'point_right', emoji: '👉' },
  { name: 'raised_hands', emoji: '🙌' },
  { name: 'pray', emoji: '🙏' },
  { name: 'clap', emoji: '👏' },
  { name: 'muscle', emoji: '💪' },
  { name: 'metal', emoji: '🤘' },
  { name: 'fu', emoji: '🖕' },
  { name: 'walking', emoji: '🚶' },
  { name: 'runner', emoji: '🏃', aliases: ['running'] },
  { name: 'couple', emoji: '👫' },
  { name: 'family', emoji: '👪' },
  { name: 'two_men_holding_hands', emoji: '👬' },
  { name: 'two_women_holding_hands', emoji: '👭' },
  { name: 'dancer', emoji: '💃' },
  { name: 'dancers', emoji: '👯' },
  { name: 'ok_woman', emoji: '🙆' },
  { name: 'no_good', emoji: '🙅' },
  { name: 'information_desk_person', emoji: '💁' },
  { name: 'raising_hand', emoji: '🙋' },
  { name: 'bride_with_veil', emoji: '👰' },
  { name: 'person_with_pouting_face', emoji: '🙎' },
  { name: 'person_frowning', emoji: '🙍' },
  { name: 'bow', emoji: '🙇' },
  { name: 'couplekiss', emoji: '💏' },
  { name: 'couple_with_heart', emoji: '💑' },
  { name: 'massage', emoji: '💆' },
  { name: 'haircut', emoji: '💇' },
  { name: 'nail_care', emoji: '💅' },
  { name: 'boy', emoji: '👦' },
  { name: 'girl', emoji: '👧' },
  { name: 'woman', emoji: '👩' },
  { name: 'man', emoji: '👨' },
  { name: 'baby', emoji: '👶' },
  { name: 'older_woman', emoji: '👵' },
  { name: 'older_man', emoji: '👴' },
  { name: 'person_with_blond_hair', emoji: '👱' },
  { name: 'man_with_gua_pi_mao', emoji: '👲' },
  { name: 'man_with_turban', emoji: '👳' },
  { name: 'construction_worker', emoji: '👷' },
  { name: 'cop', emoji: '👮' },
  { name: 'angel', emoji: '👼' },
  { name: 'princess', emoji: '👸' },
  { name: 'smiley_cat', emoji: '😺' },
  { name: 'smile_cat', emoji: '😸' },
  { name: 'heart_eyes_cat', emoji: '😻' },
  { name: 'kissing_cat', emoji: '😽' },
  { name: 'smirk_cat', emoji: '😼' },
  { name: 'scream_cat', emoji: '🙀' },
  { name: 'crying_cat_face', emoji: '😿' },
  { name: 'pouting_cat', emoji: '😾' },
  { name: 'japanese_ogre', emoji: '👹' },
  { name: 'japanese_goblin', emoji: '👺' },
  { name: 'see_no_evil', emoji: '🙈' },
  { name: 'hear_no_evil', emoji: '🙉' },
  { name: 'speak_no_evil', emoji: '🙊' },
  { name: 'guardsman', emoji: '💂' },
  { name: 'skull', emoji: '💀' },
  { name: 'feet', emoji: '🐾', aliases: ['paw_prints'] },
  { name: 'lips', emoji: '👄' },
  { name: 'kiss', emoji: '💋' },
  { name: 'droplet', emoji: '💧' },
  { name: 'ear', emoji: '👂' },
  { name: 'eyes', emoji: '👀' },
  { name: 'nose', emoji: '👃' },
  { name: 'tongue', emoji: '👅' },
  { name: 'love_letter', emoji: '💌' },
  { name: 'bust_in_silhouette', emoji: '👤' },
  { name: 'busts_in_silhouette', emoji: '👥' },
  { name: 'speech_balloon', emoji: '💬' },
  { name: 'thought_balloon', emoji: '💭' },
  { name: 'sunny', emoji: '☀️' },
  { name: 'umbrella', emoji: '☔' },
  { name: 'cloud', emoji: '☁️' },
  { name: 'snowflake', emoji: '❄️' },
  { name: 'snowman', emoji: '⛄' },
  { name: 'zap', emoji: '⚡' },
  { name: 'cyclone', emoji: '🌀' },
  { name: 'foggy', emoji: '🌁' },
  { name: 'ocean', emoji: '🌊' },
  { name: 'cat', emoji: '🐱' },
  { name: 'dog', emoji: '🐶' },
  { name: 'mouse', emoji: '🐭' },
  { name: 'hamster', emoji: '🐹' },
  { name: 'rabbit', emoji: '🐰' },
  { name: 'wolf', emoji: '🐺' },
  { name: 'frog', emoji: '🐸' },
  { name: 'tiger', emoji: '🐯' },
  { name: 'koala', emoji: '🐨' },
  { name: 'bear', emoji: '🐻' },
  { name: 'pig', emoji: '🐷' },
  { name: 'pig_nose', emoji: '🐽' },
  { name: 'cow', emoji: '🐮' },
  { name: 'boar', emoji: '🐗' },
  { name: 'monkey_face', emoji: '🐵' },
  { name: 'monkey', emoji: '🐒' },
  { name: 'horse', emoji: '🐴' },
  { name: 'racehorse', emoji: '🐎' },
  { name: 'camel', emoji: '🐫' },
  { name: 'sheep', emoji: '🐑' },
  { name: 'elephant', emoji: '🐘' },
  { name: 'panda_face', emoji: '🐼' },
  { name: 'snake', emoji: '🐍' },
  { name: 'bird', emoji: '🐦' },
  { name: 'baby_chick', emoji: '🐤' },
  { name: 'hatched_chick', emoji: '🐥' },
  { name: 'hatching_chick', emoji: '🐣' },
  { name: 'chicken', emoji: '🐔' },
  { name: 'penguin', emoji: '🐧' },
  { name: 'turtle', emoji: '🐢' },
  { name: 'bug', emoji: '🐛' },
  { name: 'honeybee', emoji: '🐝', aliases: ['bee'] },
  { name: 'ant', emoji: '🐜' },
  { name: 'beetle', emoji: '🐞' },
  { name: 'snail', emoji: '🐌' },
  { name: 'octopus', emoji: '🐙' },
  { name: 'tropical_fish', emoji: '🐠' },
  { name: 'fish', emoji: '🐟' },
  { name: 'whale', emoji: '🐳' },
  { name: 'whale2', emoji: '🐋' },
  { name: 'dolphin', emoji: '🐬' },
  { name: 'cow2', emoji: '🐄' },
  { name: 'ram', emoji: '🐏' },
  { name: 'rat', emoji: '🐀' },
  { name: 'water_buffalo', emoji: '🐃' },
  { name: 'tiger2', emoji: '🐅' },
  { name: 'rabbit2', emoji: '🐇' },
  { name: 'dragon', emoji: '🐉' },
  { name: 'goat', emoji: '🐐' },
  { name: 'rooster', emoji: '🐓' },
  { name: 'dog2', emoji: '🐕' },
  { name: 'pig2', emoji: '🐖' },
  { name: 'mouse2', emoji: '🐁' },
  { name: 'ox', emoji: '🐂' },
  { name: 'dragon_face', emoji: '🐲' },
  { name: 'blowfish', emoji: '🐡' },
  { name: 'crocodile', emoji: '🐊' },
  { name: 'dromedary_camel', emoji: '🐪' },
  { name: 'leopard', emoji: '🐆' },
  { name: 'cat2', emoji: '🐈' },
  { name: 'poodle', emoji: '🐩' },
  { name: 'paw_prints', emoji: '🐾' },
  { name: 'bouquet', emoji: '💐' },
  { name: 'cherry_blossom', emoji: '🌸' },
  { name: 'tulip', emoji: '🌷' },
  { name: 'four_leaf_clover', emoji: '🍀' },
  { name: 'rose', emoji: '🌹' },
  { name: 'sunflower', emoji: '🌻' },
  { name: 'hibiscus', emoji: '🌺' },
  { name: 'maple_leaf', emoji: '🍁' },
  { name: 'leaves', emoji: '🍃' },
  { name: 'fallen_leaf', emoji: '🍂' },
  { name: 'herb', emoji: '🌿' },
  { name: 'mushroom', emoji: '🍄' },
  { name: 'cactus', emoji: '🌵' },
  { name: 'palm_tree', emoji: '🌴' },
  { name: 'evergreen_tree', emoji: '🌲' },
  { name: 'deciduous_tree', emoji: '🌳' },
  { name: 'chestnut', emoji: '🌰' },
  { name: 'seedling', emoji: '🌱' },
  { name: 'blossom', emoji: '🌼' },
  { name: 'ear_of_rice', emoji: '🌾' },
  { name: 'shell', emoji: '🐚' },
  { name: 'globe_with_meridians', emoji: '🌐' },
  { name: 'sun_with_face', emoji: '🌞' },
  { name: 'full_moon_with_face', emoji: '🌝' },
  { name: 'new_moon_with_face', emoji: '🌚' },
  { name: 'new_moon', emoji: '🌑' },
  { name: 'waxing_crescent_moon', emoji: '🌒' },
  { name: 'first_quarter_moon', emoji: '🌓' },
  { name: 'waxing_gibbous_moon', emoji: '🌔' },
  { name: 'full_moon', emoji: '🌕' },
  { name: 'waning_gibbous_moon', emoji: '🌖' },
  { name: 'last_quarter_moon', emoji: '🌗' },
  { name: 'waning_crescent_moon', emoji: '🌘' },
  { name: 'last_quarter_moon_with_face', emoji: '🌜' },
  { name: 'first_quarter_moon_with_face', emoji: '🌛' },
  { name: 'moon', emoji: '🌔', aliases: ['waxing_gibbous_moon'] },
  { name: 'earth_africa', emoji: '🌍' },
  { name: 'earth_americas', emoji: '🌎' },
  { name: 'earth_asia', emoji: '🌏' },
  { name: 'volcano', emoji: '🌋' },
  { name: 'milky_way', emoji: '🌌' },
  { name: 'partly_sunny', emoji: '⛅' },
  { name: 'bamboo', emoji: '🎍' },
  { name: 'gift_heart', emoji: '💝' },
  { name: 'dolls', emoji: '🎎' },
  { name: 'school_satchel', emoji: '🎒' },
  { name: 'mortar_board', emoji: '🎓' },
  { name: 'flags', emoji: '🎏' },
  { name: 'fireworks', emoji: '🎆' },
  { name: 'sparkler', emoji: '🎇' },
  { name: 'wind_chime', emoji: '🎐' },
  { name: 'rice_scene', emoji: '🎑' },
  { name: 'jack_o_lantern', emoji: '🎃' },
  { name: 'ghost', emoji: '👻' },
  { name: 'santa', emoji: '🎅' },
  { name: 'christmas_tree', emoji: '🎄' },
  { name: 'gift', emoji: '🎁' },
  { name: 'bell', emoji: '🔔' },
  { name: 'no_bell', emoji: '🔕' },
  { name: 'tanabata_tree', emoji: '🎋' },
  { name: 'tada', emoji: '🎉', aliases: ['party', 'celebration'] },
  { name: 'confetti_ball', emoji: '🎊' },
  { name: 'balloon', emoji: '🎈' },
  { name: 'crystal_ball', emoji: '🔮' },
  { name: 'cd', emoji: '💿' },
  { name: 'dvd', emoji: '📀' },
  { name: 'floppy_disk', emoji: '💾' },
  { name: 'camera', emoji: '📷' },
  { name: 'video_camera', emoji: '📹' },
  { name: 'movie_camera', emoji: '🎥' },
  { name: 'computer', emoji: '💻' },
  { name: 'tv', emoji: '📺' },
  { name: 'iphone', emoji: '📱' },
  { name: 'phone', emoji: '☎️', aliases: ['telephone'] },
  { name: 'telephone_receiver', emoji: '📞' },
  { name: 'pager', emoji: '📟' },
  { name: 'fax', emoji: '📠' },
  { name: 'minidisc', emoji: '💽' },
  { name: 'vhs', emoji: '📼' },
  { name: 'sound', emoji: '🔉' },
  { name: 'speaker', emoji: '🔈' },
  { name: 'mute', emoji: '🔇' },
  { name: 'loudspeaker', emoji: '📢' },
  { name: 'mega', emoji: '📣' },
  { name: 'hourglass', emoji: '⌛' },
  { name: 'hourglass_flowing_sand', emoji: '⏳' },
  { name: 'alarm_clock', emoji: '⏰' },
  { name: 'watch', emoji: '⌚' },
  { name: 'radio', emoji: '📻' },
  { name: 'satellite', emoji: '📡' },
  { name: 'loop', emoji: '➿' },
  { name: 'mag', emoji: '🔍' },
  { name: 'mag_right', emoji: '🔎' },
  { name: 'unlock', emoji: '🔓' },
  { name: 'lock', emoji: '🔒' },
  { name: 'lock_with_ink_pen', emoji: '🔏' },
  { name: 'closed_lock_with_key', emoji: '🔐' },
  { name: 'key', emoji: '🔑' },
  { name: 'bulb', emoji: '💡' },
  { name: 'flashlight', emoji: '🔦' },
  { name: 'high_brightness', emoji: '🔆' },
  { name: 'low_brightness', emoji: '🔅' },
  { name: 'electric_plug', emoji: '🔌' },
  { name: 'battery', emoji: '🔋' },
  { name: 'calling', emoji: '📲' },
  { name: 'email', emoji: '✉️', aliases: ['envelope'] },
  { name: 'mailbox', emoji: '📫' },
  { name: 'postbox', emoji: '📮' },
  { name: 'bath', emoji: '🛀' },
  { name: 'bathtub', emoji: '🛁' },
  { name: 'shower', emoji: '🚿' },
  { name: 'toilet', emoji: '🚽' },
  { name: 'wrench', emoji: '🔧' },
  { name: 'nut_and_bolt', emoji: '🔩' },
  { name: 'hammer', emoji: '🔨' },
  { name: 'seat', emoji: '💺' },
  { name: 'moneybag', emoji: '💰' },
  { name: 'yen', emoji: '💴' },
  { name: 'dollar', emoji: '💵' },
  { name: 'pound', emoji: '💷' },
  { name: 'euro', emoji: '💶' },
  { name: 'credit_card', emoji: '💳' },
  { name: 'money_with_wings', emoji: '💸' },
  { name: 'e-mail', emoji: '📧' },
  { name: 'inbox_tray', emoji: '📥' },
  { name: 'outbox_tray', emoji: '📤' },
  { name: 'envelope', emoji: '✉️' },
  { name: 'incoming_envelope', emoji: '📨' },
  { name: 'postal_horn', emoji: '📯' },
  { name: 'mailbox_closed', emoji: '📪' },
  { name: 'mailbox_with_mail', emoji: '📬' },
  { name: 'mailbox_with_no_mail', emoji: '📭' },
  { name: 'door', emoji: '🚪' },
  { name: 'smoking', emoji: '🚬' },
  { name: 'bomb', emoji: '💣' },
  { name: 'gun', emoji: '🔫' },
  { name: 'hocho', emoji: '🔪', aliases: ['knife'] },
  { name: 'pill', emoji: '💊' },
  { name: 'syringe', emoji: '💉' },
  { name: 'page_facing_up', emoji: '📄' },
  { name: 'page_with_curl', emoji: '📃' },
  { name: 'bookmark_tabs', emoji: '📑' },
  { name: 'bar_chart', emoji: '📊' },
  { name: 'chart_with_upwards_trend', emoji: '📈' },
  { name: 'chart_with_downwards_trend', emoji: '📉' },
  { name: 'scroll', emoji: '📜' },
  { name: 'clipboard', emoji: '📋' },
  { name: 'calendar', emoji: '📆' },
  { name: 'date', emoji: '📅' },
  { name: 'card_index', emoji: '📇' },
  { name: 'file_folder', emoji: '📁' },
  { name: 'open_file_folder', emoji: '📂' },
  { name: 'scissors', emoji: '✂️' },
  { name: 'pushpin', emoji: '📌' },
  { name: 'paperclip', emoji: '📎' },
  { name: 'black_nib', emoji: '✒️' },
  { name: 'pencil2', emoji: '✏️' },
  { name: 'straight_ruler', emoji: '📏' },
  { name: 'triangular_ruler', emoji: '📐' },
  { name: 'closed_book', emoji: '📕' },
  { name: 'green_book', emoji: '📗' },
  { name: 'blue_book', emoji: '📘' },
  { name: 'orange_book', emoji: '📙' },
  { name: 'notebook', emoji: '📓' },
  { name: 'notebook_with_decorative_cover', emoji: '📔' },
  { name: 'ledger', emoji: '📒' },
  { name: 'books', emoji: '📚' },
  { name: 'bookmark', emoji: '🔖' },
  { name: 'name_badge', emoji: '📛' },
  { name: 'microscope', emoji: '🔬' },
  { name: 'telescope', emoji: '🔭' },
  { name: 'newspaper', emoji: '📰' },
  { name: 'football', emoji: '🏈' },
  { name: 'basketball', emoji: '🏀' },
  { name: 'soccer', emoji: '⚽' },
  { name: 'baseball', emoji: '⚾' },
  { name: 'tennis', emoji: '🎾' },
  { name: '8ball', emoji: '🎱' },
  { name: 'rugby_football', emoji: '🏉' },
  { name: 'bowling', emoji: '🎳' },
  { name: 'golf', emoji: '⛳' },
  { name: 'mountain_bicyclist', emoji: '🚵' },
  { name: 'bicyclist', emoji: '🚴' },
  { name: 'horse_racing', emoji: '🏇' },
  { name: 'snowboarder', emoji: '🏂' },
  { name: 'swimmer', emoji: '🏊' },
  { name: 'surfer', emoji: '🏄' },
  { name: 'ski', emoji: '🎿' },
  { name: 'spades', emoji: '♠️' },
  { name: 'hearts', emoji: '♥️' },
  { name: 'clubs', emoji: '♣️' },
  { name: 'diamonds', emoji: '♦️' },
  { name: 'gem', emoji: '💎' },
  { name: 'ring', emoji: '💍' },
  { name: 'trophy', emoji: '🏆' },
  { name: 'musical_score', emoji: '🎼' },
  { name: 'musical_keyboard', emoji: '🎹' },
  { name: 'violin', emoji: '🎻' },
  { name: 'space_invader', emoji: '👾' },
  { name: 'video_game', emoji: '🎮' },
  { name: 'black_joker', emoji: '🃏' },
  { name: 'flower_playing_cards', emoji: '🎴' },
  { name: 'game_die', emoji: '🎲' },
  { name: 'dart', emoji: '🎯' },
  { name: 'mahjong', emoji: '🀄' },
  { name: 'clapper', emoji: '🎬' },
  { name: 'memo', emoji: '📝', aliases: ['pencil'] },
  { name: 'book', emoji: '📖' },
  { name: 'art', emoji: '🎨' },
  { name: 'microphone', emoji: '🎤' },
  { name: 'headphones', emoji: '🎧' },
  { name: 'trumpet', emoji: '🎺' },
  { name: 'saxophone', emoji: '🎷' },
  { name: 'guitar', emoji: '🎸' },
  { name: 'shoe', emoji: '👞' },
  { name: 'sandal', emoji: '👡' },
  { name: 'high_heel', emoji: '👠' },
  { name: 'lipstick', emoji: '💄' },
  { name: 'boot', emoji: '👢' },
  { name: 'shirt', emoji: '👕', aliases: ['tshirt'] },
  { name: 'necktie', emoji: '👔' },
  { name: 'womans_clothes', emoji: '👚' },
  { name: 'dress', emoji: '👗' },
  { name: 'running_shirt_with_sash', emoji: '🎽' },
  { name: 'jeans', emoji: '👖' },
  { name: 'kimono', emoji: '👘' },
  { name: 'bikini', emoji: '👙' },
  { name: 'ribbon', emoji: '🎀' },
  { name: 'tophat', emoji: '🎩' },
  { name: 'crown', emoji: '👑' },
  { name: 'womans_hat', emoji: '👒' },
  { name: 'mans_shoe', emoji: '👞' },
  { name: 'closed_umbrella', emoji: '🌂' },
  { name: 'briefcase', emoji: '💼' },
  { name: 'handbag', emoji: '👜' },
  { name: 'pouch', emoji: '👝' },
  { name: 'purse', emoji: '👛' },
  { name: 'eyeglasses', emoji: '👓' },
  { name: 'fishing_pole_and_fish', emoji: '🎣' },
  { name: 'coffee', emoji: '☕' },
  { name: 'tea', emoji: '🍵' },
  { name: 'sake', emoji: '🍶' },
  { name: 'baby_bottle', emoji: '🍼' },
  { name: 'beer', emoji: '🍺' },
  { name: 'beers', emoji: '🍻' },
  { name: 'cocktail', emoji: '🍸' },
  { name: 'tropical_drink', emoji: '🍹' },
  { name: 'wine_glass', emoji: '🍷' },
  { name: 'fork_and_knife', emoji: '🍴' },
  { name: 'pizza', emoji: '🍕' },
  { name: 'hamburger', emoji: '🍔' },
  { name: 'fries', emoji: '🍟' },
  { name: 'poultry_leg', emoji: '🍗' },
  { name: 'meat_on_bone', emoji: '🍖' },
  { name: 'spaghetti', emoji: '🍝' },
  { name: 'curry', emoji: '🍛' },
  { name: 'fried_shrimp', emoji: '🍤' },
  { name: 'bento', emoji: '🍱' },
  { name: 'sushi', emoji: '🍣' },
  { name: 'fish_cake', emoji: '🍥' },
  { name: 'rice_ball', emoji: '🍙' },
  { name: 'rice_cracker', emoji: '🍘' },
  { name: 'rice', emoji: '🍚' },
  { name: 'ramen', emoji: '🍜' },
  { name: 'stew', emoji: '🍲' },
  { name: 'oden', emoji: '🍢' },
  { name: 'dango', emoji: '🍡' },
  { name: 'egg', emoji: '🍳' },
  { name: 'bread', emoji: '🍞' },
  { name: 'doughnut', emoji: '🍩' },
  { name: 'custard', emoji: '🍮' },
  { name: 'icecream', emoji: '🍦' },
  { name: 'ice_cream', emoji: '🍨' },
  { name: 'shaved_ice', emoji: '🍧' },
  { name: 'birthday', emoji: '🎂' },
  { name: 'cake', emoji: '🍰' },
  { name: 'cookie', emoji: '🍪' },
  { name: 'chocolate_bar', emoji: '🍫' },
  { name: 'candy', emoji: '🍬' },
  { name: 'lollipop', emoji: '🍭' },
  { name: 'honey_pot', emoji: '🍯' },
  { name: 'apple', emoji: '🍎' },
  { name: 'green_apple', emoji: '🍏' },
  { name: 'tangerine', emoji: '🍊' },
  { name: 'lemon', emoji: '🍋' },
  { name: 'cherries', emoji: '🍒' },
  { name: 'grapes', emoji: '🍇' },
  { name: 'watermelon', emoji: '🍉' },
  { name: 'strawberry', emoji: '🍓' },
  { name: 'peach', emoji: '🍑' },
  { name: 'melon', emoji: '🍈' },
  { name: 'banana', emoji: '🍌' },
  { name: 'pear', emoji: '🍐' },
  { name: 'pineapple', emoji: '🍍' },
  { name: 'sweet_potato', emoji: '🍠' },
  { name: 'eggplant', emoji: '🍆' },
  { name: 'tomato', emoji: '🍅' },
  { name: 'corn', emoji: '🌽' },
  { name: 'rocket', emoji: '🚀' },
  { name: 'helicopter', emoji: '🚁' },
  { name: 'steam_locomotive', emoji: '🚂' },
  { name: 'railway_car', emoji: '🚃' },
  { name: 'bullettrain_side', emoji: '🚄' },
  { name: 'bullettrain_front', emoji: '🚅' },
  { name: 'train2', emoji: '🚆' },
  { name: 'metro', emoji: '🚇' },
  { name: 'station', emoji: '🚉' },
  { name: 'tram', emoji: '🚊' },
  { name: 'bus', emoji: '🚌' },
  { name: 'oncoming_bus', emoji: '🚍' },
  { name: 'trolleybus', emoji: '🚎' },
  { name: 'busstop', emoji: '🚏' },
  { name: 'minibus', emoji: '🚐' },
  { name: 'ambulance', emoji: '🚑' },
  { name: 'fire_engine', emoji: '🚒' },
  { name: 'police_car', emoji: '🚓' },
  { name: 'oncoming_police_car', emoji: '🚔' },
  { name: 'taxi', emoji: '🚕' },
  { name: 'oncoming_taxi', emoji: '🚖' },
  { name: 'car', emoji: '🚗', aliases: ['red_car'] },
  { name: 'oncoming_automobile', emoji: '🚘' },
  { name: 'blue_car', emoji: '🚙' },
  { name: 'truck', emoji: '🚚' },
  { name: 'articulated_lorry', emoji: '🚛' },
  { name: 'tractor', emoji: '🚜' },
  { name: 'bike', emoji: '🚲' },
  { name: 'rotating_light', emoji: '🚨' },
  { name: 'warning', emoji: '⚠️' },
  { name: 'construction', emoji: '🚧' },
  { name: 'beginner', emoji: '🔰' },
  { name: 'fuelpump', emoji: '⛽' },
  { name: 'vertical_traffic_light', emoji: '🚦' },
  { name: 'traffic_light', emoji: '🚥' },
  { name: 'checkered_flag', emoji: '🏁' },
  { name: 'ship', emoji: '🚢' },
  { name: 'ferris_wheel', emoji: '🎡' },
  { name: 'roller_coaster', emoji: '🎢' },
  { name: 'carousel_horse', emoji: '🎠' },
  { name: 'building_construction', emoji: '🏗️' },
  { name: 'foggy', emoji: '🌁' },
  { name: 'tokyo_tower', emoji: '🗼' },
  { name: 'factory', emoji: '🏭' },
  { name: 'fountain', emoji: '⛲' },
  { name: 'rice_scene', emoji: '🎑' },
  { name: 'mountain', emoji: '⛰️' },
  { name: 'mountain_snow', emoji: '🏔️' },
  { name: 'mount_fuji', emoji: '🗻' },
  { name: 'volcano', emoji: '🌋' },
  { name: 'japan', emoji: '🗾' },
  { name: 'tent', emoji: '⛺' },
  { name: 'railway_track', emoji: '🛤️' },
  { name: 'sunrise', emoji: '🌅' },
  { name: 'sunrise_over_mountains', emoji: '🌄' },
  { name: 'desert', emoji: '🏜️' },
  { name: 'beach_umbrella', emoji: '🏖️' },
  { name: 'desert_island', emoji: '🏝️' },
  { name: 'city_sunrise', emoji: '🌇' },
  { name: 'city_sunset', emoji: '🌆' },
  { name: 'cityscape', emoji: '🏙️' },
  { name: 'night_with_stars', emoji: '🌃' },
  { name: 'bridge_at_night', emoji: '🌉' },
  { name: 'milky_way', emoji: '🌌' },
  { name: 'stars', emoji: '🌠' },
  { name: 'sparkler', emoji: '🎇' },
  { name: 'fireworks', emoji: '🎆' },
  { name: 'rainbow', emoji: '🌈' },
  { name: 'houses', emoji: '🏘️' },
  { name: 'european_castle', emoji: '🏰' },
  { name: 'japanese_castle', emoji: '🏯' },
  { name: 'stadium', emoji: '🏟️' },
  { name: 'statue_of_liberty', emoji: '🗽' },
  { name: 'house', emoji: '🏠' },
  { name: 'house_with_garden', emoji: '🏡' },
  { name: 'derelict_house', emoji: '🏚️' },
  { name: 'office', emoji: '🏢' },
  { name: 'department_store', emoji: '🏬' },
  { name: 'post_office', emoji: '🏣' },
  { name: 'european_post_office', emoji: '🏤' },
  { name: 'hospital', emoji: '🏥' },
  { name: 'bank', emoji: '🏦' },
  { name: 'hotel', emoji: '🏨' },
  { name: 'convenience_store', emoji: '🏪' },
  { name: 'school', emoji: '🏫' },
  { name: 'love_hotel', emoji: '🏩' },
  { name: 'wedding', emoji: '💒' },
  { name: 'classical_building', emoji: '🏛️' },
  { name: 'church', emoji: '⛪' },
  { name: 'mosque', emoji: '🕌' },
  { name: 'synagogue', emoji: '🕍' },
  { name: 'kaaba', emoji: '🕋' },
  { name: 'shinto_shrine', emoji: '⛩️' },
  { name: 'white_check_mark', emoji: '✅' },
  { name: 'heavy_check_mark', emoji: '✔️' },
  { name: 'ballot_box_with_check', emoji: '☑️' },
  { name: 'heavy_plus_sign', emoji: '➕' },
  { name: 'heavy_minus_sign', emoji: '➖' },
  { name: 'heavy_division_sign', emoji: '➗' },
  { name: 'heavy_multiplication_x', emoji: '✖️' },
  { name: 'x', emoji: '❌' },
  { name: 'negative_squared_cross_mark', emoji: '❎' },
  { name: 'heavy_dollar_sign', emoji: '💲' },
  { name: 'currency_exchange', emoji: '💱' },
  { name: 'copyright', emoji: '©️' },
  { name: 'registered', emoji: '®️' },
  { name: 'tm', emoji: '™️' },
  { name: 'hash', emoji: '#️⃣' },
  { name: 'zero', emoji: '0️⃣' },
  { name: 'one', emoji: '1️⃣' },
  { name: 'two', emoji: '2️⃣' },
  { name: 'three', emoji: '3️⃣' },
  { name: 'four', emoji: '4️⃣' },
  { name: 'five', emoji: '5️⃣' },
  { name: 'six', emoji: '6️⃣' },
  { name: 'seven', emoji: '7️⃣' },
  { name: 'eight', emoji: '8️⃣' },
  { name: 'nine', emoji: '9️⃣' },
  { name: 'keycap_ten', emoji: '🔟' },
  { name: '100', emoji: '💯' },
  { name: '1234', emoji: '🔢' },
  { name: 'ok', emoji: '🆗' },
  { name: 'new', emoji: '🆕' },
  { name: 'free', emoji: '🆓' },
  { name: 'cool', emoji: '🆒' },
  { name: 'ng', emoji: '🆖' },
  { name: 'signal_strength', emoji: '📶' },
  { name: 'cinema', emoji: '🎦' },
  { name: 'koko', emoji: '🈁' },
  { name: 'u6307', emoji: '🈯' },
  { name: 'u7a7a', emoji: '🈳' },
  { name: 'u6e80', emoji: '🈵' },
  { name: 'u5408', emoji: '🈴' },
  { name: 'u7981', emoji: '🈲' },
  { name: 'ideograph_advantage', emoji: '🉐' },
  { name: 'u5272', emoji: '🈹' },
  { name: 'u55b6', emoji: '🈺' },
  { name: 'u6709', emoji: '🈶' },
  { name: 'u7121', emoji: '🈚' },
  { name: 'restroom', emoji: '🚻' },
  { name: 'mens', emoji: '🚹' },
  { name: 'womens', emoji: '🚺' },
  { name: 'baby_symbol', emoji: '🚼' },
  { name: 'wc', emoji: '🚾' },
  { name: 'potable_water', emoji: '🚰' },
  { name: 'put_litter_in_its_place', emoji: '🚮' },
  { name: 'parking', emoji: '🅿️' },
  { name: 'wheelchair', emoji: '♿' },
  { name: 'no_smoking', emoji: '🚭' },
  { name: 'u6708', emoji: '🈷️' },
  { name: 'u7533', emoji: '🈸' },
  { name: 'sa', emoji: '🈂️' },
  { name: 'm', emoji: 'Ⓜ️' },
  { name: 'passport_control', emoji: '🛂' },
  { name: 'baggage_claim', emoji: '🛄' },
  { name: 'left_luggage', emoji: '🛅' },
  { name: 'customs', emoji: '🛃' },
  { name: 'accept', emoji: '🉑' },
  { name: 'secret', emoji: '㊙️' },
  { name: 'congratulations', emoji: '㊗️' },
  { name: 'cl', emoji: '🆑' },
  { name: 'sos', emoji: '🆘' },
  { name: 'id', emoji: '🆔' },
  { name: 'no_entry_sign', emoji: '🚫' },
  { name: 'underage', emoji: '🔞' },
  { name: 'no_mobile_phones', emoji: '📵' },
  { name: 'do_not_litter', emoji: '🚯' },
  { name: 'non-potable_water', emoji: '🚱' },
  { name: 'no_bicycles', emoji: '🚳' },
  { name: 'no_pedestrians', emoji: '🚷' },
  { name: 'children_crossing', emoji: '🚸' },
  { name: 'no_entry', emoji: '⛔' },
  { name: 'eight_spoked_asterisk', emoji: '✳️' },
  { name: 'eight_pointed_black_star', emoji: '✴️' },
  { name: 'heart_decoration', emoji: '💟' },
  { name: 'vs', emoji: '🆚' },
  { name: 'vibration_mode', emoji: '📳' },
  { name: 'mobile_phone_off', emoji: '📴' },
  { name: 'chart', emoji: '💹' },
  { name: 'currency_exchange', emoji: '💱' },
  { name: 'aries', emoji: '♈' },
  { name: 'taurus', emoji: '♉' },
  { name: 'gemini', emoji: '♊' },
  { name: 'cancer', emoji: '♋' },
  { name: 'leo', emoji: '♌' },
  { name: 'virgo', emoji: '♍' },
  { name: 'libra', emoji: '♎' },
  { name: 'scorpius', emoji: '♏' },
  { name: 'sagittarius', emoji: '♐' },
  { name: 'capricorn', emoji: '♑' },
  { name: 'aquarius', emoji: '♒' },
  { name: 'pisces', emoji: '♓' },
  { name: 'ophiuchus', emoji: '⛎' },
  { name: 'six_pointed_star', emoji: '🔯' },
  { name: 'negative_squared_cross_mark', emoji: '❎' },
  { name: 'a', emoji: '🅰️' },
  { name: 'b', emoji: '🅱️' },
  { name: 'ab', emoji: '🆎' },
  { name: 'o2', emoji: '🅾️' },
  { name: 'diamond_shape_with_a_dot_inside', emoji: '💠' },
  { name: 'recycle', emoji: '♻️' },
  { name: 'end', emoji: '🔚' },
  { name: 'on', emoji: '🔛' },
  { name: 'soon', emoji: '🔜' },
  { name: 'top', emoji: '🔝' },
  { name: 'wavy_dash', emoji: '〰️' },
  { name: 'curly_loop', emoji: '➰' },
  { name: 'radio_button', emoji: '🔘' },
  { name: 'white_circle', emoji: '⚪' },
  { name: 'black_circle', emoji: '⚫' },
  { name: 'red_circle', emoji: '🔴' },
  { name: 'large_blue_circle', emoji: '🔵' },
  { name: 'small_orange_diamond', emoji: '🔸' },
  { name: 'small_blue_diamond', emoji: '🔹' },
  { name: 'large_orange_diamond', emoji: '🔶' },
  { name: 'large_blue_diamond', emoji: '🔷' },
  { name: 'small_red_triangle', emoji: '🔺' },
  { name: 'black_small_square', emoji: '▪️' },
  { name: 'white_small_square', emoji: '▫️' },
  { name: 'black_large_square', emoji: '⬛' },
  { name: 'white_large_square', emoji: '⬜' },
  { name: 'small_red_triangle_down', emoji: '🔻' },
  { name: 'black_medium_square', emoji: '◼️' },
  { name: 'white_medium_square', emoji: '◻️' },
  { name: 'black_medium_small_square', emoji: '◾' },
  { name: 'white_medium_small_square', emoji: '◽' },
  { name: 'black_square_button', emoji: '🔲' },
  { name: 'white_square_button', emoji: '🔳' },
  { name: 'clock1', emoji: '🕐' },
  { name: 'clock2', emoji: '🕑' },
  { name: 'clock3', emoji: '🕒' },
  { name: 'clock4', emoji: '🕓' },
  { name: 'clock5', emoji: '🕔' },
  { name: 'clock6', emoji: '🕕' },
  { name: 'clock7', emoji: '🕖' },
  { name: 'clock8', emoji: '🕗' },
  { name: 'clock9', emoji: '🕘' },
  { name: 'clock10', emoji: '🕙' },
  { name: 'clock11', emoji: '🕚' },
  { name: 'clock12', emoji: '🕛' },
  { name: 'clock130', emoji: '🕜' },
  { name: 'clock230', emoji: '🕝' },
  { name: 'clock330', emoji: '🕞' },
  { name: 'clock430', emoji: '🕟' },
  { name: 'clock530', emoji: '🕠' },
  { name: 'clock630', emoji: '🕡' },
  { name: 'clock730', emoji: '🕢' },
  { name: 'clock830', emoji: '🕣' },
  { name: 'clock930', emoji: '🕤' },
  { name: 'clock1030', emoji: '🕥' },
  { name: 'clock1130', emoji: '🕦' },
  { name: 'clock1230', emoji: '🕧' },
  // GitHub-ish review shorthand
  { name: 'shipit', emoji: '🐿️', aliases: ['squirrel'] },
  { name: 'octocat', emoji: '🐙' },
  { name: 'bowtie', emoji: '👔' },
  { name: 'tada', emoji: '🎉' },
  { name: 'rocket', emoji: '🚀' },
  { name: 'eyes', emoji: '👀' },
  { name: 'thinking', emoji: '🤔', aliases: ['thinking_face'] },
  { name: 'shrug', emoji: '🤷' },
  { name: 'facepalm', emoji: '🤦' },
  { name: 'rofl', emoji: '🤣' },
  { name: 'handshake', emoji: '🤝' },
  { name: 'pray', emoji: '🙏' },
  { name: 'raised_hands', emoji: '🙌' },
  { name: 'clap', emoji: '👏' },
  { name: 'muscle', emoji: '💪' },
  { name: 'brain', emoji: '🧠' },
  { name: 'nerd_face', emoji: '🤓' },
  { name: 'robot', emoji: '🤖' },
  { name: 'partying_face', emoji: '🥳' },
  { name: 'woozy_face', emoji: '🥴' },
  { name: 'hot_face', emoji: '🥵' },
  { name: 'cold_face', emoji: '🥶' },
  { name: 'exploding_head', emoji: '🤯' },
  { name: 'cowboy_hat_face', emoji: '🤠' },
  { name: 'pleading_face', emoji: '🥺' },
  { name: 'star_struck', emoji: '🤩' },
  { name: 'zany_face', emoji: '🤪' },
  { name: 'shushing_face', emoji: '🤫' },
  { name: 'face_with_monocle', emoji: '🧐' },
  { name: 'face_with_raised_eyebrow', emoji: '🤨' },
  { name: 'infinity', emoji: '♾️' },
  { name: 'checkered_flag', emoji: '🏁' },
  { name: 'bug', emoji: '🐛' },
  { name: 'hammer_and_wrench', emoji: '🛠️' },
  { name: 'gear', emoji: '⚙️' },
  { name: 'link', emoji: '🔗' },
  { name: 'package', emoji: '📦' },
  { name: 'memo', emoji: '📝' },
  { name: 'bulb', emoji: '💡' },
  { name: 'warning', emoji: '⚠️' },
  { name: 'heavy_check_mark', emoji: '✔️' },
  { name: 'x', emoji: '❌' },
  { name: 'construction', emoji: '🚧' },
  { name: 'rocket', emoji: '🚀' },
  { name: 'ship', emoji: '🚢' },
  { name: 'hourglass_flowing_sand', emoji: '⏳' },
  { name: 'mag', emoji: '🔍' },
  { name: 'bookmark', emoji: '🔖' },
  { name: 'label', emoji: '🏷️' },
  { name: 'pushpin', emoji: '📌' },
  { name: 'paperclip', emoji: '📎' },
  { name: 'file_folder', emoji: '📁' },
  { name: 'open_file_folder', emoji: '📂' },
  { name: 'chart_with_upwards_trend', emoji: '📈' },
  { name: 'chart_with_downwards_trend', emoji: '📉' },
  { name: 'bar_chart', emoji: '📊' },
  { name: 'clipboard', emoji: '📋' },
  { name: 'page_facing_up', emoji: '📄' },
  { name: 'newspaper', emoji: '📰' },
  { name: 'books', emoji: '📚' },
  { name: 'book', emoji: '📖' },
  { name: 'computer', emoji: '💻' },
  { name: 'keyboard', emoji: '⌨️' },
  { name: 'desktop_computer', emoji: '🖥️' },
  { name: 'printer', emoji: '🖨️' },
  { name: 'trackball', emoji: '🖲️' },
  { name: 'joystick', emoji: '🕹️' },
  { name: 'compression', emoji: '🗜️' },
  { name: 'minidisc', emoji: '💽' },
  { name: 'floppy_disk', emoji: '💾' },
  { name: 'cd', emoji: '💿' },
  { name: 'dvd', emoji: '📀' },
  { name: 'vhs', emoji: '📼' },
  { name: 'camera', emoji: '📷' },
  { name: 'camera_flash', emoji: '📸' },
  { name: 'video_camera', emoji: '📹' },
  { name: 'movie_camera', emoji: '🎥' },
  { name: 'film_projector', emoji: '📽️' },
  { name: 'film_strip', emoji: '🎞️' },
  { name: 'telephone_receiver', emoji: '📞' },
  { name: 'pager', emoji: '📟' },
  { name: 'fax', emoji: '📠' },
  { name: 'tv', emoji: '📺' },
  { name: 'radio', emoji: '📻' },
  { name: 'studio_microphone', emoji: '🎙️' },
  { name: 'level_slider', emoji: '🎚️' },
  { name: 'control_knobs', emoji: '🎛️' },
  { name: 'stopwatch', emoji: '⏱️' },
  { name: 'timer_clock', emoji: '⏲️' },
  { name: 'alarm_clock', emoji: '⏰' },
  { name: 'mantelpiece_clock', emoji: '🕰️' },
  { name: 'hourglass', emoji: '⌛' },
  { name: 'satellite', emoji: '📡' },
  { name: 'battery', emoji: '🔋' },
  { name: 'electric_plug', emoji: '🔌' },
  { name: 'bulb', emoji: '💡' },
  { name: 'flashlight', emoji: '🔦' },
  { name: 'candle', emoji: '🕯️' },
  { name: 'wastebasket', emoji: '🗑️' },
  { name: 'oil_drum', emoji: '🛢️' },
  { name: 'money_with_wings', emoji: '💸' },
  { name: 'dollar', emoji: '💵' },
  { name: 'yen', emoji: '💴' },
  { name: 'euro', emoji: '💶' },
  { name: 'pound', emoji: '💷' },
  { name: 'moneybag', emoji: '💰' },
  { name: 'credit_card', emoji: '💳' },
  { name: 'gem', emoji: '💎' },
  { name: 'balance_scale', emoji: '⚖️' },
  { name: 'wrench', emoji: '🔧' },
  { name: 'hammer', emoji: '🔨' },
  { name: 'hammer_and_pick', emoji: '⚒️' },
  { name: 'hammer_and_wrench', emoji: '🛠️' },
  { name: 'pick', emoji: '⛏️' },
  { name: 'nut_and_bolt', emoji: '🔩' },
  { name: 'gear', emoji: '⚙️' },
  { name: 'chains', emoji: '⛓️' },
  { name: 'gun', emoji: '🔫' },
  { name: 'bomb', emoji: '💣' },
  { name: 'hocho', emoji: '🔪' },
  { name: 'dagger', emoji: '🗡️' },
  { name: 'crossed_swords', emoji: '⚔️' },
  { name: 'shield', emoji: '🛡️' },
  { name: 'smoking', emoji: '🚬' },
  { name: 'coffin', emoji: '⚰️' },
  { name: 'funeral_urn', emoji: '⚱️' },
  { name: 'amphora', emoji: '🏺' },
  { name: 'crystal_ball', emoji: '🔮' },
  { name: 'prayer_beads', emoji: '📿' },
  { name: 'barber', emoji: '💈' },
  { name: 'alembic', emoji: '⚗️' },
  { name: 'telescope', emoji: '🔭' },
  { name: 'microscope', emoji: '🔬' },
  { name: 'hole', emoji: '🕳️' },
  { name: 'pill', emoji: '💊' },
  { name: 'syringe', emoji: '💉' },
  { name: 'thermometer', emoji: '🌡️' },
  { name: 'label', emoji: '🏷️' },
  { name: 'bookmark', emoji: '🔖' },
  { name: 'toilet', emoji: '🚽' },
  { name: 'shower', emoji: '🚿' },
  { name: 'bathtub', emoji: '🛁' },
  { name: 'key', emoji: '🔑' },
  { name: 'old_key', emoji: '🗝️' },
  { name: 'couch_and_lamp', emoji: '🛋️' },
  { name: 'sleeping_bed', emoji: '🛌' },
  { name: 'bed', emoji: '🛏️' },
  { name: 'door', emoji: '🚪' },
  { name: 'bellhop_bell', emoji: '🛎️' },
  { name: 'framed_picture', emoji: '🖼️' },
  { name: 'world_map', emoji: '🗺️' },
  { name: 'umbrella', emoji: '☂️' },
  { name: 'moyai', emoji: '🗿' },
  { name: 'shopping', emoji: '🛍️' },
  { name: 'shopping_cart', emoji: '🛒' },
  { name: 'balloon', emoji: '🎈' },
  { name: 'flags', emoji: '🎏' },
  { name: 'ribbon', emoji: '🎀' },
  { name: 'gift', emoji: '🎁' },
  { name: 'confetti_ball', emoji: '🎊' },
  { name: 'tada', emoji: '🎉' },
  { name: 'dolls', emoji: '🎎' },
  { name: 'wind_chime', emoji: '🎐' },
  { name: 'crossed_flags', emoji: '🎌' },
  { name: 'izakaya_lantern', emoji: '🏮' },
  { name: 'email', emoji: '✉️' },
  { name: 'envelope_with_arrow', emoji: '📩' },
  { name: 'incoming_envelope', emoji: '📨' },
  { name: 'e-mail', emoji: '📧' },
  { name: 'love_letter', emoji: '💌' },
  { name: 'inbox_tray', emoji: '📥' },
  { name: 'outbox_tray', emoji: '📤' },
  { name: 'package', emoji: '📦' },
  { name: 'label', emoji: '🏷️' },
  { name: 'closed_mailbox_with_lowered_flag', emoji: '📪' },
  { name: 'closed_mailbox_with_raised_flag', emoji: '📫' },
  { name: 'open_mailbox_with_raised_flag', emoji: '📬' },
  { name: 'open_mailbox_with_lowered_flag', emoji: '📭' },
  { name: 'postbox', emoji: '📮' },
  { name: 'postal_horn', emoji: '📯' },
  { name: 'scroll', emoji: '📜' },
  { name: 'page_with_curl', emoji: '📃' },
  { name: 'page_facing_up', emoji: '📄' },
  { name: 'bookmark_tabs', emoji: '📑' },
  { name: 'bar_chart', emoji: '📊' },
  { name: 'chart_with_upwards_trend', emoji: '📈' },
  { name: 'chart_with_downwards_trend', emoji: '📉' },
  { name: 'spiral_notepad', emoji: '🗒️' },
  { name: 'spiral_calendar', emoji: '🗓️' },
  { name: 'calendar', emoji: '📆' },
  { name: 'date', emoji: '📅' },
  { name: 'card_index', emoji: '📇' },
  { name: 'card_file_box', emoji: '🗃️' },
  { name: 'ballot_box', emoji: '🗳️' },
  { name: 'file_cabinet', emoji: '🗄️' },
  { name: 'clipboard', emoji: '📋' },
  { name: 'file_folder', emoji: '📁' },
  { name: 'open_file_folder', emoji: '📂' },
  { name: 'card_index_dividers', emoji: '🗂️' },
  { name: 'newspaper_roll', emoji: '🗞️' },
  { name: 'newspaper', emoji: '📰' },
  { name: 'notebook', emoji: '📓' },
  { name: 'notebook_with_decorative_cover', emoji: '📔' },
  { name: 'ledger', emoji: '📒' },
  { name: 'closed_book', emoji: '📕' },
  { name: 'green_book', emoji: '📗' },
  { name: 'blue_book', emoji: '📘' },
  { name: 'orange_book', emoji: '📙' },
  { name: 'books', emoji: '📚' },
  { name: 'book', emoji: '📖' },
  { name: 'bookmark', emoji: '🔖' },
  { name: 'link', emoji: '🔗' },
  { name: 'paperclip', emoji: '📎' },
  { name: 'paperclips', emoji: '🖇️' },
  { name: 'triangular_ruler', emoji: '📐' },
  { name: 'straight_ruler', emoji: '📏' },
  { name: 'pushpin', emoji: '📌' },
  { name: 'round_pushpin', emoji: '📍' },
  { name: 'scissors', emoji: '✂️' },
  { name: 'pen', emoji: '🖊️' },
  { name: 'fountain_pen', emoji: '🖋️' },
  { name: 'black_nib', emoji: '✒️' },
  { name: 'paintbrush', emoji: '🖌️' },
  { name: 'crayon', emoji: '🖍️' },
  { name: 'memo', emoji: '📝' },
  { name: 'pencil2', emoji: '✏️' },
  { name: 'mag', emoji: '🔍' },
  { name: 'mag_right', emoji: '🔎' },
  { name: 'lock_with_ink_pen', emoji: '🔏' },
  { name: 'closed_lock_with_key', emoji: '🔐' },
  { name: 'lock', emoji: '🔒' },
  { name: 'unlock', emoji: '🔓' },
] as const;

/** Popular defaults when user types bare `:` */
const POPULAR_NAMES = [
  '+1',
  '-1',
  'smile',
  'tada',
  'rocket',
  'eyes',
  'heart',
  'fire',
  '100',
  'clap',
  'pray',
  'thinking',
  'shipit',
  'warning',
  'white_check_mark',
  'x',
  'bug',
  'sparkles',
  'raised_hands',
  'sweat_smile',
] as const;

const BY_NAME = new Map<string, EmojiEntry>();
for (const e of EMOJI_SHORTCODES) {
  if (!BY_NAME.has(e.name)) BY_NAME.set(e.name, e);
  for (const a of e.aliases || []) {
    const ak = String(a || '').trim();
    if (ak && !BY_NAME.has(ak)) BY_NAME.set(ak, e);
  }
}

/**
 * Detect `:query` token at cursor (GitHub-style).
 * Requires start-of-text or whitespace / open bracket before `:`.
 * @returns {{ query: string, start: number, end: number }|null}
 */
export function detectEmojiTrigger(text: unknown, cursor: unknown) {
  const s = String(text || '');
  const c = Math.max(0, Math.min(cursor == null ? s.length : Number(cursor), s.length));
  if (!Number.isFinite(c)) return null;
  const before = s.slice(0, c);
  // Avoid matching mid-token like emails; require boundary before `:`
  const m = before.match(/(^|[\s([{])(:([a-zA-Z0-9_+-]{0,40}))$/);
  if (!m) return null;
  const full = m[2] || ''; // includes leading :
  const query = m[3] || '';
  const start = c - full.length;
  return { query, start, end: c };
}

function entrySearchBlob(e: EmojiEntry): string {
  const parts = [e.name, ...(e.aliases || [])];
  return parts.join(' ').toLowerCase();
}

/**
 * Filter shortcodes by query (prefix preferred, then substring).
 * Empty query → popular set.
 */
export function filterEmojis(query: unknown, limit = 12): EmojiEntry[] {
  const lim = Math.max(1, Math.min(40, Number(limit) || 12));
  const q = String(query || '')
    .trim()
    .toLowerCase()
    .replace(/^:+|:+$/g, '');
  if (!q) {
    const out: EmojiEntry[] = [];
    const seen = new Set<string>();
    for (const name of POPULAR_NAMES) {
      const e = BY_NAME.get(name);
      if (!e || seen.has(e.name)) continue;
      seen.add(e.name);
      out.push(e);
      if (out.length >= lim) break;
    }
    // Pad with list head if needed
    for (const e of EMOJI_SHORTCODES) {
      if (out.length >= lim) break;
      if (seen.has(e.name)) continue;
      seen.add(e.name);
      out.push(e);
    }
    return out;
  }

  const prefix: EmojiEntry[] = [];
  const substr: EmojiEntry[] = [];
  const seen = new Set<string>();
  for (const e of EMOJI_SHORTCODES) {
    if (seen.has(e.name)) continue;
    const blob = entrySearchBlob(e);
    const name = e.name.toLowerCase();
    const aliasHit = (e.aliases || []).some((a) =>
      String(a).toLowerCase().startsWith(q)
    );
    if (name.startsWith(q) || aliasHit) {
      seen.add(e.name);
      prefix.push(e);
    } else if (blob.includes(q) || name.includes(q)) {
      seen.add(e.name);
      substr.push(e);
    }
    if (prefix.length >= lim) break;
  }
  return prefix.concat(substr).slice(0, lim);
}

/**
 * Replace `:query` with `:name: ` (trailing space, GitHub shortcode form).
 */
export function applyEmojiInsertion(
  text: unknown,
  trigger: { start: number; end: number } | null | undefined,
  entry: EmojiEntry | string | null | undefined
) {
  const s = String(text || '');
  if (!trigger) return { text: s, cursor: s.length };
  const name =
    typeof entry === 'string'
      ? entry.replace(/^:+|:+$/g, '')
      : String(entry?.name || '').replace(/^:+|:+$/g, '');
  if (!name) return { text: s, cursor: s.length };
  const insertion = `:${name}: `;
  const a = Math.max(0, Number(trigger.start) || 0);
  const b = Math.max(a, Number(trigger.end) || a);
  const next = s.slice(0, a) + insertion + s.slice(b);
  return { text: next, cursor: a + insertion.length };
}

export function emojiMenuLabel(entry: EmojiEntry): string {
  return `:${entry.name}:`;
}

/**
 * Expand `:shortcode:` tokens to Unicode emoji for markdown preview/render.
 * Unknown codes are left unchanged.
 */
export function expandEmojiShortcodes(text: unknown): string {
  const s = String(text ?? '');
  if (!s.includes(':')) return s;
  return s.replace(/:([a-zA-Z0-9_+-]+):/g, (full, name: string) => {
    const key = String(name || '');
    const entry =
      BY_NAME.get(key) ||
      BY_NAME.get(key.replace(/-/g, '_')) ||
      null;
    return entry?.emoji || full;
  });
}
