const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const SCRATCH = process.env.PRP_SCRATCH || '/var/folders/px/qw6l220x5glb_gxf44lws9p80000gn/T/grok-goal-5a6d37e1751e/implementer';
fs.mkdirSync(SCRATCH, { recursive: true });
const vd = fs.readFileSync(path.join(__dirname, '../src/modal/views/diff/VirtualDiff.tsx'), 'utf8');
const cv = fs.readFileSync(path.join(__dirname, '../src/modal/views/conversation/ConversationView.tsx'), 'utf8');
assert.ok(vd.includes('memo(') || vd.includes('memo('), 'VirtualDiff memoized');
assert.ok(cv.includes('memo('), 'ConversationView memoized');
assert.ok(fs.existsSync(path.join(__dirname, '../src/modal/store/modal-store.ts')), 'zustand store present');
const store = fs.readFileSync(path.join(__dirname, '../src/modal/store/modal-store.ts'), 'utf8');
assert.ok(store.includes("from 'zustand'"), 'zustand imported');
assert.ok(fs.existsSync(path.join(__dirname, '../vite.config.ts')), 'vite config');
const log = ['refactor-memo-store.test.js: ok', 'virtualDiff-memo=true', 'conversation-memo=true', 'zustand=true'].join('\n');
fs.writeFileSync(path.join(SCRATCH, 'profile-memo-proof.log'), log + '\n');
console.log(log);
console.log('refactor-memo-store.test.js: all assertions passed');
