/**
 * AUTO-GENERATED from src/modal/lib/aside-lists.ts
 * SOURCE OF TRUTH: src/modal/lib/aside-lists.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  filterCommitsByQuery: () => filterCommitsByQuery,
  filterFilesByQuery: () => filterFilesByQuery,
  filterTagsByQuery: () => filterTagsByQuery,
  mayHaveMoreCommits: () => mayHaveMoreCommits,
  mayHaveMoreFiles: () => mayHaveMoreFiles,
  takeCommitsForTimeline: () => takeCommitsForTimeline,
  takeVisibleTreeNodes: () => takeVisibleTreeNodes
});
module.exports = __toCommonJS(stdin_exports);
function takeCommitsForTimeline(commits, max = 12) {
  const list = Array.isArray(commits) ? [...commits].reverse() : [];
  const limit = Number.isFinite(max) && max > 0 ? Math.floor(max) : 12;
  const items = list.slice(0, limit).map((c, i) => {
    const fullMsg = String(c.message || "").trim();
    const firstLine = fullMsg.split("\n")[0] || "(no message)";
    const shortMessage = firstLine.length > 72 ? `${firstLine.slice(0, 69)}\u2026` : firstLine;
    const sha = String(c.sha || "");
    return {
      key: sha || `commit-${i}`,
      sha,
      shortSha: sha ? sha.slice(0, 7) : "-------",
      message: shortMessage,
      fullMessage: fullMsg,
      author: c.author || "",
      at: c.date || c.committedAt || c.authoredAt || ""
    };
  });
  return {
    items,
    total: list.length,
    truncated: Math.max(0, list.length - items.length)
  };
}
function takeVisibleTreeNodes(visibleNodes, max = 20) {
  const list = Array.isArray(visibleNodes) ? visibleNodes : [];
  const limit = Number.isFinite(max) && max > 0 ? Math.floor(max) : 20;
  if (list.length <= limit) {
    return { nodes: list, total: list.length, truncated: 0 };
  }
  return {
    nodes: list.slice(0, limit),
    total: list.length,
    truncated: list.length - limit
  };
}
function filterCommitsByQuery(commits, query) {
  const list = Array.isArray(commits) ? commits : [];
  const q = String(query || "").trim().toLowerCase();
  if (!q) return list;
  const words = q.split(/\s+/).filter(Boolean);
  return list.filter((c) => {
    const hay = [c?.sha, c?.message, c?.author, c?.date].filter(Boolean).join(" ").toLowerCase();
    return words.every((w) => hay.includes(w));
  });
}
function filterFilesByQuery(files, query) {
  const list = Array.isArray(files) ? files : [];
  const q = String(query || "").trim().toLowerCase();
  if (!q) return list;
  const words = q.split(/\s+/).filter(Boolean);
  return list.filter((f) => {
    const path = f?.filename || f?.path || f?.previous_filename || "";
    const hay = [path, f?.status, f?.previous_filename].filter(Boolean).join(" ").toLowerCase();
    return words.every((w) => hay.includes(w));
  });
}
function mayHaveMoreCommits(detail) {
  const loaded = Array.isArray(detail?.commits) ? detail.commits.length : 0;
  const total = Number(detail?.commitsCount);
  if (Number.isFinite(total) && total > loaded) return true;
  return loaded >= 100;
}
function mayHaveMoreFiles(detail) {
  const loaded = Array.isArray(detail?.files) ? detail.files.length : 0;
  const total = Number(detail?.changedFiles);
  if (Number.isFinite(total) && total > loaded) return true;
  return loaded >= 100;
}
function filterTagsByQuery(tags, query) {
  const list = Array.isArray(tags) ? tags : [];
  const q = String(query || "").trim().toLowerCase();
  if (!q) return list;
  const words = q.split(/\s+/).filter(Boolean);
  return list.filter((t) => {
    const hay = [t?.name, t?.sha, t?.message].filter(Boolean).join(" ").toLowerCase();
    return words.every((w) => hay.includes(w));
  });
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalAsideLists = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
