/**
 * AUTO-GENERATED from src/modal/lib/checks.ts
 * SOURCE OF TRUTH: src/modal/lib/checks.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  buildMergeBoxCheckGroups: () => buildMergeBoxCheckGroups,
  checkRunKey: () => checkRunKey,
  checkRunTime: () => checkRunTime,
  checksNeedElapsedTick: () => checksNeedElapsedTick,
  classifyCheckOutcome: () => classifyCheckOutcome,
  deriveChecksState: () => deriveChecksState,
  distinctCheckRuns: () => distinctCheckRuns,
  distinctStatuses: () => distinctStatuses,
  formatCheckGroupTip: () => formatCheckGroupTip,
  formatCheckSummary: () => formatCheckSummary,
  formatChecksCountLabel: () => formatChecksCountLabel,
  formatDurationMs: () => formatDurationMs,
  formatRelativeAgo: () => formatRelativeAgo,
  listCheckNamesByOutcome: () => listCheckNamesByOutcome,
  mergeBoxChecksHeadline: () => mergeBoxChecksHeadline,
  normalizeChecks: () => normalizeChecks,
  parseTime: () => parseTime,
  statusIsInProgress: () => statusIsInProgress,
  statusKey: () => statusKey,
  statusTime: () => statusTime,
  summarizeCheckCounts: () => summarizeCheckCounts
});
module.exports = __toCommonJS(stdin_exports);
function parseTime(value) {
  if (value == null || value === "") return 0;
  if (typeof value === "number" && Number.isFinite(value)) return value;
  const n = Date.parse(String(value));
  return Number.isFinite(n) ? n : 0;
}
function statusKey(s) {
  const ctx = String(s?.context || "").trim().toLowerCase();
  if (ctx) return ctx;
  const desc = String(s?.description || "").trim().toLowerCase();
  if (desc) return `desc:${desc}`;
  return "";
}
function statusTime(s) {
  return parseTime(s?.updatedAt ?? s?.updated_at) || parseTime(s?.createdAt ?? s?.created_at) || 0;
}
function distinctStatuses(statuses) {
  const list = Array.isArray(statuses) ? statuses : [];
  const byKey = /* @__PURE__ */ new Map();
  let anon = 0;
  for (const s of list) {
    if (!s || typeof s !== "object") continue;
    let key = statusKey(s);
    if (!key) key = `__anon_status_${anon++}`;
    const prev = byKey.get(key);
    if (!prev || statusTime(s) >= statusTime(prev)) {
      byKey.set(key, s);
    }
  }
  return [...byKey.values()];
}
function checkRunKey(r) {
  const name = String(r?.name || "").trim().toLowerCase();
  const app = String(
    r?.appSlug || r?.app_slug || r?.app?.slug || r?.app?.name || ""
  ).trim().toLowerCase();
  if (!name) return "";
  return app ? `${app}::${name}` : name;
}
function checkRunTime(r) {
  return parseTime(r?.completedAt ?? r?.completed_at) || parseTime(r?.startedAt ?? r?.started_at) || // Prefer higher numeric id as recency proxy when timestamps missing
  (Number.isFinite(Number(r?.id)) ? Number(r.id) : 0);
}
function distinctCheckRuns(runs) {
  const list = Array.isArray(runs) ? runs : [];
  const byKey = /* @__PURE__ */ new Map();
  let anon = 0;
  for (const r of list) {
    if (!r || typeof r !== "object") continue;
    let key = checkRunKey(r);
    if (!key) key = `__anon_run_${anon++}`;
    const prev = byKey.get(key);
    if (!prev) {
      byKey.set(key, r);
      continue;
    }
    const tNew = checkRunTime(r);
    const tOld = checkRunTime(prev);
    if (tNew > tOld || tNew === tOld && Number(r.id || 0) > Number(prev.id || 0)) {
      byKey.set(key, r);
    }
  }
  return [...byKey.values()];
}
function deriveChecksState(statuses, checkRuns, fallback = "unknown") {
  const st = Array.isArray(statuses) ? statuses : [];
  const runs = Array.isArray(checkRuns) ? checkRuns : [];
  if (!st.length && !runs.length) return "unknown";
  const statusStates = st.map((s) => String(s?.state || "").toLowerCase());
  const conclusions = runs.map((r) => String(r?.conclusion || "").toLowerCase());
  const runStatuses = runs.map((r) => String(r?.status || "").toLowerCase());
  const anyFailure = statusStates.some((s) => s === "failure" || s === "error") || conclusions.some(
    (c) => c === "failure" || c === "timed_out" || c === "startup_failure" || c === "cancelled"
  );
  if (anyFailure) return "failure";
  const anyPending = statusStates.some((s) => s === "pending") || runStatuses.some(
    (s) => s === "queued" || s === "in_progress" || s === "waiting"
  ) || conclusions.some((c) => c === "" || c === "null" || c === "action_required");
  if (anyPending) return "pending";
  const anySuccess = statusStates.some((s) => s === "success") || conclusions.some(
    (c) => c === "success" || c === "neutral" || c === "skipped"
  );
  if (anySuccess) return "success";
  return fallback || "unknown";
}
function normalizeChecks(checks) {
  const raw = checks && typeof checks === "object" ? checks : {};
  const statuses = distinctStatuses(raw.statuses);
  const checkRuns = distinctCheckRuns(raw.checkRuns || raw.check_runs);
  const fallback = statuses.length || checkRuns.length ? String(raw.state || "unknown") : "unknown";
  const state = deriveChecksState(statuses, checkRuns, fallback);
  return {
    state,
    totalCount: statuses.length + checkRuns.length,
    statuses,
    checkRuns
  };
}
function statusIsInProgress(item) {
  const status = String(item?.status || "").toLowerCase();
  return status === "in_progress" || status === "queued" || status === "waiting";
}
function classifyCheckOutcome(item) {
  if (!item || typeof item !== "object") return "pending";
  if (item.kind === "status" || item.state != null && item.status == null && item.conclusion == null) {
    const st = String(item.state || "").toLowerCase();
    if (st === "failure" || st === "error") return "failure";
    if (st === "success") return "success";
    return "pending";
  }
  const conclusion = String(item.conclusion || "").toLowerCase();
  if (conclusion === "failure" || conclusion === "timed_out" || conclusion === "startup_failure" || conclusion === "cancelled") {
    return "failure";
  }
  if (conclusion === "skipped") return "skipped";
  if (conclusion === "success" || conclusion === "neutral") return "success";
  if (statusIsInProgress(item)) return "in_progress";
  return "pending";
}
function formatDurationMs(ms) {
  const n = Number(ms);
  if (!Number.isFinite(n) || n < 0) return "";
  if (n < 1e3) return "<1s";
  const sec = Math.round(n / 1e3);
  if (sec < 60) return `${sec}s`;
  const min = Math.floor(sec / 60);
  const remSec = sec % 60;
  if (min < 60) return remSec ? `${min}m ${remSec}s` : `${min}m`;
  const hr = Math.floor(min / 60);
  const remMin = min % 60;
  return remMin ? `${hr}h ${remMin}m` : `${hr}h`;
}
function formatRelativeAgo(iso, nowMs) {
  const t = parseTime(iso);
  if (!t) return "";
  const now = Number.isFinite(nowMs) ? nowMs : Date.now();
  let sec = Math.max(0, Math.round((now - t) / 1e3));
  if (sec < 60) return "just now";
  const min = Math.floor(sec / 60);
  if (min < 60) return `${min} minute${min === 1 ? "" : "s"} ago`;
  const hr = Math.floor(min / 60);
  if (hr < 48) return `${hr} hour${hr === 1 ? "" : "s"} ago`;
  const day = Math.floor(hr / 24);
  return `${day} day${day === 1 ? "" : "s"} ago`;
}
function formatCheckSummary(item, nowMs) {
  if (!item) return "";
  const desc = String(item.description || "").trim();
  const start = parseTime(item.startedAt);
  const outcome = item.outcome || classifyCheckOutcome(item);
  const live = outcome === "in_progress" || statusIsInProgress(item);
  const now = Number.isFinite(nowMs) ? nowMs : Date.now();
  let duration = "";
  if (live && start) {
    duration = formatDurationMs(Math.max(0, now - start));
  } else {
    const end = parseTime(item.completedAt) || parseTime(item.updatedAt);
    if (start && end && end >= start) {
      duration = formatDurationMs(end - start);
    } else if (start && !end) {
      duration = formatDurationMs(Math.max(0, now - start));
    }
  }
  if (outcome === "failure") {
    if (duration) return `Failing after ${duration}`;
    return desc || "Failing";
  }
  if (outcome === "success") {
    if (duration) return `Successful in ${duration}`;
    return desc || "Successful";
  }
  if (outcome === "skipped") {
    const when = formatRelativeAgo(item.completedAt || item.updatedAt, nowMs);
    if (when) return `Skipped ${when}`;
    return desc || "Skipped";
  }
  if (live) {
    return duration ? `In progress \u2014 ${duration}` : desc || "In progress";
  }
  return desc || "Expected \u2014 Waiting for status to be reported";
}
function checksNeedElapsedTick(checks) {
  const n = normalizeChecks(checks);
  for (const r of n.checkRuns || []) {
    if (classifyCheckOutcome(r) !== "in_progress") continue;
    if (parseTime(r.startedAt || r.started_at)) return true;
  }
  for (const s of n.statuses || []) {
    const o = classifyCheckOutcome({ kind: "status", state: s.state });
    if (o !== "in_progress") continue;
    if (parseTime(s.createdAt || s.created_at || s.startedAt || s.started_at)) {
      return true;
    }
  }
  return false;
}
function buildMergeBoxCheckGroups(checks, opts) {
  const nowMs = opts && Number.isFinite(opts.nowMs) ? opts.nowMs : Date.now();
  const n = normalizeChecks(checks);
  const rows = [];
  for (const s of n.statuses || []) {
    const outcome = classifyCheckOutcome({ kind: "status", state: s.state });
    const row = {
      id: `status:${s.context || rows.length}`,
      kind: "status",
      name: s.context || s.description || "status",
      outcome,
      description: s.description || "",
      url: s.targetUrl || s.target_url || "",
      startedAt: s.createdAt || s.created_at || "",
      completedAt: s.updatedAt || s.updated_at || "",
      updatedAt: s.updatedAt || s.updated_at || "",
      required: Boolean(s.required)
    };
    row.summary = formatCheckSummary(row, nowMs);
    rows.push(row);
  }
  for (const r of n.checkRuns || []) {
    const outcome = classifyCheckOutcome(r);
    const app = String(r.appName || r.app?.name || "").trim();
    const name = String(r.name || "check").trim() || "check";
    const displayName = app && !name.toLowerCase().startsWith(app.toLowerCase()) ? `${app} / ${name}` : name;
    const row = {
      id: `run:${r.id || name}`,
      kind: "run",
      name: displayName,
      outcome,
      status: r.status || "",
      conclusion: r.conclusion || "",
      description: "",
      url: r.htmlUrl || r.html_url || r.detailsUrl || r.details_url || "",
      startedAt: r.startedAt || r.started_at || "",
      completedAt: r.completedAt || r.completed_at || "",
      updatedAt: r.completedAt || r.completed_at || r.startedAt || "",
      required: Boolean(r.required)
    };
    row.summary = formatCheckSummary(row, nowMs);
    rows.push(row);
  }
  const buckets = {
    failure: [],
    in_progress: [],
    pending: [],
    skipped: [],
    success: []
  };
  for (const row of rows) {
    const b = buckets[row.outcome] || buckets.pending;
    b.push(row);
  }
  const groups = [];
  const pushGroup = (key, outcome, singular, plural, items) => {
    if (!items.length) return;
    const label = items.length === 1 ? `1 ${singular}` : `${items.length} ${plural}`;
    groups.push({ key, label, outcome, items });
  };
  pushGroup("failure", "failure", "failing check", "failing checks", buckets.failure);
  pushGroup(
    "in_progress",
    "in_progress",
    "in progress check",
    "in progress checks",
    buckets.in_progress
  );
  pushGroup("pending", "pending", "expected check", "expected checks", buckets.pending);
  pushGroup("skipped", "skipped", "skipped check", "skipped checks", buckets.skipped);
  pushGroup(
    "success",
    "success",
    "successful check",
    "successful checks",
    buckets.success
  );
  return {
    state: n.state,
    totalCount: rows.length,
    groups
  };
}
function mergeBoxChecksHeadline(state, totalCount) {
  const st = String(state || "").toLowerCase();
  if (!totalCount) return null;
  if (st === "failure" || st === "error") return "Some checks were not successful";
  if (st === "pending") return "Some checks haven\u2019t completed yet";
  if (st === "success") return "All checks have passed";
  return "Checks";
}
function summarizeCheckCounts(checks) {
  const n = normalizeChecks(checks);
  let success = 0;
  let failure = 0;
  let pending = 0;
  let inProgress = 0;
  let skipped = 0;
  for (const s of n.statuses || []) {
    const o = classifyCheckOutcome({ kind: "status", state: s?.state });
    if (o === "failure") failure += 1;
    else if (o === "success") success += 1;
    else if (o === "skipped") skipped += 1;
    else if (o === "in_progress") inProgress += 1;
    else pending += 1;
  }
  for (const r of n.checkRuns || []) {
    const o = classifyCheckOutcome(r);
    if (o === "failure") failure += 1;
    else if (o === "success") success += 1;
    else if (o === "skipped") skipped += 1;
    else if (o === "in_progress") inProgress += 1;
    else pending += 1;
  }
  const total = success + failure + pending + inProgress + skipped;
  return {
    total,
    success,
    failure,
    pending,
    inProgress,
    skipped,
    state: n.state || "unknown"
  };
}
function formatChecksCountLabel(summary) {
  const s = summary && typeof summary === "object" ? summary : {};
  const total = Number(s.total) || 0;
  const success = Number(s.success) || 0;
  const failure = Number(s.failure) || 0;
  const pending = Number(s.pending) || 0;
  const inProgress = Number(s.inProgress) || 0;
  const skipped = Number(s.skipped) || 0;
  if (!total) {
    return "No checks";
  }
  const parts = [
    `${total} check${total === 1 ? "" : "s"}`,
    `${success} succeeded`,
    `${failure} failed`
  ];
  if (inProgress > 0) parts.push(`${inProgress} in progress`);
  if (pending > 0) parts.push(`${pending} expected`);
  if (skipped > 0) parts.push(`${skipped} skipped`);
  return parts.join(" \xB7 ");
}
function listCheckNamesByOutcome(checks) {
  const n = normalizeChecks(checks);
  const groups = {
    failure: [],
    pending: [],
    in_progress: [],
    success: [],
    skipped: []
  };
  for (const s of n.statuses || []) {
    const o = classifyCheckOutcome({ kind: "status", state: s?.state });
    const name = String(s?.context || s?.description || "status").trim() || "status";
    const bucket = groups[o] || groups.pending;
    bucket.push(name);
  }
  for (const r of n.checkRuns || []) {
    const o = classifyCheckOutcome(r);
    const app = String(r?.appName || r?.app?.name || "").trim();
    const job = String(r?.name || "check").trim() || "check";
    const name = app && !job.toLowerCase().startsWith(app.toLowerCase()) ? `${app} / ${job}` : job;
    const bucket = groups[o] || groups.pending;
    bucket.push(name);
  }
  return {
    failure: groups.failure,
    pending: groups.pending,
    in_progress: groups.in_progress,
    success: groups.success,
    skipped: groups.skipped,
    state: n.state || "unknown"
  };
}
function formatCheckGroupTip(outcome, names, locale) {
  const list = Array.isArray(names) ? names.filter(Boolean) : [];
  const n = list.length;
  const pure = typeof globalThis !== "undefined" ? globalThis.PRModalI18n : null;
  const t = (key, subs) => {
    if (pure && typeof pure.formatMessage === "function" && locale) {
      const m = pure.formatMessage(key, locale, subs);
      if (m && m !== key) return m;
    }
    return "";
  };
  const headings = {
    failure: n === 1 ? t("check_tip_failed_one") || "1 failed" : t("check_tip_failed_n", { count: n }) || `${n} failed`,
    in_progress: n === 1 ? t("check_tip_in_progress_one") || "1 in progress" : t("check_tip_in_progress_n", { count: n }) || `${n} in progress`,
    pending: n === 1 ? t("check_tip_expected_one") || "1 expected" : t("check_tip_expected_n", { count: n }) || `${n} expected`,
    success: n === 1 ? t("check_tip_succeeded_one") || "1 succeeded" : t("check_tip_succeeded_n", { count: n }) || `${n} succeeded`,
    skipped: n === 1 ? t("check_tip_skipped_one") || "1 skipped" : t("check_tip_skipped_n", { count: n }) || `${n} skipped`
  };
  const head = headings[outcome] || t("check_tip_checks_n", { count: n }) || `${n} checks`;
  if (!n) return head;
  const max = 12;
  const shown = list.slice(0, max);
  const more = n - shown.length;
  const body = shown.map((name) => `\xB7 ${name}`).join("\n");
  const moreLine = t("check_tip_more", { count: more }) || `\xB7 +${more} more`;
  return more > 0 ? `${head}
${body}
${moreLine}` : `${head}
${body}`;
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalChecks = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);

if (typeof module !== 'undefined' && module.exports && typeof globalThis !== 'undefined' && globalThis.PRModalChecks) {
  module.exports = globalThis.PRModalChecks;
}
