/**
 * AUTO-GENERATED from src/modal/lib/collapse.ts
 * SOURCE OF TRUTH: src/modal/lib/collapse.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  COLLAPSED_SET_EXPLICIT_EMPTY: () => COLLAPSED_SET_EXPLICIT_EMPTY,
  DEFAULT_LARGE_CHANGES: () => DEFAULT_LARGE_CHANGES,
  DEFAULT_LARGE_PATCH_CHARS: () => DEFAULT_LARGE_PATCH_CHARS,
  annotateFilesForCollapse: () => annotateFilesForCollapse,
  attributesForPath: () => attributesForPath,
  classifyDiffFile: () => classifyDiffFile,
  defaultCollapsedPathSet: () => defaultCollapsedPathSet,
  expandPathInCollapsedSet: () => expandPathInCollapsedSet,
  isAttrEnabled: () => isAttrEnabled,
  isImagePath: () => isImagePath,
  isPathCollapsed: () => isPathCollapsed,
  matchAttrPattern: () => matchAttrPattern,
  materializeCollapsedPaths: () => materializeCollapsedPaths,
  parseGitattributes: () => parseGitattributes,
  shouldCollapseFile: () => shouldCollapseFile
});
module.exports = __toCommonJS(stdin_exports);
const DEFAULT_LARGE_CHANGES = 5e3;
const DEFAULT_LARGE_PATCH_CHARS = 8e4;
const IMAGE_EXT_RE = /\.(png|jpe?g|gif|webp|bmp|svg|ico|avif|jfif|pjpeg|pjp|tif{1,2})$/i;
function isImagePath(path) {
  const p = String(path || "").split("?")[0].split("#")[0];
  return IMAGE_EXT_RE.test(p);
}
function classifyDiffFile(file) {
  if (!file) {
    return { kind: "binary", openableAsText: false, renderImage: false };
  }
  const path = file.filename || file.path || "";
  const patch = typeof file.patch === "string" ? file.patch : "";
  const hasPatch = patch.length > 0;
  const media = String(file.mediaType || file.contentType || "").toLowerCase();
  const image = isImagePath(path) || media.startsWith("image/") && media !== "image/svg+xml-not";
  if (image) {
    return { kind: "image", openableAsText: false, renderImage: true };
  }
  if (hasPatch) {
    return { kind: "text", openableAsText: true, renderImage: false };
  }
  return { kind: "binary", openableAsText: false, renderImage: false };
}
function parseGitattributes(text) {
  const rules = [];
  if (!text || typeof text !== "string") return rules;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.replace(/#.*$/, "").trim();
    if (!line) continue;
    const parts = line.split(/\s+/);
    if (parts.length < 2) continue;
    const pattern = parts[0];
    const attrs = {};
    for (let i = 1; i < parts.length; i++) {
      const p = parts[i];
      if (p.startsWith("-")) {
        attrs[p.slice(1)] = false;
      } else if (p.includes("=")) {
        const [k, v] = p.split("=");
        attrs[k] = v;
      } else {
        attrs[p] = true;
      }
    }
    rules.push({ pattern, attrs });
  }
  return rules;
}
function matchAttrPattern(filePath, pattern) {
  if (!filePath || !pattern) return false;
  const path = filePath.replace(/^\/+/, "");
  if (pattern === path) return true;
  if (pattern.startsWith("**/")) {
    const rest = pattern.slice(3);
    return path === rest || path.endsWith(`/${rest}`) || path.endsWith(rest);
  }
  if (pattern.startsWith("*.")) {
    return path.endsWith(pattern.slice(1));
  }
  if (pattern.includes("*")) {
    const re = new RegExp(
      "^" + pattern.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*\*/g, "\xA7\xA7").replace(/\*/g, "[^/]*").replace(/§§/g, ".*") + "$"
    );
    return re.test(path);
  }
  return path === pattern || path.endsWith(`/${pattern}`);
}
function attributesForPath(filePath, rules) {
  const out = {};
  if (!Array.isArray(rules)) return out;
  for (const rule of rules) {
    if (matchAttrPattern(filePath, rule.pattern)) {
      Object.assign(out, rule.attrs);
    }
  }
  return out;
}
function isAttrEnabled(value) {
  if (value === true) return true;
  if (value === false || value == null) return false;
  if (typeof value === "string") {
    const v = value.trim().toLowerCase();
    if (v === "" || v === "false" || v === "0" || v === "no" || v === "unset") {
      return false;
    }
    return true;
  }
  return Boolean(value);
}
function shouldCollapseFile(file, opts = {}) {
  if (!file) return true;
  const path = file.filename || file.path || "";
  const patch = file.patch || "";
  const changes = file.changes ?? Number(file.additions || 0) + Number(file.deletions || 0);
  const largeChanges = opts.largeChanges ?? DEFAULT_LARGE_CHANGES;
  const largePatchChars = opts.largePatchChars ?? DEFAULT_LARGE_PATCH_CHARS;
  const rules = opts.rules || [];
  const classified = classifyDiffFile(file);
  const attrs = attributesForPath(path, rules);
  if (isAttrEnabled(file.linguistGenerated) || isAttrEnabled(attrs["linguist-generated"])) {
    return true;
  }
  if (isAttrEnabled(file.binary) || isAttrEnabled(attrs.binary)) {
    return true;
  }
  if (attrs.diff === false || String(attrs.diff || "").toLowerCase() === "false") {
    return true;
  }
  if (classified.kind === "binary") return true;
  if (changes >= largeChanges) return true;
  if (patch && patch.length >= largePatchChars) return true;
  if (classified.kind === "image") return false;
  if (!patch) return true;
  const lower = path.toLowerCase();
  if (lower.endsWith("package-lock.json") || lower.endsWith("yarn.lock") || lower.endsWith("pnpm-lock.yaml") || lower.endsWith(".min.js") || lower.endsWith(".min.css") || lower.endsWith(".map") || lower.includes("/dist/") || lower.endsWith(".bundle.js")) {
    return true;
  }
  return false;
}
function annotateFilesForCollapse(files, gitattributesText) {
  const rules = parseGitattributes(gitattributesText || "");
  return (Array.isArray(files) ? files : []).map((f) => {
    const path = f.filename || f.path || "";
    const attrs = attributesForPath(path, rules);
    const enriched = {
      ...f,
      linguistGenerated: isAttrEnabled(f.linguistGenerated) || isAttrEnabled(attrs["linguist-generated"]),
      binary: isAttrEnabled(f.binary) || isAttrEnabled(attrs.binary)
    };
    const classified = classifyDiffFile(enriched);
    const collapsed = shouldCollapseFile(enriched, { rules });
    return {
      ...f,
      attrs,
      fileKind: classified.kind,
      openableAsText: classified.openableAsText,
      renderImage: classified.renderImage,
      defaultCollapsed: collapsed
    };
  });
}
function toPathSet(paths) {
  if (!paths) return /* @__PURE__ */ new Set();
  if (paths instanceof Set) return paths;
  return new Set(Array.isArray(paths) ? paths : []);
}
function isPathCollapsed(path, collapsedPaths, defaultCollapsed = false, expandAll = false, viewedPaths = null) {
  if (expandAll || !path) return false;
  const set = toPathSet(collapsedPaths);
  if (set.has(path)) return true;
  if (set.size === 0) {
    if (defaultCollapsed === true) return true;
    if (toPathSet(viewedPaths).has(path)) return true;
  }
  return false;
}
function defaultCollapsedPathSet(files, viewedPaths = null) {
  const out = /* @__PURE__ */ new Set();
  for (const f of Array.isArray(files) ? files : []) {
    if (!f?.defaultCollapsed) continue;
    const p = f.filename || f.path;
    if (p) out.add(p);
  }
  for (const p of toPathSet(viewedPaths)) {
    if (p) out.add(p);
  }
  return out;
}
function materializeCollapsedPaths(collapsedPaths, files, viewedPaths = null) {
  if (collapsedPaths instanceof Set && collapsedPaths.size > 0) {
    return new Set(collapsedPaths);
  }
  if (Array.isArray(collapsedPaths) && collapsedPaths.length > 0) {
    return new Set(collapsedPaths);
  }
  return defaultCollapsedPathSet(files, viewedPaths);
}
const COLLAPSED_SET_EXPLICIT_EMPTY = "\0prp-collapsed-explicit";
function expandPathInCollapsedSet(collapsedPaths, path, files, viewedPaths = null) {
  const p = String(path || "").trim();
  const n = materializeCollapsedPaths(collapsedPaths, files, viewedPaths);
  if (p) n.delete(p);
  n.delete(COLLAPSED_SET_EXPLICIT_EMPTY);
  if (n.size === 0) {
    n.add(COLLAPSED_SET_EXPLICIT_EMPTY);
  }
  return n;
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalCollapse = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
