/**
 * AUTO-GENERATED from src/modal/lib/comments-page.ts
 * SOURCE OF TRUTH: src/modal/lib/comments-page.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  DEFAULT_COMMENT_PAGE_SIZE: () => DEFAULT_COMMENT_PAGE_SIZE,
  advanceCommentsMeta: () => advanceCommentsMeta,
  buildCommentsListUrl: () => buildCommentsListUrl,
  buildCommentsPageMeta: () => buildCommentsPageMeta,
  clampPerPage: () => clampPerPage,
  linkHasMore: () => linkHasMore,
  mergeCommentsById: () => mergeCommentsById,
  parseLinkLastPage: () => parseLinkLastPage,
  parseLinkNextPage: () => parseLinkNextPage,
  sinceCursorFromMeta: () => sinceCursorFromMeta
});
module.exports = __toCommonJS(stdin_exports);
const DEFAULT_COMMENT_PAGE_SIZE = 50;
function parseLinkRelPage(linkHeader, rel) {
  const raw = String(linkHeader || "");
  if (!raw) return null;
  const re = new RegExp(`rel="?${rel}"?`, "i");
  const parts = raw.split(",");
  for (const part of parts) {
    if (!re.test(part)) continue;
    const m = part.match(/[?&]page=(\d+)/i);
    if (m) {
      const n = Number(m[1]);
      return Number.isFinite(n) && n > 0 ? n : null;
    }
  }
  return null;
}
function parseLinkNextPage(linkHeader) {
  return parseLinkRelPage(linkHeader, "next");
}
function parseLinkLastPage(linkHeader) {
  return parseLinkRelPage(linkHeader, "last");
}
function linkHasMore(linkHeader) {
  return parseLinkNextPage(linkHeader) != null;
}
function buildCommentsListUrl(kind, owner, repo, number, opts = {}) {
  const o = encodeURIComponent(String(owner || ""));
  const r = encodeURIComponent(String(repo || ""));
  const n = Number(number);
  const perPage = clampPerPage(opts.perPage);
  const page = Math.max(1, Number(opts.page) || 1);
  const base = kind === "review" ? `https://api.github.com/repos/${o}/${r}/pulls/${n}/comments` : `https://api.github.com/repos/${o}/${r}/issues/${n}/comments`;
  const params = new URLSearchParams();
  params.set("per_page", String(perPage));
  params.set("page", String(page));
  if (opts.sort) params.set("sort", String(opts.sort));
  if (opts.direction) params.set("direction", String(opts.direction));
  if (opts.since) params.set("since", String(opts.since));
  return `${base}?${params.toString()}`;
}
function clampPerPage(n, max = 100) {
  const v = Number(n);
  if (!Number.isFinite(v) || v <= 0) return DEFAULT_COMMENT_PAGE_SIZE;
  return Math.min(max, Math.floor(v));
}
function mergeCommentsById(existing, incoming, excludeIds = null) {
  const ban = excludeIds instanceof Set ? excludeIds : excludeIds ? new Set(
    (Array.isArray(excludeIds) ? excludeIds : []).map((x) => String(x))
  ) : null;
  const map = /* @__PURE__ */ new Map();
  for (const c of Array.isArray(existing) ? existing : []) {
    if (!c || c.id == null) continue;
    const key = String(c.id);
    if (ban && ban.has(key)) continue;
    map.set(key, c);
  }
  for (const c of Array.isArray(incoming) ? incoming : []) {
    if (!c || c.id == null) continue;
    const key = String(c.id);
    if (ban && ban.has(key)) continue;
    map.set(key, c);
  }
  return [...map.values()].sort((a, b) => {
    const ta = String(a.createdAt || a.created_at || "");
    const tb = String(b.createdAt || b.created_at || "");
    if (ta !== tb) return ta.localeCompare(tb);
    return Number(a.id) - Number(b.id);
  });
}
function buildCommentsPageMeta(items, opts = {}) {
  const list = Array.isArray(items) ? items : [];
  const page = Math.max(1, Number(opts.page) || 1);
  const perPage = clampPerPage(opts.perPage);
  const order = opts.order === "from-end" ? "from-end" : opts.order || "asc";
  let oldest = null;
  let newest = null;
  let maxId = null;
  for (const c of list) {
    const at = c?.createdAt || c?.created_at || null;
    if (at) {
      if (!oldest || at < oldest) oldest = at;
      if (!newest || at > newest) newest = at;
    }
    if (c?.id != null) {
      const id = Number(c.id);
      if (Number.isFinite(id) && (maxId == null || id > maxId)) maxId = id;
    }
  }
  if (order === "from-end") {
    const hasMore2 = page > 1;
    return {
      page,
      perPage,
      hasMore: hasMore2,
      nextPage: hasMore2 ? page - 1 : null,
      order: "from-end",
      since: opts.since || null,
      oldestCreatedAt: oldest,
      newestCreatedAt: newest,
      maxId,
      loadedCount: list.length
    };
  }
  const nextPage = parseLinkNextPage(opts.linkHeader);
  const hasMore = nextPage != null || // If no Link header (mocks), treat full page as maybe-more
  opts.linkHeader == null && list.length >= perPage;
  return {
    page,
    perPage,
    hasMore: Boolean(hasMore),
    nextPage: nextPage ?? (hasMore ? page + 1 : null),
    order,
    since: opts.since || null,
    oldestCreatedAt: oldest,
    newestCreatedAt: newest,
    maxId,
    loadedCount: list.length
  };
}
function advanceCommentsMeta(prevMeta, pageMeta, totalLoaded) {
  const prev = prevMeta || {};
  const page = pageMeta || {};
  return {
    page: page.page ?? prev.page ?? 1,
    perPage: page.perPage ?? prev.perPage ?? DEFAULT_COMMENT_PAGE_SIZE,
    hasMore: Boolean(page.hasMore),
    nextPage: page.hasMore ? page.nextPage : null,
    order: page.order || prev.order || "asc",
    since: prev.since || null,
    oldestCreatedAt: minIso(prev.oldestCreatedAt, page.oldestCreatedAt),
    newestCreatedAt: maxIso(prev.newestCreatedAt, page.newestCreatedAt),
    maxId: page.maxId != null && (prev.maxId == null || page.maxId > prev.maxId) ? page.maxId : prev.maxId ?? page.maxId ?? null,
    loadedCount: Number.isFinite(totalLoaded) ? totalLoaded : page.loadedCount || 0
  };
}
function minIso(a, b) {
  if (!a) return b || null;
  if (!b) return a;
  return a < b ? a : b;
}
function maxIso(a, b) {
  if (!a) return b || null;
  if (!b) return a;
  return a > b ? a : b;
}
function sinceCursorFromMeta(meta) {
  if (meta?.newestCreatedAt) return meta.newestCreatedAt;
  return null;
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalCommentsPage = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
