/**
 * AUTO-GENERATED from src/modal/lib/conversation-virtual.ts
 * SOURCE OF TRUTH: src/modal/lib/conversation-virtual.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  CONV_EST_COLLAPSED_THREAD: () => CONV_EST_COLLAPSED_THREAD,
  CONV_EST_COMMENT: () => CONV_EST_COMMENT,
  CONV_EST_COMPOSER: () => CONV_EST_COMPOSER,
  CONV_EST_DESCRIPTION: () => CONV_EST_DESCRIPTION,
  CONV_EST_EMPTY: () => CONV_EST_EMPTY,
  CONV_EST_GAP: () => CONV_EST_GAP,
  CONV_EST_MAX: () => CONV_EST_MAX,
  CONV_EST_MERGE: () => CONV_EST_MERGE,
  CONV_EST_MIN: () => CONV_EST_MIN,
  CONV_EST_PAGINATION: () => CONV_EST_PAGINATION,
  CONV_EST_REPLY: () => CONV_EST_REPLY,
  CONV_EST_SNIPPET: () => CONV_EST_SNIPPET,
  CONV_EST_THREAD_BASE: () => CONV_EST_THREAD_BASE,
  CONV_ROW_GAP: () => CONV_ROW_GAP,
  buildConversationVirtualRows: () => buildConversationVirtualRows,
  conversationRowHeight: () => conversationRowHeight,
  conversationRowOffsets: () => conversationRowOffsets,
  estimateConversationRowHeight: () => estimateConversationRowHeight,
  indexForConversationAnchor: () => indexForConversationAnchor
});
module.exports = __toCommonJS(stdin_exports);
const CONV_EST_GAP = 72;
const CONV_EST_COLLAPSED_THREAD = 64;
const CONV_EST_THREAD_BASE = 180;
const CONV_EST_REPLY = 64;
const CONV_EST_SNIPPET = 110;
const CONV_EST_COMMENT = 120;
const CONV_EST_DESCRIPTION = 220;
const CONV_EST_COMPOSER = 168;
const CONV_EST_MERGE = 132;
const CONV_EST_PAGINATION = 48;
const CONV_EST_EMPTY = 40;
const CONV_EST_MIN = 40;
const CONV_EST_MAX = 2400;
const CONV_ROW_GAP = 14;
function buildConversationVirtualRows(paged, opts = {}) {
  const reverse = Boolean(opts.reverseComments);
  const top = Array.isArray(paged?.items) ? paged.items : [];
  const bottom = Array.isArray(paged?.bottomItems) ? paged.bottomItems : [];
  const hidden = Number(paged?.hiddenCount ?? opts.metaHiddenCount) || 0;
  const showGap = Boolean(
    paged?.showThreadGap || opts.hasMoreThreads && hidden > 0 && opts.canLoadMore !== false
  );
  const hasTimeline = top.length > 0 || bottom.length > 0 || showGap;
  const rows = [];
  rows.push({ type: "description", key: "description" });
  if (reverse) {
    rows.push({ type: "composer", key: "composer" });
    rows.push({ type: "merge", key: "merge" });
  }
  if (!hasTimeline) {
    rows.push({ type: "empty", key: "empty" });
  } else {
    for (const item of top) {
      const id = item?.id ?? item?.key;
      rows.push({
        type: "item",
        key: `item:${String(id)}`,
        item
      });
    }
    if (showGap) {
      rows.push({
        type: "gap",
        key: "timeline-gap",
        hiddenCount: hidden
      });
    }
    for (const item of bottom) {
      const id = item?.id ?? item?.key;
      rows.push({
        type: "item",
        key: `old:${String(id)}`,
        item,
        keyPrefix: "old-"
      });
    }
  }
  if (!reverse) {
    rows.push({ type: "merge", key: "merge" });
    rows.push({ type: "composer", key: "composer" });
  }
  return rows;
}
function estimateConversationRowHeight(row, opts = {}) {
  if (!row) return CONV_EST_COMMENT + CONV_ROW_GAP;
  if (row.type === "description") {
    const body = String(opts.descriptionBody ?? "");
    const h2 = CONV_EST_DESCRIPTION + Math.min(800, Math.floor(body.length / 2.5));
    return clampEst(h2) + CONV_ROW_GAP;
  }
  if (row.type === "composer") return CONV_EST_COMPOSER + CONV_ROW_GAP;
  if (row.type === "merge") return CONV_EST_MERGE + CONV_ROW_GAP;
  if (row.type === "pagination") return CONV_EST_PAGINATION + CONV_ROW_GAP;
  if (row.type === "empty") return CONV_EST_EMPTY + CONV_ROW_GAP;
  if (row.type === "gap") return CONV_EST_GAP + CONV_ROW_GAP;
  const item = row.item;
  if (!item) return CONV_EST_COMMENT + CONV_ROW_GAP;
  const kind = item.kind || "";
  if (kind === "review-group") {
    const threads = Array.isArray(item.threads) ? item.threads : [];
    let h2 = 56 + threads.length * 34;
    const bodyLen2 = String(item.body || "").length;
    if (bodyLen2) h2 += Math.min(160, 40 + Math.floor(bodyLen2 / 4));
    const expandFn = opts.isGroupThreadExpanded;
    for (const t of threads) {
      const open = typeof expandFn === "function" ? Boolean(expandFn(item, t)) : t?.pending ? false : !t?.resolved;
      if (!open) continue;
      const replies = Array.isArray(t.replies) ? t.replies.length : 0;
      h2 += CONV_EST_THREAD_BASE + replies * CONV_EST_REPLY;
      if (t.snippet) h2 += CONV_EST_SNIPPET;
    }
    return clampEst(h2) + CONV_ROW_GAP;
  }
  if (kind === "review-thread" || kind === "review-comment") {
    const collapsed = typeof opts.isThreadCollapsed === "function" ? Boolean(opts.isThreadCollapsed(item)) : Boolean(item.resolved);
    if (collapsed) return CONV_EST_COLLAPSED_THREAD + CONV_ROW_GAP;
    const replies = Array.isArray(item.replies) ? item.replies.length : 0;
    let h2 = CONV_EST_THREAD_BASE + replies * CONV_EST_REPLY;
    if (item.snippet) h2 += CONV_EST_SNIPPET;
    const bodyLen2 = String(item.body || "").length;
    h2 += Math.min(180, Math.floor(bodyLen2 / 4));
    h2 += 96;
    return clampEst(h2) + CONV_ROW_GAP;
  }
  const bodyLen = String(item.body || "").length;
  let h = CONV_EST_COMMENT + Math.min(200, Math.floor(bodyLen / 3));
  if (kind === "review" && item.state) h += 12;
  return clampEst(h) + CONV_ROW_GAP;
}
function clampEst(h) {
  return Math.max(CONV_EST_MIN, Math.min(CONV_EST_MAX, Math.round(h)));
}
function conversationRowHeight(row, measured, opts = {}) {
  const key = row?.key;
  if (key != null && measured) {
    if (measured instanceof Map) {
      if (measured.has(key)) return Math.max(1, Number(measured.get(key)) || 1);
    } else if (Object.prototype.hasOwnProperty.call(measured, key)) {
      return Math.max(1, Number(measured[key]) || 1);
    }
  }
  return estimateConversationRowHeight(row, opts);
}
function conversationRowOffsets(rows, measured, opts = {}) {
  const list = Array.isArray(rows) ? rows : [];
  const offsets = new Array(list.length + 1);
  offsets[0] = 0;
  for (let i = 0; i < list.length; i++) {
    offsets[i + 1] = offsets[i] + conversationRowHeight(list[i], measured, opts);
  }
  return offsets;
}
function indexForConversationAnchor(rows, anchorId) {
  const a = String(anchorId || "");
  if (!a) return -1;
  const list = Array.isArray(rows) ? rows : [];
  for (let i = 0; i < list.length; i++) {
    const row = list[i];
    if (row.type === "description" && (a === "body" || a === "description")) {
      return i;
    }
    if (row.type !== "item") continue;
    const item = row.item;
    if (!item) continue;
    if (item.kind === "issue-comment" && `issue-comment:${item.id}` === a) {
      return i;
    }
    if (item.kind === "review" && `review:${item.id}` === a) return i;
    if (item.kind === "review-group") {
      if (`review:${item.id}` === a || `review-group:${item.id}` === a) return i;
      for (const t of item.threads || []) {
        if (`review-comment:${t?.id}` === a) return i;
        const replies = t?.replies || [];
        if (replies.some((r) => `review-comment:${r?.id}` === a)) return i;
      }
    }
    if (item.kind === "review-thread" || item.kind === "review-comment") {
      if (`review-comment:${item.id}` === a) return i;
      const replies = item.replies || [];
      if (replies.some((r) => `review-comment:${r?.id}` === a)) {
        return i;
      }
    }
  }
  return -1;
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalConversationVirtual = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
