/**
 * AUTO-GENERATED from src/modal/lib/detail-store.ts
 * SOURCE OF TRUTH: src/modal/lib/detail-store.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  META_KEYS: () => META_KEYS,
  applyChecks: () => applyChecks,
  applyComments: () => applyComments,
  applyCommits: () => applyCommits,
  applyCorePayload: () => applyCorePayload,
  applyDevelopment: () => applyDevelopment,
  applyFiles: () => applyFiles,
  applyMeta: () => applyMeta,
  applyPendingReview: () => applyPendingReview,
  applyReviews: () => applyReviews,
  applyThreadsFromMergedDetail: () => applyThreadsFromMergedDetail,
  cloneStore: () => cloneStore,
  createEmptyStore: () => createEmptyStore,
  fromAppDetail: () => fromAppDetail,
  pickMeta: () => pickMeta,
  sidePendingFlags: () => sidePendingFlags,
  sideSettledFlags: () => sideSettledFlags,
  toAppDetail: () => toAppDetail
});
module.exports = __toCommonJS(stdin_exports);
const META_KEYS = [
  "owner",
  "repo",
  "number",
  "nodeId",
  "title",
  "body",
  "state",
  "draft",
  "author",
  "authorAvatarUrl",
  "viewerLogin",
  "baseRef",
  "headRef",
  "baseSha",
  "headSha",
  "baseOwner",
  "baseRepo",
  "headOwner",
  "headRepo",
  "magicLinks",
  "htmlUrl",
  "merged",
  "mergeable",
  "mergeableState",
  "conflictFiles",
  "rebaseable",
  "createdAt",
  "updatedAt",
  "additions",
  "deletions",
  "changedFiles",
  "commitsCount",
  "labels",
  "assignees",
  "requestedReviewers",
  "requestedTeams",
  "milestone",
  "avatarUrls",
  "actorIsBot",
  "subscribed",
  "locked",
  "gitattributesText"
];
function emptyListSlice(items) {
  return {
    items: Array.isArray(items) ? items.slice() : [],
    settled: false
  };
}
function createEmptyStore() {
  return {
    meta: {},
    files: emptyListSlice(),
    commits: emptyListSlice(),
    comments: { items: [], pageMeta: null, settled: false },
    reviews: emptyListSlice(),
    checks: {
      data: {
        state: "unknown",
        totalCount: 0,
        statuses: [],
        checkRuns: []
      },
      settled: false
    },
    development: {
      linkedIssues: [],
      developmentIssues: [],
      projects: [],
      settled: false
    },
    threads: {
      reviewThreads: [],
      reviewComments: [],
      reviewThreadsMeta: null,
      reviewCommentsMeta: null,
      settled: false
    },
    pendingReview: null,
    flags: {
      sketch: false,
      source: null,
      cacheFull: false
    }
  };
}
function cloneStore(store) {
  return store ? JSON.parse(JSON.stringify(store)) : createEmptyStore();
}
function pickMeta(flat) {
  if (!flat || typeof flat !== "object") return {};
  const out = {};
  for (const k of META_KEYS) {
    if (Object.prototype.hasOwnProperty.call(flat, k)) {
      out[k] = flat[k];
    }
  }
  return out;
}
function mergeAvatarMaps(a, b) {
  return {
    ...a && typeof a === "object" ? a : {},
    ...b && typeof b === "object" ? b : {}
  };
}
function fromAppDetail(flat) {
  const store = createEmptyStore();
  if (!flat || typeof flat !== "object") return store;
  store.meta = pickMeta(flat);
  store.flags.sketch = Boolean(flat._sketch);
  store.flags.source = flat._source || (flat._sketch ? "list" : null);
  store.flags.cacheFull = flat._cacheFull === true;
  const settled = flat._sideSettled && typeof flat._sideSettled === "object" ? flat._sideSettled : {};
  store.files = {
    items: Array.isArray(flat.files) ? flat.files.slice() : [],
    settled: Boolean(settled.files) || flat._cacheFull === true || Array.isArray(flat.files) && flat.files.length > 0
  };
  store.commits = {
    items: Array.isArray(flat.commits) ? flat.commits.slice() : [],
    settled: Boolean(settled.commits) || flat._cacheFull === true || Array.isArray(flat.commits) && flat.commits.length > 0
  };
  store.comments = {
    items: Array.isArray(flat.comments) ? flat.comments.slice() : [],
    pageMeta: flat.commentsMeta || null,
    settled: Boolean(settled.comments) || Array.isArray(flat.comments) && flat.comments.length > 0
  };
  store.reviews = {
    items: Array.isArray(flat.reviews) ? flat.reviews.slice() : [],
    settled: Boolean(settled.reviews) || Array.isArray(flat.reviews) && flat.reviews.length > 0
  };
  const checks = flat.checks || store.checks.data;
  const hasChecks = checks && (Array.isArray(checks.statuses) && checks.statuses.length > 0 || Array.isArray(checks.checkRuns) && checks.checkRuns.length > 0 || Array.isArray(checks.check_runs) && checks.check_runs.length > 0);
  store.checks = {
    data: checks || store.checks.data,
    settled: Boolean(settled.checks) || Boolean(hasChecks)
  };
  store.development = {
    linkedIssues: Array.isArray(flat.linkedIssues) ? flat.linkedIssues.slice() : [],
    developmentIssues: Array.isArray(flat.developmentIssues) ? flat.developmentIssues.slice() : [],
    projects: Array.isArray(flat.projects) ? flat.projects.slice() : [],
    settled: Boolean(settled.development) || Array.isArray(flat.developmentIssues) && flat.developmentIssues.length > 0 || Array.isArray(flat.linkedIssues) && flat.linkedIssues.length > 0
  };
  const hasThreads = Array.isArray(flat.reviewThreads) && flat.reviewThreads.length > 0 || Array.isArray(flat.reviewComments) && flat.reviewComments.length > 0;
  store.threads = {
    reviewThreads: Array.isArray(flat.reviewThreads) ? flat.reviewThreads.slice() : [],
    reviewComments: Array.isArray(flat.reviewComments) ? flat.reviewComments.slice() : [],
    reviewThreadsMeta: flat.reviewThreadsMeta || null,
    reviewCommentsMeta: flat.reviewCommentsMeta || null,
    settled: hasThreads
  };
  store.pendingReview = flat.viewerPendingReview || null;
  return store;
}
function toAppDetail(store) {
  if (!store || typeof store !== "object") return null;
  const m = store.meta && typeof store.meta === "object" ? store.meta : {};
  const sideSettled = {
    files: Boolean(store.files?.settled),
    commits: Boolean(store.commits?.settled),
    comments: Boolean(store.comments?.settled),
    reviews: Boolean(store.reviews?.settled),
    checks: Boolean(store.checks?.settled),
    development: Boolean(store.development?.settled)
  };
  return {
    ...m,
    files: Array.isArray(store.files?.items) ? store.files.items : [],
    commits: Array.isArray(store.commits?.items) ? store.commits.items : [],
    comments: Array.isArray(store.comments?.items) ? store.comments.items : [],
    commentsMeta: store.comments?.pageMeta || null,
    reviews: Array.isArray(store.reviews?.items) ? store.reviews.items : [],
    checks: store.checks?.data || {
      state: "unknown",
      totalCount: 0,
      statuses: [],
      checkRuns: []
    },
    linkedIssues: Array.isArray(store.development?.linkedIssues) ? store.development.linkedIssues : [],
    developmentIssues: Array.isArray(store.development?.developmentIssues) ? store.development.developmentIssues : [],
    projects: Array.isArray(store.development?.projects) ? store.development.projects : [],
    reviewThreads: Array.isArray(store.threads?.reviewThreads) ? store.threads.reviewThreads : [],
    reviewComments: Array.isArray(store.threads?.reviewComments) ? store.threads.reviewComments : [],
    reviewThreadsMeta: store.threads?.reviewThreadsMeta || null,
    reviewCommentsMeta: store.threads?.reviewCommentsMeta || null,
    viewerPendingReview: store.pendingReview || null,
    _sideSettled: sideSettled,
    _sketch: store.flags?.sketch ? true : void 0,
    _source: store.flags?.source || void 0,
    _cacheFull: store.flags?.cacheFull ? true : void 0,
    _incompleteIdentity: m.owner == null || m.repo == null || m.number == null ? true : void 0
  };
}
function sidePendingFlags(store) {
  if (!store) {
    return {
      files: false,
      commits: false,
      comments: false,
      reviews: false,
      checks: false,
      development: false
    };
  }
  return {
    files: !store.files?.settled,
    commits: !store.commits?.settled,
    comments: !store.comments?.settled,
    reviews: !store.reviews?.settled,
    checks: !store.checks?.settled,
    development: !store.development?.settled
  };
}
function sideSettledFlags(store) {
  const p = sidePendingFlags(store);
  return {
    files: !p.files,
    commits: !p.commits,
    comments: !p.comments,
    reviews: !p.reviews,
    checks: !p.checks,
    development: !p.development
  };
}
function applyMeta(store, metaPartial, opts = {}) {
  if (!store || !metaPartial || typeof metaPartial !== "object") return store;
  const next = { ...store.meta };
  for (const k of META_KEYS) {
    if (!Object.prototype.hasOwnProperty.call(metaPartial, k)) continue;
    const v = metaPartial[k];
    if (v === void 0) continue;
    if (k === "avatarUrls" && v && typeof v === "object") {
      next.avatarUrls = mergeAvatarMaps(next.avatarUrls, v);
      continue;
    }
    if (k === "actorIsBot" && v && typeof v === "object") {
      next.actorIsBot = { ...next.actorIsBot || {}, ...v };
      continue;
    }
    if (!opts.trustEmpty && (k === "assignees" || k === "requestedReviewers" || k === "requestedTeams" || k === "labels") && Array.isArray(v) && v.length === 0 && Array.isArray(next[k]) && next[k].length > 0) {
      continue;
    }
    next[k] = v;
  }
  store.meta = next;
  if (opts.source) store.flags.source = opts.source;
  if (opts.sketch === false) store.flags.sketch = false;
  if (opts.sketch === true) store.flags.sketch = true;
  if (opts.cacheFull === true) store.flags.cacheFull = true;
  return store;
}
function applyFiles(store, files, opts = {}) {
  if (!store) return store;
  store.files = {
    items: Array.isArray(files) ? files.slice() : [],
    settled: opts.settled !== false
  };
  if (opts.gitattributesText != null) {
    store.meta = {
      ...store.meta,
      gitattributesText: opts.gitattributesText
    };
  }
  return store;
}
function applyCommits(store, commits, opts = {}) {
  if (!store) return store;
  store.commits = {
    items: Array.isArray(commits) ? commits.slice() : [],
    settled: opts.settled !== false
  };
  return store;
}
function applyComments(store, comments, opts = {}) {
  if (!store) return store;
  store.comments = {
    items: Array.isArray(comments) ? comments.slice() : [],
    pageMeta: opts.pageMeta != null ? opts.pageMeta : store.comments.pageMeta,
    settled: opts.settled !== false
  };
  return store;
}
function applyReviews(store, reviews, opts = {}) {
  if (!store) return store;
  store.reviews = {
    items: Array.isArray(reviews) ? reviews.slice() : [],
    settled: opts.settled !== false
  };
  if (opts.avatarUrls) {
    store.meta = {
      ...store.meta,
      avatarUrls: mergeAvatarMaps(store.meta.avatarUrls, opts.avatarUrls)
    };
  }
  return store;
}
function applyChecks(store, checks, opts = {}) {
  if (!store) return store;
  store.checks = {
    data: checks || {
      state: "unknown",
      totalCount: 0,
      statuses: [],
      checkRuns: []
    },
    settled: opts.settled !== false
  };
  return store;
}
function applyDevelopment(store, dev, opts = {}) {
  if (!store) return store;
  const d = dev && typeof dev === "object" ? dev : {};
  store.development = {
    linkedIssues: Array.isArray(d.linkedIssues) ? d.linkedIssues.slice() : [],
    developmentIssues: Array.isArray(d.developmentIssues) ? d.developmentIssues.slice() : [],
    projects: Array.isArray(d.projects) ? d.projects.slice() : [],
    settled: opts.settled !== false
  };
  return store;
}
function applyThreadsFromMergedDetail(store, mergedFlat) {
  if (!store || !mergedFlat) return store;
  store.threads = {
    reviewThreads: Array.isArray(mergedFlat.reviewThreads) ? mergedFlat.reviewThreads.slice() : store.threads.reviewThreads,
    reviewComments: Array.isArray(mergedFlat.reviewComments) ? mergedFlat.reviewComments.slice() : store.threads.reviewComments,
    reviewThreadsMeta: mergedFlat.reviewThreadsMeta != null ? mergedFlat.reviewThreadsMeta : store.threads.reviewThreadsMeta,
    reviewCommentsMeta: mergedFlat.reviewCommentsMeta != null ? mergedFlat.reviewCommentsMeta : store.threads.reviewCommentsMeta,
    settled: store.threads.settled || Array.isArray(mergedFlat.reviewThreads) && mergedFlat.reviewThreads.length > 0 || Array.isArray(mergedFlat.reviewComments) && mergedFlat.reviewComments.length > 0
  };
  if (mergedFlat.viewerPendingReview !== void 0) {
    store.pendingReview = mergedFlat.viewerPendingReview;
  }
  return store;
}
function applyPendingReview(store, pending) {
  if (!store) return store;
  store.pendingReview = pending || null;
  return store;
}
function applyCorePayload(store, coreFlat) {
  if (!store || !coreFlat) return store;
  applyMeta(store, pickMeta(coreFlat), {
    source: coreFlat._source || "network",
    sketch: false
  });
  if (coreFlat.viewerPendingReview !== void 0) {
    applyPendingReview(store, coreFlat.viewerPendingReview);
  }
  if (Array.isArray(coreFlat.reviewThreads) && coreFlat.reviewThreads.length || Array.isArray(coreFlat.reviewComments) && coreFlat.reviewComments.length) {
    applyThreadsFromMergedDetail(store, coreFlat);
  }
  return store;
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalDetailStore = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
