/**
 * AUTO-GENERATED from src/modal/lib/diff-snippet.ts
 * SOURCE OF TRUTH: src/modal/lib/diff-snippet.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  extractDiffSnippet: () => extractDiffSnippet,
  parsePatchLines: () => parsePatchLines,
  snippetForComment: () => snippetForComment,
  snippetFromDiffHunk: () => snippetFromDiffHunk
});
module.exports = __toCommonJS(stdin_exports);
function parsePatchLines(patch) {
  const out = [];
  if (!patch || typeof patch !== "string") return out;
  let oldLine = 0;
  let newLine = 0;
  for (const line of patch.split("\n")) {
    let type = "context";
    if (line.startsWith("+++") || line.startsWith("---")) {
      type = "meta";
    } else if (line.startsWith("@@")) {
      type = "hunk";
      const m = line.match(/@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)? @@/);
      if (m) {
        oldLine = Number(m[1]);
        newLine = Number(m[2]);
      }
      out.push({ oldLine: null, newLine: null, type, text: line });
      continue;
    } else if (line.startsWith("+")) type = "add";
    else if (line.startsWith("-")) type = "del";
    let o = null;
    let n = null;
    if (type === "context") {
      o = oldLine++;
      n = newLine++;
    } else if (type === "del") {
      o = oldLine++;
    } else if (type === "add") {
      n = newLine++;
    }
    out.push({ oldLine: o, newLine: n, type, text: line });
  }
  return out;
}
function extractDiffSnippet(patch, anchor, opts = {}) {
  const lines = parsePatchLines(patch);
  if (!lines.length || !anchor || anchor.line == null) return null;
  const side = (anchor.side || "RIGHT").toUpperCase();
  const end = Number(anchor.line);
  const start = anchor.startLine != null && Number(anchor.startLine) <= end ? Number(anchor.startLine) : end;
  const ctx = Number.isFinite(opts.context) ? opts.context : 2;
  const matchIdx = [];
  for (let i = 0; i < lines.length; i++) {
    const L = lines[i];
    if (L.type === "hunk" || L.type === "meta") continue;
    const n = side === "LEFT" ? L.oldLine : L.newLine;
    if (n != null && n >= start && n <= end) matchIdx.push(i);
  }
  if (!matchIdx.length) {
    for (let i = 0; i < lines.length; i++) {
      const L = lines[i];
      const n = L.newLine ?? L.oldLine;
      if (n != null && n >= start && n <= end) matchIdx.push(i);
    }
  }
  if (!matchIdx.length) return null;
  let from = Math.max(0, matchIdx[0] - ctx);
  let to = Math.min(lines.length - 1, matchIdx[matchIdx.length - 1] + ctx);
  for (let i = from; i >= Math.max(0, from - 5); i--) {
    if (lines[i].type === "hunk") {
      from = i;
      break;
    }
  }
  const slice = lines.slice(from, to + 1).map((L) => ({
    type: L.type,
    text: L.text,
    oldLine: L.oldLine,
    newLine: L.newLine,
    highlight: (side === "LEFT" ? L.oldLine : L.newLine) != null && (side === "LEFT" ? L.oldLine : L.newLine) >= start && (side === "LEFT" ? L.oldLine : L.newLine) <= end
  }));
  return { lines: slice, startLine: start, endLine: end, side };
}
function snippetFromDiffHunk(diffHunk, anchor = {}, opts = {}) {
  if (!diffHunk || typeof diffHunk !== "string") return null;
  const lines = parsePatchLines(diffHunk);
  if (!lines.length) return null;
  const side = String(anchor.side || "RIGHT").toUpperCase() === "LEFT" ? "LEFT" : "RIGHT";
  const end = anchor.line != null ? Number(anchor.line) : anchor.originalLine != null ? Number(anchor.originalLine) : null;
  const start = anchor.startLine != null && end != null && Number(anchor.startLine) <= end ? Number(anchor.startLine) : end;
  if (end != null) {
    const focused = extractDiffSnippet(
      diffHunk,
      { line: end, startLine: start, side },
      { context: opts.context ?? 3 }
    );
    if (focused?.lines?.length) return focused;
  }
  const maxLines = Number.isFinite(opts.maxLines) && opts.maxLines > 0 ? Math.floor(opts.maxLines) : 40;
  const body = lines.filter((L) => L.type !== "meta");
  const slice = (body.length > maxLines ? body.slice(0, maxLines) : body).map((L) => ({
    type: L.type,
    text: L.text,
    oldLine: L.oldLine,
    newLine: L.newLine,
    highlight: end != null && ((side === "LEFT" ? L.oldLine : L.newLine) === end || start != null && end != null && (side === "LEFT" ? L.oldLine : L.newLine) != null && (side === "LEFT" ? L.oldLine : L.newLine) >= start && (side === "LEFT" ? L.oldLine : L.newLine) <= end)
  }));
  if (!slice.length) return null;
  if (!slice.some((L) => L.highlight)) {
    for (let i = slice.length - 1; i >= 0; i--) {
      if (slice[i].type === "add" || slice[i].type === "context" || slice[i].type === "del") {
        slice[i] = { ...slice[i], highlight: true };
        break;
      }
    }
  }
  return {
    lines: slice,
    startLine: start,
    endLine: end,
    side
  };
}
function snippetForComment(comment, files) {
  if (!comment) return null;
  const path = comment.path || "";
  const line = comment.line != null ? Number(comment.line) : comment.originalLine != null ? Number(comment.originalLine) : comment.original_line != null ? Number(comment.original_line) : null;
  const startLine = comment.startLine ?? comment.start_line ?? null;
  const side = comment.side || "RIGHT";
  const hunk = comment.diffHunk || comment.diff_hunk || "";
  if (hunk) {
    const fromHunk = snippetFromDiffHunk(
      hunk,
      { line, startLine, originalLine: comment.originalLine ?? comment.original_line, side },
      { context: 3, maxLines: 40 }
    );
    if (fromHunk?.lines?.length) {
      return { ...fromHunk, path, filePath: path };
    }
  }
  if (!path || !Array.isArray(files)) return null;
  const file = files.find((f) => (f.filename || f.path || "") === path);
  if (!file?.patch) return null;
  const snippet = extractDiffSnippet(
    file.patch,
    { line, startLine, side },
    { context: 2 }
  );
  if (!snippet) return null;
  return { ...snippet, path, filePath: path };
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalDiffSnippet = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
