/**
 * AUTO-GENERATED from src/modal/lib/file-tree.ts
 * SOURCE OF TRUTH: src/modal/lib/file-tree.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  buildNestedFileTree: () => buildNestedFileTree,
  collectDirPaths: () => collectDirPaths,
  fileExtensionFromPath: () => fileExtensionFromPath,
  filesInTreeOrder: () => filesInTreeOrder,
  filterFilesByExtensions: () => filterFilesByExtensions,
  filterFilesByReviewMode: () => filterFilesByReviewMode,
  filterFilesUnreadOnly: () => filterFilesUnreadOnly,
  filterFilesWithReviewThreads: () => filterFilesWithReviewThreads,
  flattenVisibleTree: () => flattenVisibleTree,
  formatFileExtensionLabel: () => formatFileExtensionLabel,
  hasAnyReviewThreads: () => hasAnyReviewThreads,
  listFileExtensions: () => listFileExtensions,
  sumThreadCounts: () => sumThreadCounts,
  toggleFileExtension: () => toggleFileExtension
});
module.exports = __toCommonJS(stdin_exports);
function buildNestedFileTree(files) {
  const root = { type: "dir", name: "", path: "", children: [] };
  if (!Array.isArray(files)) return [];
  for (const file of files) {
    const full = file.filename || file.path || "";
    if (!full) continue;
    const parts = full.split("/").filter(Boolean);
    let node = root;
    let acc = "";
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      acc = acc ? `${acc}/${part}` : part;
      const isFile = i === parts.length - 1;
      if (isFile) {
        if (!node.children) node.children = [];
        node.children.push({
          type: "file",
          name: part,
          path: full,
          file
        });
      } else {
        if (!node.children) node.children = [];
        let next = node.children.find((c) => c.type === "dir" && c.name === part);
        if (!next) {
          next = { type: "dir", name: part, path: acc, children: [] };
          node.children.push(next);
        }
        node = next;
      }
    }
  }
  function sortNodes(nodes) {
    nodes.sort((a, b) => {
      if (a.type !== b.type) return a.type === "dir" ? -1 : 1;
      return a.name.localeCompare(b.name);
    });
    for (const n of nodes) {
      if (n.type === "dir" && n.children) sortNodes(n.children);
    }
  }
  sortNodes(root.children || []);
  return root.children || [];
}
function filesInTreeOrder(files) {
  const list = Array.isArray(files) ? files : [];
  if (!list.length) return [];
  const tree = buildNestedFileTree(list);
  const out = [];
  function walk(nodes) {
    if (!Array.isArray(nodes)) return;
    for (const n of nodes) {
      if (!n) continue;
      if (n.type === "file") {
        if (n.file) out.push(n.file);
        else if (n.path) out.push({ filename: n.path, path: n.path });
        continue;
      }
      if (n.type === "dir" && n.children) walk(n.children);
    }
  }
  walk(tree);
  return out;
}
function flattenVisibleTree(nodes, expandedDirs) {
  const out = [];
  const expanded = expandedDirs instanceof Set ? expandedDirs : expandedDirs instanceof Map ? new Set([...expandedDirs.keys()].filter((k) => expandedDirs.get(k))) : new Set(expandedDirs || []);
  function walk(list, depth) {
    if (!Array.isArray(list)) return;
    for (const n of list) {
      out.push({
        type: n.type,
        name: n.name,
        path: n.path,
        depth,
        file: n.file
      });
      if (n.type === "dir" && n.children && expanded.has(n.path)) {
        walk(n.children, depth + 1);
      }
    }
  }
  walk(nodes, 0);
  return out;
}
function fileExtensionFromPath(pathOrName) {
  const base = String(pathOrName || "").split("/").pop() || "";
  const i = base.lastIndexOf(".");
  if (i <= 0) return "";
  return base.slice(i + 1).toLowerCase();
}
function listFileExtensions(files, opts = {}) {
  const list = Array.isArray(files) ? files : [];
  const counts = /* @__PURE__ */ new Map();
  for (const f of list) {
    const path = f?.filename || f?.path || "";
    if (!path) continue;
    const ext = fileExtensionFromPath(path);
    counts.set(ext, (counts.get(ext) || 0) + 1);
  }
  const sorted = [...counts.entries()].sort((a, b) => {
    if (b[1] !== a[1]) return b[1] - a[1];
    if (a[0] === "") return 1;
    if (b[0] === "") return -1;
    return a[0].localeCompare(b[0]);
  });
  const optsMax = Number(opts?.max);
  const max = Number.isFinite(optsMax) && optsMax > 0 ? Math.floor(optsMax) : sorted.length;
  return sorted.slice(0, max).map(([ext]) => ext);
}
function filterFilesByExtensions(files, selected) {
  const list = Array.isArray(files) ? files : [];
  const set = selected instanceof Set ? selected : new Set(
    Array.isArray(selected) ? selected : selected ? [...selected] : []
  );
  if (set.size === 0) return list.slice();
  return list.filter((f) => {
    const path = f?.filename || f?.path || "";
    return set.has(fileExtensionFromPath(path));
  });
}
function toggleFileExtension(selected, ext) {
  const next = selected instanceof Set ? new Set(selected) : new Set(selected || []);
  const key = String(ext ?? "");
  if (next.has(key)) next.delete(key);
  else next.add(key);
  return next;
}
function formatFileExtensionLabel(ext) {
  const e = String(ext ?? "");
  return e ? `.${e}` : "\u2205";
}
function hasAnyReviewThreads(threadCounts) {
  if (!threadCounts) return false;
  if (threadCounts instanceof Map) {
    for (const n of threadCounts.values()) {
      if (Number(n) > 0) return true;
    }
    return false;
  }
  if (typeof threadCounts === "object") {
    for (const k of Object.keys(threadCounts)) {
      if (Number(threadCounts[k]) > 0) return true;
    }
  }
  return false;
}
function sumThreadCounts(threadCounts) {
  if (!threadCounts) return 0;
  let n = 0;
  if (threadCounts instanceof Map) {
    for (const v of threadCounts.values()) n += Number(v) || 0;
    return n;
  }
  if (typeof threadCounts === "object") {
    for (const k of Object.keys(threadCounts)) {
      n += Number(threadCounts[k]) || 0;
    }
  }
  return n;
}
function countOnPath(threadCounts, path) {
  if (!path || !threadCounts) return 0;
  if (threadCounts instanceof Map) return Number(threadCounts.get(path)) || 0;
  return Number(threadCounts[path]) || 0;
}
function filterFilesByReviewMode(files, allCounts, unresolvedCounts, mode, pendingCounts = null) {
  const list = Array.isArray(files) ? files : [];
  let m = mode;
  if (m === true) m = "all";
  if (m !== "all" && m !== "unresolved" && m !== "resolved" && m !== "pending") {
    return list.slice();
  }
  return list.filter((f) => {
    const path = f?.filename || f?.path || "";
    const total = countOnPath(allCounts, path);
    const unresolved = countOnPath(unresolvedCounts, path);
    const pending = countOnPath(pendingCounts, path);
    if (m === "pending") return pending > 0;
    if (m === "unresolved") {
      if (pendingCounts != null) return Math.max(0, unresolved - pending) > 0;
      return unresolved > 0;
    }
    if (m === "resolved") return total > unresolved;
    return total > 0;
  });
}
function filterFilesWithReviewThreads(files, threadCounts, reviewOnly) {
  return filterFilesByReviewMode(
    files,
    threadCounts,
    threadCounts,
    reviewOnly ? "all" : null
  );
}
function filterFilesUnreadOnly(files, viewedPaths, unreadOnly) {
  const list = Array.isArray(files) ? files : [];
  if (!unreadOnly) return list.slice();
  const viewed = viewedPaths instanceof Set ? viewedPaths : new Set(Array.isArray(viewedPaths) ? viewedPaths : []);
  return list.filter((f) => {
    const path = f?.filename || f?.path || "";
    return path ? !viewed.has(path) : false;
  });
}
function collectDirPaths(nodes) {
  const out = /* @__PURE__ */ new Set();
  function walk(list) {
    if (!Array.isArray(list)) return;
    for (const n of list) {
      if (n?.type === "dir") {
        if (n.path) out.add(n.path);
        walk(n.children);
      }
    }
  }
  walk(nodes);
  return out;
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalFileTree = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
