/**
 * AUTO-GENERATED from src/modal/lib/layout-mode.ts
 * SOURCE OF TRUTH: src/modal/lib/layout-mode.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  LAYOUT_CENTERED: () => LAYOUT_CENTERED,
  LAYOUT_DIFF: () => LAYOUT_DIFF,
  closeDiffLayout: () => closeDiffLayout,
  isValidLayoutMode: () => isValidLayoutMode,
  layoutClassName: () => layoutClassName,
  openDiffLayout: () => openDiffLayout,
  toggleDiffLayout: () => toggleDiffLayout
});
module.exports = __toCommonJS(stdin_exports);
const LAYOUT_CENTERED = "centered";
const LAYOUT_DIFF = "diff";
function isValidLayoutMode(mode) {
  return mode === LAYOUT_CENTERED || mode === LAYOUT_DIFF;
}
function toggleDiffLayout(mode) {
  return mode === LAYOUT_DIFF ? LAYOUT_CENTERED : LAYOUT_DIFF;
}
function openDiffLayout() {
  return LAYOUT_DIFF;
}
function closeDiffLayout() {
  return LAYOUT_CENTERED;
}
function layoutClassName(mode) {
  if (mode === LAYOUT_DIFF) {
    return "prp-modal prp-modal--diff";
  }
  return "prp-modal prp-modal--centered";
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalLayoutMode = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
