/**
 * AUTO-GENERATED from src/modal/lib/modal-state.ts
 * SOURCE OF TRUTH: src/modal/lib/modal-state.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  closeModal: () => closeModal,
  createInitialModalState: () => createInitialModalState,
  openModal: () => openModal,
  selectSearchHit: () => selectSearchHit,
  setLayoutMode: () => setLayoutMode,
  setScrollTop: () => setScrollTop,
  setSearchResults: () => setSearchResults
});
module.exports = __toCommonJS(stdin_exports);
function createInitialModalState() {
  return {
    open: false,
    owner: null,
    repo: null,
    number: null,
    layoutMode: "centered",
    loading: false,
    error: null,
    detail: null,
    files: [],
    virtualRows: [],
    scrollTop: 0,
    viewportHeight: 480,
    rowHeight: 22,
    searchQuery: "",
    searchHits: [],
    searchHitIndex: -1,
    activeFilePath: null
  };
}
function openModal(state, { owner, repo, number }) {
  return {
    ...state,
    open: true,
    owner,
    repo,
    number,
    layoutMode: "centered",
    loading: true,
    error: null,
    detail: null,
    files: [],
    virtualRows: [],
    scrollTop: 0,
    searchQuery: "",
    searchHits: [],
    searchHitIndex: -1,
    activeFilePath: null
  };
}
function closeModal(state) {
  return {
    ...createInitialModalState(),
    // keep measured geometry prefs
    viewportHeight: state.viewportHeight,
    rowHeight: state.rowHeight
  };
}
function setLayoutMode(state, layoutMode) {
  return { ...state, layoutMode };
}
function setScrollTop(state, scrollTop) {
  return { ...state, scrollTop: Math.max(0, scrollTop) };
}
function setSearchResults(state, query, hits, hitIndex = 0) {
  const list = Array.isArray(hits) ? hits : [];
  const idx = list.length === 0 ? -1 : Math.max(0, Math.min(hitIndex, list.length - 1));
  const hit = idx >= 0 ? list[idx] : null;
  return {
    ...state,
    searchQuery: query || "",
    searchHits: list,
    searchHitIndex: idx,
    activeFilePath: hit?.filePath || state.activeFilePath
  };
}
function selectSearchHit(state, hitIndex) {
  const list = state.searchHits || [];
  if (!list.length) return { ...state, searchHitIndex: -1 };
  const idx = (hitIndex % list.length + list.length) % list.length;
  const hit = list[idx];
  return {
    ...state,
    searchHitIndex: idx,
    activeFilePath: hit?.filePath || state.activeFilePath
  };
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalModalState = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
