/**
 * AUTO-GENERATED from src/modal/lib/page-embed.ts
 * SOURCE OF TRUTH: src/modal/lib/page-embed.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  EMBED_OPEN_SHORTCUT: () => EMBED_OPEN_SHORTCUT,
  EMBED_RESTORE_SHORTCUT: () => EMBED_RESTORE_SHORTCUT,
  GH_FOOTER_SELECTORS: () => GH_FOOTER_SELECTORS,
  PAGE_EMBED_ACTIVE_CLASS: () => PAGE_EMBED_ACTIVE_CLASS,
  PAGE_EMBED_FOOTER_HIDDEN_ATTR: () => PAGE_EMBED_FOOTER_HIDDEN_ATTR,
  PAGE_EMBED_HEADER_OFFSET_PX: () => PAGE_EMBED_HEADER_OFFSET_PX,
  PAGE_EMBED_HOST_HEIGHT_CSS: () => PAGE_EMBED_HOST_HEIGHT_CSS,
  PAGE_EMBED_HOST_ID: () => PAGE_EMBED_HOST_ID,
  PAGE_EMBED_HOST_Z_INDEX: () => PAGE_EMBED_HOST_Z_INDEX,
  PRESENTATION_EMBED: () => PRESENTATION_EMBED,
  PRESENTATION_MODAL: () => PRESENTATION_MODAL,
  applyEmbedWheelScroll: () => applyEmbedWheelScroll,
  applyFooterHide: () => applyFooterHide,
  embedGlobalScrollMax: () => embedGlobalScrollMax,
  embedShellChromeFlags: () => embedShellChromeFlags,
  isEmbedPresentation: () => isEmbedPresentation,
  isPrEmbedTarget: () => isPrEmbedTarget,
  matchGithubFooterNodes: () => matchGithubFooterNodes,
  normalizePresentation: () => normalizePresentation,
  parsePrPagePath: () => parsePrPagePath,
  presentationClassName: () => presentationClassName,
  resolveEmbedShortcutAction: () => resolveEmbedShortcutAction,
  restoreFooters: () => restoreFooters,
  routeEmbedWheelScroll: () => routeEmbedWheelScroll,
  shouldShowEmbedChrome: () => shouldShowEmbedChrome
});
module.exports = __toCommonJS(stdin_exports);
const PRESENTATION_MODAL = "modal";
const PRESENTATION_EMBED = "embed";
const PAGE_EMBED_HOST_ID = "prp-page-embed";
const PAGE_EMBED_ACTIVE_CLASS = "prp-embed-active";
const PAGE_EMBED_HEADER_OFFSET_PX = 64;
const PAGE_EMBED_HOST_HEIGHT_CSS = "100vh";
const PAGE_EMBED_HOST_Z_INDEX = 1e5;
const PAGE_EMBED_FOOTER_HIDDEN_ATTR = "data-prp-footer-hidden";
const GH_FOOTER_SELECTORS = [
  "footer.footer",
  "footer.Footer",
  "#footer",
  '[data-test-selector="site-footer"]',
  '[data-test-selector="footer"]',
  "div.footer",
  ".footer",
  "footer"
];
const EMBED_RESTORE_SHORTCUT = {
  alt: true,
  shift: true,
  key: "e",
  action: "restoreNativeView",
  label: "\u2325\u21E7E",
  labelWin: "Alt+Shift+E"
};
const EMBED_OPEN_SHORTCUT = {
  alt: true,
  shift: true,
  key: "e",
  action: "openEmbedView",
  label: EMBED_RESTORE_SHORTCUT.label,
  labelWin: EMBED_RESTORE_SHORTCUT.labelWin
};
const SHA_RE = /^[0-9a-f]{7,40}$/i;
const RANGE_RE = /^([0-9a-f]{7,40})\.\.([0-9a-f]{7,40})$/i;
function parsePrPagePath(pathname) {
  const path = String(pathname || "").split("?")[0].split("#")[0];
  const m = path.match(
    /^\/([^/]+)\/([^/]+)\/pull\/(\d+)(?:\/(files|changes)(?:\/([^/]+))?)?\/?$/i
  );
  if (!m) return null;
  const owner = m[1];
  const repo = m[2];
  const number = Number(m[3]);
  if (!owner || !repo || !Number.isFinite(number) || number <= 0) return null;
  const tab = String(m[4] || "").trim().toLowerCase();
  if (tab && tab !== "files" && tab !== "changes") return null;
  const page = tab === "files" || tab === "changes" ? "diff" : "conversation";
  const rest = String(m[5] || "").trim();
  let commitSha = null;
  let commitEndSha = null;
  if (rest) {
    const range = rest.match(RANGE_RE);
    if (range) {
      commitSha = range[1].toLowerCase();
      commitEndSha = range[2].toLowerCase();
    } else if (SHA_RE.test(rest)) {
      commitSha = rest.toLowerCase();
    }
  }
  return {
    owner,
    repo,
    number,
    page,
    tab: tab || "conversation",
    commitSha,
    commitEndSha
  };
}
function isPrEmbedTarget(pathname) {
  return parsePrPagePath(pathname) != null;
}
function normalizePresentation(value) {
  const v = String(value || "").trim().toLowerCase();
  if (v === PRESENTATION_EMBED || v === "page" || v === "in-page" || v === "inline") {
    return PRESENTATION_EMBED;
  }
  return PRESENTATION_MODAL;
}
function isEmbedPresentation(value) {
  return normalizePresentation(value) === PRESENTATION_EMBED;
}
function embedShellChromeFlags() {
  return {
    presentation: PRESENTATION_EMBED,
    showClose: false,
    showShellToggle: false,
    showFullscreen: false,
    showExit: false,
    showRestoreNative: true
  };
}
function presentationClassName(presentation) {
  return isEmbedPresentation(presentation) ? "prp-shell--embed" : "";
}
function shouldShowEmbedChrome(presentation, control) {
  if (control === "restoreNative") {
    return isEmbedPresentation(presentation);
  }
  if (!isEmbedPresentation(presentation)) return true;
  return false;
}
function clamp(n, lo, hi) {
  if (!Number.isFinite(n)) return lo;
  if (n < lo) return lo;
  if (n > hi) return hi;
  return n;
}
function embedGlobalScrollMax(opts) {
  const cover = opts.coverHeader !== false;
  if (cover) return 0;
  const vh = Math.max(0, Number(opts.viewportHeight) || 0);
  const header = opts.headerOffset != null && Number.isFinite(Number(opts.headerOffset)) ? Math.max(0, Number(opts.headerOffset)) : PAGE_EMBED_HEADER_OFFSET_PX;
  const embedH = opts.embedHeight != null && Number.isFinite(Number(opts.embedHeight)) ? Math.max(0, Number(opts.embedHeight)) : vh;
  const footer = opts.footerHeight != null && Number.isFinite(Number(opts.footerHeight)) ? Math.max(0, Number(opts.footerHeight)) : 0;
  const content = header + embedH + footer;
  return Math.max(0, content - vh);
}
function routeEmbedWheelScroll(opts) {
  const dy = Number(opts.deltaY);
  if (!Number.isFinite(dy) || dy === 0) {
    return { globalDelta: 0, panelDelta: 0, preventDefault: false };
  }
  const gMax = Math.max(0, Number(opts.globalScrollMax) || 0);
  const pMax = Math.max(0, Number(opts.panelScrollMax) || 0);
  const gTop = clamp(Number(opts.globalScrollTop) || 0, 0, gMax);
  const pTop = clamp(Number(opts.panelScrollTop) || 0, 0, pMax);
  const nextG = clamp(gTop + dy, 0, gMax);
  const globalDelta = nextG - gTop;
  const remaining = dy - globalDelta;
  const nextP = clamp(pTop + remaining, 0, pMax);
  const panelDelta = nextP - pTop;
  return {
    globalDelta,
    panelDelta,
    preventDefault: globalDelta !== 0 || panelDelta !== 0
  };
}
function applyEmbedWheelScroll(opts) {
  const g = opts.globalEl;
  const p = opts.panelEl;
  const gMax = g ? Math.max(0, (g.scrollHeight || 0) - (g.clientHeight || 0)) : 0;
  const pMax = p ? Math.max(0, (p.scrollHeight || 0) - (p.clientHeight || 0)) : 0;
  const routed = routeEmbedWheelScroll({
    deltaY: opts.deltaY,
    globalScrollTop: g?.scrollTop ?? 0,
    globalScrollMax: gMax,
    panelScrollTop: p?.scrollTop ?? 0,
    panelScrollMax: pMax
  });
  if (g && routed.globalDelta) {
    g.scrollTop = (g.scrollTop || 0) + routed.globalDelta;
  }
  if (p && routed.panelDelta) {
    p.scrollTop = (p.scrollTop || 0) + routed.panelDelta;
  }
  return routed;
}
function matchGithubFooterNodes(doc) {
  if (!doc || typeof doc.querySelectorAll !== "function") return [];
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  for (const sel of GH_FOOTER_SELECTORS) {
    let list;
    try {
      list = doc.querySelectorAll(sel);
    } catch {
      continue;
    }
    for (let i = 0; i < list.length; i++) {
      const el = list[i];
      if (!el || seen.has(el)) continue;
      if (el.closest?.("#prp-page-embed, .prp-overlay, .prp-page-embed")) {
        continue;
      }
      seen.add(el);
      out.push(el);
    }
  }
  return out;
}
function applyFooterHide(doc) {
  let n = 0;
  for (const el of matchGithubFooterNodes(doc)) {
    const h = el;
    if (h.getAttribute?.(PAGE_EMBED_FOOTER_HIDDEN_ATTR) === "1") continue;
    try {
      h.setAttribute(PAGE_EMBED_FOOTER_HIDDEN_ATTR, "1");
      if (h.style?.setProperty) {
        h.style.setProperty("display", "none", "important");
      }
      n += 1;
    } catch {
    }
  }
  return n;
}
function restoreFooters(doc) {
  if (!doc || typeof doc.querySelectorAll !== "function") return 0;
  let n = 0;
  let list;
  try {
    list = doc.querySelectorAll(`[${PAGE_EMBED_FOOTER_HIDDEN_ATTR}="1"]`);
  } catch {
    return 0;
  }
  for (let i = 0; i < list.length; i++) {
    const h = list[i];
    try {
      h.removeAttribute?.(PAGE_EMBED_FOOTER_HIDDEN_ATTR);
      h.style?.removeProperty?.("display");
      n += 1;
    } catch {
    }
  }
  return n;
}
function resolveEmbedShortcutAction(opts = {}) {
  if (opts.editableTarget) return null;
  if (opts.mod) return null;
  if (!opts.alt || !opts.shift) return null;
  const key = String(opts.key || "").toLowerCase();
  const code = String(opts.code || "");
  const isE = key === EMBED_RESTORE_SHORTCUT.key || code === "KeyE" || code === "keye";
  if (!isE) return null;
  if (isEmbedPresentation(opts.presentation)) return "restoreNativeView";
  if (opts.onNativePrPage) return "openEmbedView";
  return null;
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalPageEmbed = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
