/**
 * AUTO-GENERATED from src/modal/lib/pending-review.ts
 * SOURCE OF TRUTH: src/modal/lib/pending-review.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  addPendingComment: () => addPendingComment,
  buildPendingReviewSubmitPayload: () => buildPendingReviewSubmitPayload,
  createEmptyPendingReview: () => createEmptyPendingReview,
  discardPendingReview: () => discardPendingReview,
  pendingReviewCount: () => pendingReviewCount,
  pendingReviewCtaLabel: () => pendingReviewCtaLabel,
  setPendingReviewBody: () => setPendingReviewBody
});
module.exports = __toCommonJS(stdin_exports);
function createEmptyPendingReview() {
  return { comments: [], body: "" };
}
function addPendingComment(batch, comment) {
  const base = batch && Array.isArray(batch.comments) ? batch : createEmptyPendingReview();
  const body = String(comment?.body || "").trim();
  if (!body || !comment?.path || comment.line == null) {
    return { batch: base, added: false };
  }
  const id = comment.id || `pc-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
  const next = {
    body: base.body || "",
    comments: [
      ...base.comments,
      {
        id,
        path: comment.path,
        line: Number(comment.line),
        side: comment.side || "RIGHT",
        startLine: comment.startLine != null && Number(comment.startLine) !== Number(comment.line) ? Number(comment.startLine) : void 0,
        startSide: comment.startSide || comment.side || "RIGHT",
        body
      }
    ]
  };
  return { batch: next, added: true };
}
function discardPendingReview() {
  return createEmptyPendingReview();
}
function setPendingReviewBody(batch, body) {
  const base = batch && Array.isArray(batch.comments) ? batch : createEmptyPendingReview();
  return { ...base, body: String(body || "") };
}
function pendingReviewCount(batch) {
  return Array.isArray(batch?.comments) ? batch.comments.length : 0;
}
function pendingReviewCtaLabel(batch) {
  return pendingReviewCount(batch) > 0 ? "Add comment" : "Start review";
}
function buildPendingReviewSubmitPayload(batch, opts = {
  // typed loosely for mutable REST payloads
}) {
  const event = opts.event || "COMMENT";
  if (!["COMMENT", "APPROVE", "REQUEST_CHANGES"].includes(event)) {
    return null;
  }
  const comments = (batch?.comments || []).map((c) => {
    const row = {
      path: c.path,
      body: c.body,
      line: Number(c.line),
      side: c.side || "RIGHT"
    };
    if (c.startLine != null && Number(c.startLine) !== Number(c.line)) {
      row.start_line = Number(c.startLine);
      row.start_side = c.startSide || c.side || "RIGHT";
    }
    return row;
  });
  const payload = {
    event,
    body: opts.body != null ? String(opts.body) : String(batch?.body || "")
  };
  if (opts.commitId) payload.commit_id = opts.commitId;
  if (comments.length) payload.comments = comments;
  return payload;
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalPendingReview = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
