/**
 * AUTO-GENERATED from src/modal/lib/review-threads.ts
 * SOURCE OF TRUTH: src/modal/lib/review-threads.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  buildReplyReviewCommentRequest: () => buildReplyReviewCommentRequest,
  buildReplyReviewThreadGraphql: () => buildReplyReviewThreadGraphql,
  buildResolveThreadGraphql: () => buildResolveThreadGraphql,
  countPendingReviewThreads: () => countPendingReviewThreads,
  countPendingReviewThreadsByPath: () => countPendingReviewThreadsByPath,
  countReviewThreadTotals: () => countReviewThreadTotals,
  countReviewThreadsByPath: () => countReviewThreadsByPath,
  countUnresolvedReviewThreadsByPath: () => countUnresolvedReviewThreadsByPath,
  filterFilesByQuery: () => filterFilesByQuery,
  groupReviewThreads: () => groupReviewThreads,
  isPathViewed: () => isPathViewed,
  mapGraphqlReviewThreads: () => mapGraphqlReviewThreads,
  mergeReviewThreadMeta: () => mergeReviewThreadMeta,
  normalizeReviewCommentId: () => normalizeReviewCommentId,
  resolveRootReviewCommentId: () => resolveRootReviewCommentId,
  toggleViewedPath: () => toggleViewedPath
});
module.exports = __toCommonJS(stdin_exports);
function groupReviewThreads(comments) {
  const list = Array.isArray(comments) ? comments : [];
  const byId = /* @__PURE__ */ new Map();
  for (const c of list) {
    if (c && c.id != null) byId.set(String(c.id), c);
  }
  const roots = [];
  const children = /* @__PURE__ */ new Map();
  for (const c of list) {
    if (!c) continue;
    const parentId = c.inReplyToId ?? c.in_reply_to_id ?? null;
    if (parentId != null && byId.has(String(parentId))) {
      const key = String(parentId);
      if (!children.has(key)) children.set(key, []);
      children.get(key).push(c);
    } else {
      roots.push(c);
    }
  }
  return roots.map((root) => {
    const replies = (children.get(String(root.id)) || []).slice().sort(
      (a, b) => String(a.createdAt || a.created_at || "").localeCompare(
        String(b.createdAt || b.created_at || "")
      )
    );
    return {
      id: root.id,
      path: root.path || "",
      line: root.line ?? root.original_line ?? null,
      side: root.side || "RIGHT",
      root,
      replies,
      resolved: Boolean(root.resolved ?? root.isResolved),
      outdated: Boolean(root.outdated),
      pending: Boolean(
        root.pending || replies.some((r) => r && r.pending)
      ),
      threadNodeId: root.threadNodeId || root.thread_id || root.pullRequestReviewThreadId || null,
      count: 1 + replies.length
    };
  });
}
function mergeReviewThreadMeta(comments, threads) {
  const list = Array.isArray(comments) ? comments : [];
  const byCommentId = /* @__PURE__ */ new Map();
  for (const t of Array.isArray(threads) ? threads : []) {
    if (!t || !t.threadNodeId) continue;
    const meta = {
      threadNodeId: String(t.threadNodeId),
      resolved: Boolean(t.resolved)
    };
    for (const id of t.commentIds || []) {
      if (id == null) continue;
      byCommentId.set(String(id), meta);
    }
  }
  return list.map((c) => {
    if (!c) return c;
    const meta = c.id != null ? byCommentId.get(String(c.id)) : null;
    if (!meta) {
      return {
        ...c,
        threadNodeId: c.threadNodeId || null,
        resolved: Boolean(c.resolved)
      };
    }
    return {
      ...c,
      threadNodeId: meta.threadNodeId,
      resolved: meta.resolved
    };
  });
}
function mapGraphqlReviewThreads(nodes) {
  if (!Array.isArray(nodes)) return [];
  return nodes.filter((t) => t && t.id).map((t) => ({
    threadNodeId: t.id,
    resolved: Boolean(t.isResolved),
    commentIds: (t.comments?.nodes || []).map((c) => c?.databaseId).filter((id) => id != null)
  }));
}
function countReviewThreadsByPath(comments) {
  const threads = groupReviewThreads(comments);
  const map = /* @__PURE__ */ new Map();
  for (const t of threads) {
    const p = t.path || "";
    if (!p) continue;
    map.set(p, (map.get(p) || 0) + 1);
  }
  return map;
}
function countUnresolvedReviewThreadsByPath(comments) {
  const threads = groupReviewThreads(comments);
  const map = /* @__PURE__ */ new Map();
  for (const t of threads) {
    if (t.resolved) continue;
    const p = t.path || "";
    if (!p) continue;
    map.set(p, (map.get(p) || 0) + 1);
  }
  return map;
}
function countPendingReviewThreads(comments) {
  const threads = groupReviewThreads(comments);
  let n = 0;
  for (const t of threads) {
    if (t.pending) n += 1;
  }
  return n;
}
function countPendingReviewThreadsByPath(comments) {
  const map = /* @__PURE__ */ new Map();
  const threads = groupReviewThreads(comments);
  for (const t of threads) {
    if (!t.pending) continue;
    const p = t.path || "";
    if (!p) continue;
    map.set(p, (map.get(p) || 0) + 1);
  }
  for (const c of Array.isArray(comments) ? comments : []) {
    if (!c?.pending) continue;
    const p = c.path || "";
    if (!p || map.has(p)) continue;
    map.set(p, 1);
  }
  return map;
}
function countReviewThreadTotals(comments, opts = {}) {
  const pathSet = opts?.allowedPaths instanceof Set ? opts.allowedPaths : opts?.allowedPaths ? new Set(
    Array.isArray(opts.allowedPaths) ? opts.allowedPaths.map(String).filter(Boolean) : []
  ) : null;
  const excludeOutdated = Boolean(opts?.excludeOutdated);
  const threads = groupReviewThreads(comments);
  let total = 0;
  let unresolved = 0;
  let resolved = 0;
  let pendingThreads = 0;
  for (const t of threads) {
    const p = t.path || "";
    if (!p) continue;
    if (pathSet && !pathSet.has(p)) continue;
    if (excludeOutdated && t.outdated) continue;
    total += 1;
    if (t.pending) pendingThreads += 1;
    if (t.resolved) resolved += 1;
    else if (!t.pending) unresolved += 1;
  }
  return { total, unresolved, resolved, pendingThreads };
}
function normalizeReviewCommentId(raw) {
  if (raw == null || raw === "") return null;
  if (typeof raw === "number" && Number.isFinite(raw) && raw > 0) {
    return Math.floor(raw);
  }
  const s = String(raw).trim();
  if (!/^\d+$/.test(s)) return null;
  const n = Number(s);
  return Number.isFinite(n) && n > 0 ? n : null;
}
function resolveRootReviewCommentId(comments, commentId) {
  const start = normalizeReviewCommentId(commentId);
  if (start == null) return null;
  const byId = /* @__PURE__ */ new Map();
  for (const c of Array.isArray(comments) ? comments : []) {
    if (!c || c.id == null) continue;
    const id = normalizeReviewCommentId(c.id);
    if (id != null) byId.set(id, c);
  }
  let cur = byId.get(start) || null;
  if (!cur) return start;
  const seen = /* @__PURE__ */ new Set();
  while (cur) {
    const id = normalizeReviewCommentId(cur.id);
    if (id == null || seen.has(id)) break;
    seen.add(id);
    const parentRaw = cur.inReplyToId ?? cur.in_reply_to_id ?? null;
    const parentId = normalizeReviewCommentId(parentRaw);
    if (parentId == null || !byId.has(parentId)) return id;
    cur = byId.get(parentId);
  }
  return start;
}
function buildReplyReviewThreadGraphql(threadNodeId, body) {
  return {
    method: "POST",
    url: "https://api.github.com/graphql",
    body: {
      query: `mutation($id:ID!,$body:String!){
  addPullRequestReviewThreadReply(input:{pullRequestReviewThreadId:$id,body:$body}){
    comment { databaseId body }
  }
}`,
      variables: {
        id: String(threadNodeId || ""),
        body: String(body || "").trim()
      }
    }
  };
}
function buildReplyReviewCommentRequest(owner, repo, pullNumber, commentId, body) {
  const parentId = normalizeReviewCommentId(commentId);
  const text = String(body || "").trim();
  return {
    method: "POST",
    url: `https://api.github.com/repos/${owner}/${repo}/pulls/${pullNumber}/comments/${parentId ?? commentId}/replies`,
    body: { body: text }
  };
}
function buildResolveThreadGraphql(threadNodeId, resolved = true) {
  const mutation = resolved ? `mutation($id:ID!){ resolveReviewThread(input:{threadId:$id}){ thread { id isResolved } } }` : `mutation($id:ID!){ unresolveReviewThread(input:{threadId:$id}){ thread { id isResolved } } }`;
  return {
    method: "POST",
    url: "https://api.github.com/graphql",
    body: {
      query: mutation,
      variables: { id: threadNodeId }
    }
  };
}
function filterFilesByQuery(files, query) {
  const list = Array.isArray(files) ? files : [];
  const q = String(query || "").trim().toLowerCase();
  if (!q) return list.slice();
  return list.filter((f) => {
    const path = String(f.filename || f.path || "").toLowerCase();
    return path.includes(q);
  });
}
function toggleViewedPath(viewed, path) {
  const next = viewed instanceof Set ? new Set(viewed) : new Set(viewed || []);
  const p = String(path || "");
  if (!p) return next;
  if (next.has(p)) next.delete(p);
  else next.add(p);
  return next;
}
function isPathViewed(viewed, path) {
  if (!path) return false;
  if (viewed instanceof Set) return viewed.has(path);
  if (Array.isArray(viewed)) return viewed.includes(path);
  return false;
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalReviewThreads = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
