/**
 * AUTO-GENERATED from src/modal/lib/search-index.ts
 * SOURCE OF TRUTH: src/modal/lib/search-index.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  SEARCH_CHUNK_SIZE: () => SEARCH_CHUNK_SIZE,
  SEARCH_MAX_HITS: () => SEARCH_MAX_HITS,
  SEARCH_MAX_HITS_PER_DOC: () => SEARCH_MAX_HITS_PER_DOC,
  buildConversationSearchIndex: () => buildConversationSearchIndex,
  buildDiffSearchIndex: () => buildDiffSearchIndex,
  buildSearchIndex: () => buildSearchIndex,
  firstNavigableHitIndex: () => firstNavigableHitIndex,
  isNavigableSearchHit: () => isNavigableSearchHit,
  isSearchHitVisibleInLayout: () => isSearchHitVisibleInLayout,
  mapHitStartToDisplay: () => mapHitStartToDisplay,
  markSearchInHtml: () => markSearchInHtml,
  markSearchInText: () => markSearchInText,
  nextHitIndex: () => nextHitIndex,
  occurrenceIndexAmongRowHits: () => occurrenceIndexAmongRowHits,
  resolveActiveMarkStart: () => resolveActiveMarkStart,
  resolveNavSearchState: () => resolveNavSearchState,
  resolveNavSearchStateForLayout: () => resolveNavSearchStateForLayout,
  resolveQuerySearchState: () => resolveQuerySearchState,
  resolveQuerySearchStateAsync: () => resolveQuerySearchStateAsync,
  searchHitHasRowIndex: () => searchHitHasRowIndex,
  searchHitRowIndexSet: () => searchHitRowIndexSet,
  searchIndex: () => searchIndex,
  searchIndexAsync: () => searchIndexAsync,
  sortSearchHitsForUi: () => sortSearchHitsForUi,
  startOfNthOccurrence: () => startOfNthOccurrence
});
module.exports = __toCommonJS(stdin_exports);
const SEARCH_MAX_HITS = 2e3;
const SEARCH_MAX_HITS_PER_DOC = 8;
const SEARCH_CHUNK_SIZE = 400;
function pushDoc(docs, id, kind, text, extra = {}) {
  const t = (text == null ? "" : String(text)).trim();
  if (!t) return;
  docs.push({ id, kind, text: t, textLower: t.toLowerCase(), ...extra });
}
function buildConversationSearchIndex(prDetail) {
  const docs = [];
  const pr = prDetail || {};
  pushDoc(docs, "body", "body", pr.body, { anchorId: "body" });
  if (Array.isArray(pr.comments)) {
    pr.comments.forEach((c, i) => {
      const id = c?.id ?? i;
      pushDoc(docs, `issue-comment-${id}`, "issue-comment", c?.body || "", {
        anchorId: `issue-comment:${id}`,
        commentId: id
      });
    });
  }
  if (Array.isArray(pr.reviews)) {
    pr.reviews.forEach((r, i) => {
      if (!r?.body) return;
      const id = r.id ?? i;
      pushDoc(docs, `review-${id}`, "review", r.body || "", {
        anchorId: `review:${id}`,
        commentId: id
      });
    });
  }
  if (Array.isArray(pr.reviewComments)) {
    pr.reviewComments.forEach((c, i) => {
      if (!c) return;
      const id = c.id ?? i;
      const parentId = c.inReplyToId ?? c.in_reply_to_id ?? null;
      const isReply = parentId != null;
      pushDoc(
        docs,
        `review-comment-${id}`,
        isReply ? "review-reply" : "review-comment",
        c.body || "",
        {
          anchorId: `review-comment:${id}`,
          commentId: id,
          filePath: c.path || "",
          rowIndex: c.rowIndex
        }
      );
    });
  }
  return docs;
}
function buildDiffSearchIndex(virtualRows) {
  const docs = [];
  if (!Array.isArray(virtualRows)) return docs;
  for (const row of virtualRows) {
    if (!row || row.rowIndex == null) continue;
    const kind = row.kind || "diff";
    let text = "";
    if (kind === "inline-comment") {
      text = row.body || row.text || "";
    } else if (kind === "file-header") {
      text = row.filePath || row.text || "";
    } else {
      text = row.text || row.code || "";
    }
    const isInline = kind === "inline-comment" && row.commentId != null;
    pushDoc(docs, `row-${row.rowIndex}`, kind, text, {
      filePath: row.filePath,
      rowIndex: row.rowIndex,
      commentId: isInline ? row.commentId : void 0,
      anchorId: isInline ? `review-comment:${row.commentId}` : void 0
    });
  }
  return docs;
}
function buildSearchIndex(prDetail, virtualRows, opts = {}) {
  const mode = opts.mode || "full";
  if (mode === "conversation") {
    return buildConversationSearchIndex(prDetail);
  }
  if (mode === "diff") {
    return buildDiffSearchIndex(virtualRows);
  }
  const docs = [];
  const pr = prDetail || {};
  pushDoc(docs, "body", "body", pr.body, { anchorId: "body" });
  if (Array.isArray(pr.comments)) {
    pr.comments.forEach((c, i) => {
      const id = c?.id ?? i;
      pushDoc(docs, `issue-comment-${id}`, "issue-comment", c?.body || "", {
        anchorId: `issue-comment:${id}`,
        commentId: id
      });
    });
  }
  if (Array.isArray(pr.reviewComments)) {
    pr.reviewComments.forEach((c, i) => {
      if (!c) return;
      const id = c.id ?? i;
      const parentId = c.inReplyToId ?? c.in_reply_to_id ?? null;
      pushDoc(
        docs,
        `review-comment-${id}`,
        parentId != null ? "review-reply" : "review-comment",
        c.body || "",
        {
          anchorId: `review-comment:${id}`,
          commentId: id,
          filePath: c.path || "",
          rowIndex: c.rowIndex
        }
      );
    });
  }
  if (Array.isArray(pr.reviews)) {
    pr.reviews.forEach((r, i) => {
      if (!r?.body) return;
      const id = r.id ?? i;
      pushDoc(docs, `review-${id}`, "review", r.body || "", {
        anchorId: `review:${id}`,
        commentId: id
      });
    });
  }
  for (const d of buildDiffSearchIndex(virtualRows)) {
    docs.push(d);
  }
  return docs;
}
function collectDocHits(doc, lower, qLen, hits, maxHits, maxPerDoc) {
  const text = doc.text || "";
  const hay = doc.textLower || text.toLowerCase();
  let from = 0;
  let perDoc = 0;
  while (from < hay.length && hits.length < maxHits && perDoc < maxPerDoc) {
    const at = hay.indexOf(lower, from);
    if (at < 0) break;
    hits.push({
      docId: doc.id,
      kind: doc.kind,
      filePath: doc.filePath,
      text: text.slice(Math.max(0, at - 40), at + qLen + 40),
      rowIndex: doc.rowIndex,
      anchorId: doc.anchorId || null,
      commentId: doc.commentId ?? null,
      start: at,
      end: at + qLen
    });
    perDoc += 1;
    from = at + Math.max(1, qLen);
  }
  return hits.length >= maxHits;
}
function searchIndex(docs, query, opts = {}) {
  const q = (query || "").trim();
  if (!q || !Array.isArray(docs) || docs.length === 0) return [];
  const lower = q.toLowerCase();
  const maxHits = Number.isFinite(opts.maxHits) && opts.maxHits > 0 ? Math.floor(opts.maxHits) : SEARCH_MAX_HITS;
  const maxPerDoc = Number.isFinite(opts.maxPerDoc) && opts.maxPerDoc > 0 ? Math.floor(opts.maxPerDoc) : SEARCH_MAX_HITS_PER_DOC;
  const hits = [];
  for (const doc of docs) {
    if (collectDocHits(doc, lower, q.length, hits, maxHits, maxPerDoc)) break;
  }
  return hits;
}
function yieldToMain() {
  return new Promise((resolve) => {
    if (typeof requestAnimationFrame === "function") {
      requestAnimationFrame(() => setTimeout(resolve, 0));
    } else {
      setTimeout(resolve, 0);
    }
  });
}
async function searchIndexAsync(docs, query, opts = {}) {
  const q = (query || "").trim();
  if (!q || !Array.isArray(docs) || docs.length === 0) return [];
  const lower = q.toLowerCase();
  const maxHits = Number.isFinite(opts.maxHits) && opts.maxHits > 0 ? Math.floor(opts.maxHits) : SEARCH_MAX_HITS;
  const maxPerDoc = Number.isFinite(opts.maxPerDoc) && opts.maxPerDoc > 0 ? Math.floor(opts.maxPerDoc) : SEARCH_MAX_HITS_PER_DOC;
  const chunkSize = Number.isFinite(opts.chunkSize) && opts.chunkSize > 0 ? Math.floor(opts.chunkSize) : SEARCH_CHUNK_SIZE;
  const isCancelled = typeof opts.isCancelled === "function" ? opts.isCancelled : () => false;
  const hits = [];
  const n = docs.length;
  if (n <= chunkSize) {
    if (isCancelled()) return [];
    return searchIndex(docs, query, { maxHits, maxPerDoc });
  }
  for (let i = 0; i < n; i += chunkSize) {
    if (isCancelled()) return [];
    const end = Math.min(i + chunkSize, n);
    for (let j = i; j < end; j++) {
      if (collectDocHits(docs[j], lower, q.length, hits, maxHits, maxPerDoc)) {
        return hits;
      }
    }
    if (end < n) {
      await yieldToMain();
    }
  }
  return hits;
}
function nextHitIndex(current, total, delta) {
  if (!total || total <= 0) return -1;
  if (current < 0) return delta >= 0 ? 0 : total - 1;
  return (current + delta + total) % total;
}
function searchHitHasRowIndex(hit) {
  return hit?.rowIndex != null && Number.isFinite(Number(hit.rowIndex));
}
function firstNavigableHitIndex(hits, opts = {}) {
  const list = Array.isArray(hits) ? hits : [];
  const mode = String(opts.mode || "");
  const preferDiff = opts.preferDiff === true || mode === "diff" || mode === "full";
  if (preferDiff) {
    for (let i = 0; i < list.length; i++) {
      if (searchHitHasRowIndex(list[i])) return i;
    }
  }
  for (let i = 0; i < list.length; i++) {
    const h = list[i];
    if (h?.anchorId) return i;
    if (searchHitHasRowIndex(h)) return i;
  }
  return list.length ? 0 : -1;
}
function isNavigableSearchHit(hit) {
  if (!hit) return false;
  if (hit.anchorId) return true;
  return searchHitHasRowIndex(hit);
}
function isSearchHitVisibleInLayout(hit, layoutMode) {
  if (!hit) return false;
  const inDiff = layoutMode === "diff" || layoutMode === "LAYOUT_DIFF" || String(layoutMode).toLowerCase() === "diff";
  if (inDiff) {
    return searchHitHasRowIndex(hit);
  }
  return isNavigableSearchHit(hit);
}
function resolveNavSearchStateForLayout(hits, hitIndex, delta, layoutMode = "centered") {
  const list = Array.isArray(hits) ? hits : [];
  if (!list.length) {
    return { hits: list, hitIndex: -1, activeHit: null, shouldJump: false };
  }
  let st = resolveNavSearchState(list, hitIndex, delta);
  let guard = 0;
  const start = st.hitIndex;
  while (st.activeHit && (!isNavigableSearchHit(st.activeHit) || !isSearchHitVisibleInLayout(st.activeHit, layoutMode)) && guard < list.length) {
    st = resolveNavSearchState(list, st.hitIndex, delta);
    guard += 1;
    if (st.hitIndex === start && guard > 0) break;
  }
  if (st.activeHit && !isSearchHitVisibleInLayout(st.activeHit, layoutMode)) {
    return {
      hits: list,
      hitIndex: Number.isFinite(hitIndex) ? hitIndex : -1,
      activeHit: list[hitIndex] || null,
      shouldJump: false
    };
  }
  return st;
}
function resolveQuerySearchState(docs, query, opts = {}) {
  let hits = searchIndex(docs, query);
  if (opts.mode || opts.detail) {
    hits = sortSearchHitsForUi(hits, opts.mode || "conversation", opts.detail || null);
  }
  if (!hits.length) {
    return { hits, hitIndex: -1, activeHit: null, shouldJump: false };
  }
  const hitIndex = firstNavigableHitIndex(hits, { mode: opts.mode });
  return {
    hits,
    hitIndex,
    activeHit: hits[hitIndex] || hits[0],
    shouldJump: true
  };
}
async function resolveQuerySearchStateAsync(docs, query, opts = {}) {
  let hits = await searchIndexAsync(docs, query, opts);
  if (typeof opts.isCancelled === "function" && opts.isCancelled()) {
    return { hits: [], hitIndex: -1, activeHit: null, shouldJump: false, cancelled: true };
  }
  if (opts.mode || opts.detail) {
    hits = sortSearchHitsForUi(hits, opts.mode || "conversation", opts.detail || null);
  }
  if (!hits.length) {
    return { hits, hitIndex: -1, activeHit: null, shouldJump: false, cancelled: false };
  }
  const hitIndex = firstNavigableHitIndex(hits, { mode: opts.mode });
  return {
    hits,
    hitIndex,
    activeHit: hits[hitIndex] || hits[0],
    shouldJump: true,
    cancelled: false
  };
}
function escapeHtmlLocal(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function markSearchInText(text, query, opts = {}) {
  const src = text == null ? "" : String(text);
  const q = (query || "").trim();
  if (!src) return "";
  if (!q) return escapeHtmlLocal(src);
  const lower = src.toLowerCase();
  const ql = q.toLowerCase();
  const currentStart = opts.currentStart != null && Number.isFinite(Number(opts.currentStart)) ? Number(opts.currentStart) : null;
  let out = "";
  let i = 0;
  while (i < src.length) {
    const at = lower.indexOf(ql, i);
    if (at < 0) {
      out += escapeHtmlLocal(src.slice(i));
      break;
    }
    out += escapeHtmlLocal(src.slice(i, at));
    const isCurrent = currentStart != null && at === currentStart;
    const cls = isCurrent ? "prp-search-mark prp-search-mark--current" : "prp-search-mark";
    out += `<mark class="${cls}">${escapeHtmlLocal(src.slice(at, at + q.length))}</mark>`;
    i = at + Math.max(1, q.length);
  }
  return out;
}
function decodeEntityAt(html, i) {
  if (html[i] !== "&") return null;
  const semi = html.indexOf(";", i + 1);
  if (semi < 0 || semi - i > 12) return null;
  const body = html.slice(i + 1, semi);
  if (body[0] === "#") {
    const hex = body[1] === "x" || body[1] === "X";
    const num = hex ? parseInt(body.slice(2), 16) : parseInt(body.slice(1), 10);
    if (!Number.isFinite(num)) return null;
    return { ch: String.fromCodePoint(num), end: semi + 1 };
  }
  const map = {
    amp: "&",
    lt: "<",
    gt: ">",
    quot: '"',
    apos: "'",
    nbsp: "\xA0"
  };
  const ch = map[body.toLowerCase()];
  if (!ch) return null;
  return { ch, end: semi + 1 };
}
function markSearchInHtml(html, query, opts = {}) {
  const src = html == null ? "" : String(html);
  const q = (query || "").trim();
  if (!src) return "";
  if (!q) return src;
  const ql = q.toLowerCase();
  const qLen = q.length;
  const plainChars = [];
  const plainToHtml = [];
  let i = 0;
  let inTag = false;
  while (i < src.length) {
    const c = src[i];
    if (inTag) {
      if (c === ">") inTag = false;
      i += 1;
      continue;
    }
    if (c === "<") {
      inTag = true;
      i += 1;
      continue;
    }
    if (c === "&") {
      const ent = decodeEntityAt(src, i);
      if (ent) {
        plainChars.push(ent.ch);
        plainToHtml.push({ hStart: i, hEnd: ent.end });
        i = ent.end;
        continue;
      }
    }
    plainChars.push(c);
    plainToHtml.push({ hStart: i, hEnd: i + 1 });
    i += 1;
  }
  const plain = plainChars.join("");
  const plainLower = plain.toLowerCase();
  const ranges = [];
  let from = 0;
  let occ = 0;
  const wantOcc = opts.occurrenceIndex != null && Number.isFinite(Number(opts.occurrenceIndex)) ? Number(opts.occurrenceIndex) : null;
  const currentStart = opts.currentStart != null && Number.isFinite(Number(opts.currentStart)) ? Number(opts.currentStart) : null;
  while (from < plainLower.length) {
    const at = plainLower.indexOf(ql, from);
    if (at < 0) break;
    let isCurrent = false;
    if (currentStart != null && at === currentStart) isCurrent = true;
    else if (wantOcc != null && occ === wantOcc) isCurrent = true;
    ranges.push({ start: at, end: at + qLen, current: isCurrent });
    occ += 1;
    from = at + Math.max(1, qLen);
  }
  if (!ranges.length) return src;
  let out = "";
  let plainIdx = 0;
  let htmlIdx = 0;
  inTag = false;
  const openMark = (current) => current ? '<mark class="prp-search-mark prp-search-mark--current">' : '<mark class="prp-search-mark">';
  const closeMark = "</mark>";
  const rangeAt = (p) => {
    for (const r of ranges) {
      if (p >= r.start && p < r.end) return r;
    }
    return null;
  };
  let openRange = null;
  while (htmlIdx < src.length) {
    const c = src[htmlIdx];
    if (inTag) {
      out += c;
      if (c === ">") inTag = false;
      htmlIdx += 1;
      continue;
    }
    if (c === "<") {
      if (openRange) {
        out += closeMark;
        openRange = null;
      }
      inTag = true;
      out += c;
      htmlIdx += 1;
      continue;
    }
    const map = plainToHtml[plainIdx];
    if (!map || map.hStart !== htmlIdx) {
      out += src.slice(htmlIdx);
      break;
    }
    const r = rangeAt(plainIdx);
    if (r && (!openRange || openRange.start !== r.start)) {
      if (openRange) out += closeMark;
      out += openMark(r.current);
      openRange = r;
    } else if (!r && openRange) {
      out += closeMark;
      openRange = null;
    }
    out += src.slice(map.hStart, map.hEnd);
    htmlIdx = map.hEnd;
    plainIdx += 1;
    if (openRange && plainIdx >= openRange.end) {
      out += closeMark;
      openRange = null;
    }
  }
  if (openRange) out += closeMark;
  return out;
}
function sortSearchHitsForUi(hits, mode, detail = null) {
  const list = Array.isArray(hits) ? hits.slice() : [];
  if (!list.length) return list;
  if (mode === "diff" || mode === "full") {
    list.sort((a, b) => {
      const ar = a.rowIndex != null ? Number(a.rowIndex) : Number.POSITIVE_INFINITY;
      const br = b.rowIndex != null ? Number(b.rowIndex) : Number.POSITIVE_INFINITY;
      if (ar !== br) return ar - br;
      const aa = String(a.anchorId || a.docId || "");
      const bb = String(b.anchorId || b.docId || "");
      if (ar === Number.POSITIVE_INFINITY && aa !== bb) return aa.localeCompare(bb);
      return (Number(a.start) || 0) - (Number(b.start) || 0);
    });
    return list;
  }
  const timeByAnchor = /* @__PURE__ */ new Map();
  const putTime = (anchorId, at) => {
    if (!anchorId) return;
    timeByAnchor.set(String(anchorId), String(at || ""));
  };
  putTime("body", detail?.createdAt || detail?.updatedAt || "");
  for (const c of detail?.comments || []) {
    putTime(`issue-comment:${c.id}`, c.createdAt);
  }
  for (const r of detail?.reviews || []) {
    putTime(`review:${r.id}`, r.submittedAt);
  }
  for (const c of detail?.reviewComments || []) {
    putTime(`review-comment:${c.id}`, c.createdAt);
  }
  const kindRank = (h) => {
    const k = String(h.kind || "");
    if (k === "body" || h.anchorId === "body") return 0;
    if (k === "issue-comment") return 1;
    if (k === "review") return 2;
    if (k === "review-comment" || k === "review-reply") return 3;
    return 9;
  };
  list.sort((a, b) => {
    const ka = kindRank(a);
    const kb = kindRank(b);
    if (ka === 0 && kb !== 0) return -1;
    if (kb === 0 && ka !== 0) return 1;
    const ta = timeByAnchor.get(String(a.anchorId || "")) || "";
    const tb = timeByAnchor.get(String(b.anchorId || "")) || "";
    if (ta !== tb) return String(tb).localeCompare(String(ta));
    if (ka !== kb) return ka - kb;
    const aa = String(a.anchorId || a.docId || "");
    const bb = String(b.anchorId || b.docId || "");
    if (aa !== bb) return aa.localeCompare(bb);
    return (Number(a.start) || 0) - (Number(b.start) || 0);
  });
  return list;
}
function mapHitStartToDisplay(row, hit, field = "code") {
  if (!row || !hit || hit.rowIndex == null) return null;
  if (Number(hit.rowIndex) !== Number(row.rowIndex)) return null;
  if (hit.start == null || !Number.isFinite(Number(hit.start))) return null;
  const start = Number(hit.start);
  const indexed = row.text != null ? String(row.text) : "";
  let display = field === "left" ? String(row.leftCode ?? "") : field === "right" ? String(row.rightCode ?? "") : field === "text" ? indexed : String(row.code ?? row.text ?? "");
  if (!display) return null;
  if (display === indexed) return start;
  if (indexed.length === display.length + 1 && (indexed[0] === "+" || indexed[0] === "-" || indexed[0] === " ")) {
    return Math.max(0, start - 1);
  }
  const slice = indexed.slice(start, Number(hit.end) || start);
  if (slice) {
    const at = display.toLowerCase().indexOf(slice.toLowerCase());
    if (at >= 0) return at;
  }
  return null;
}
function searchHitRowIndexSet(hits) {
  const set = /* @__PURE__ */ new Set();
  for (const h of Array.isArray(hits) ? hits : []) {
    if (h?.rowIndex != null && Number.isFinite(Number(h.rowIndex))) {
      set.add(Number(h.rowIndex));
    }
  }
  return set;
}
function occurrenceIndexAmongRowHits(hits, hitIndex) {
  const list = Array.isArray(hits) ? hits : [];
  const idx = Number(hitIndex);
  if (!Number.isFinite(idx) || idx < 0 || idx >= list.length) return 0;
  const cur = list[idx];
  if (!cur || cur.rowIndex == null) return 0;
  const row = Number(cur.rowIndex);
  let occ = 0;
  for (let i = 0; i < idx; i++) {
    if (list[i] && Number(list[i].rowIndex) === row) occ += 1;
  }
  return occ;
}
function startOfNthOccurrence(text, query, n) {
  const src = text == null ? "" : String(text);
  const q = (query || "").trim();
  const want = Number(n);
  if (!src || !q || !Number.isFinite(want) || want < 0) return null;
  const lower = src.toLowerCase();
  const ql = q.toLowerCase();
  let from = 0;
  let found = 0;
  while (from < src.length) {
    const at = lower.indexOf(ql, from);
    if (at < 0) return null;
    if (found === want) return at;
    found += 1;
    from = at + Math.max(1, q.length);
  }
  return null;
}
function resolveActiveMarkStart(displayText, query, row, activeHit, occurrenceIndex, field = "code") {
  if (!activeHit || activeHit.rowIndex == null) return null;
  if (Number(activeHit.rowIndex) !== Number(row?.rowIndex)) return null;
  const byOcc = startOfNthOccurrence(displayText, query, occurrenceIndex);
  if (byOcc != null) return byOcc;
  return mapHitStartToDisplay(row, activeHit, field);
}
function resolveNavSearchState(hits, hitIndex, delta) {
  const list = Array.isArray(hits) ? hits : [];
  if (!list.length) {
    return { hits: list, hitIndex: -1, activeHit: null, shouldJump: false };
  }
  const next = nextHitIndex(hitIndex, list.length, delta);
  return {
    hits: list,
    hitIndex: next,
    activeHit: list[next],
    shouldJump: next >= 0
  };
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalSearchIndex = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
