/**
 * AUTO-GENERATED from src/modal/lib/searchable-select.ts
 * SOURCE OF TRUTH: src/modal/lib/searchable-select.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  GITHUB_DEFAULT_LABEL_COLORS: () => GITHUB_DEFAULT_LABEL_COLORS,
  buildBranchOptions: () => buildBranchOptions,
  buildLabelOptions: () => buildLabelOptions,
  buildMilestoneOptions: () => buildMilestoneOptions,
  buildPeopleOptions: () => buildPeopleOptions,
  buildUnifiedReviewerRows: () => buildUnifiedReviewerRows,
  filterSelectOptions: () => filterSelectOptions,
  isBotAccount: () => isBotAccount,
  labelColorCss: () => labelColorCss,
  queryMatchesOption: () => queryMatchesOption,
  resolveLabelColor: () => resolveLabelColor
});
module.exports = __toCommonJS(stdin_exports);
function filterSelectOptions(options, query, opts = {}) {
  const list = Array.isArray(options) ? options : [];
  const limit = Number.isFinite(opts.limit) && opts.limit > 0 ? Math.floor(opts.limit) : 50;
  const q = String(query || "").trim().toLowerCase();
  if (!q) return list.filter((o) => o && !o.disabled).slice(0, limit);
  const words = q.split(/\s+/).filter(Boolean);
  return list.filter((o) => {
    if (!o || o.disabled) return false;
    const hay = [o.id, o.label, ...o.keywords || []].filter(Boolean).join(" ").toLowerCase();
    return words.every((w) => hay.includes(w));
  }).slice(0, limit);
}
function buildPeopleOptions(logins, statusByLogin = {}, avatarByLogin = {}) {
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  const avatars = avatarByLogin && typeof avatarByLogin === "object" ? avatarByLogin : {};
  for (const login of logins || []) {
    const raw = String(login || "").trim();
    if (!raw) continue;
    const key = raw.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    const status = statusByLogin[key] || statusByLogin[raw] || "";
    const avatarUrl = avatars[key] || avatars[raw] || "";
    out.push({
      id: raw,
      label: raw,
      keywords: [raw, status].filter(Boolean),
      meta: { status, login: raw, avatarUrl, kind: "user" }
    });
  }
  return out;
}
const GITHUB_DEFAULT_LABEL_COLORS = {
  bug: "d73a4a",
  documentation: "0075ca",
  duplicate: "cfd3d7",
  enhancement: "a2eeef",
  "good first issue": "7057ff",
  "help wanted": "008672",
  invalid: "e4e669",
  question: "d876e3",
  wontfix: "ffffff"
};
function labelColorCss(color, name) {
  const raw = String(color || "").trim().replace(/^#/, "");
  if (/^[0-9a-fA-F]{3,8}$/.test(raw)) return `#${raw}`;
  const key = String(name || "").trim().toLowerCase();
  const fallback = key ? GITHUB_DEFAULT_LABEL_COLORS[key] : "";
  return fallback ? `#${fallback}` : "";
}
function resolveLabelColor(color, name) {
  const css = labelColorCss(color, name);
  return css ? css.replace(/^#/, "") : "";
}
function buildLabelOptions(labels) {
  const byKey = /* @__PURE__ */ new Map();
  for (const l of labels || []) {
    const name = typeof l === "string" ? l : l?.name;
    const raw = String(name || "").trim();
    if (!raw) continue;
    const key = raw.toLowerCase();
    const fromObj = typeof l === "object" && l ? String(l.color || "").trim().replace(/^#/, "") : "";
    const color = resolveLabelColor(fromObj, raw);
    const next = {
      id: raw,
      label: raw,
      keywords: [raw, l?.description].filter(Boolean),
      meta: typeof l === "object" && l ? { ...l, name: raw, color, kind: "label" } : { name: raw, color, kind: "label" }
    };
    const prev = byKey.get(key);
    if (!prev) {
      byKey.set(key, next);
      continue;
    }
    if (!prev.meta?.color && next.meta?.color) {
      byKey.set(key, next);
    } else if (prev.meta?.color && next.meta?.color && !prev.meta?.description && next.meta?.description) {
      byKey.set(key, { ...prev, meta: { ...prev.meta, description: next.meta.description } });
    }
  }
  return [...byKey.values()];
}
function queryMatchesOption(options, query) {
  const q = String(query || "").trim().toLowerCase();
  if (!q) return false;
  for (const o of options || []) {
    if (!o) continue;
    const id = String(o.id || "").trim().toLowerCase();
    const label = String(o.label || "").trim().toLowerCase();
    if (id === q || label === q) return true;
    const title = String(o.meta?.title || "").trim().toLowerCase();
    if (title && title === q) return true;
  }
  return false;
}
function buildMilestoneOptions(milestones) {
  const byNum = /* @__PURE__ */ new Map();
  for (const m of milestones || []) {
    const number = Number(m?.number);
    if (!Number.isFinite(number) || number <= 0) continue;
    const title = String(m?.title || `Milestone ${number}`).trim();
    const id = String(number);
    byNum.set(id, {
      id,
      label: `${title} (#${number})`,
      keywords: [title, id, m?.description, m?.state].filter(Boolean),
      meta: {
        kind: "milestone",
        number,
        title,
        state: m?.state || "",
        description: m?.description || ""
      }
    });
  }
  return [...byNum.values()].sort(
    (a, b) => Number(b.meta.number) - Number(a.meta.number)
  );
}
function buildBranchOptions(prs, ctx = {}) {
  const names = /* @__PURE__ */ new Set();
  for (const p of prs || []) {
    if (p?.headRef) names.add(String(p.headRef));
    if (p?.baseRef) names.add(String(p.baseRef));
  }
  if (ctx.baseRef) names.add(String(ctx.baseRef));
  if (ctx.headRef) names.add(String(ctx.headRef));
  for (const e of ctx.extra || []) if (e) names.add(String(e));
  for (const d of ["main", "master", "develop", "dev", "trunk"]) names.add(d);
  return [...names].filter(Boolean).sort((a, b) => String(a).localeCompare(String(b))).map((name) => ({
    id: name,
    label: name,
    keywords: [name],
    meta: { branch: name }
  }));
}
function isBotAccount(userOrLogin, detail = null) {
  if (userOrLogin == null) return false;
  if (typeof userOrLogin === "object") {
    if (userOrLogin.isBot === true || userOrLogin.bot === true) return true;
    const type = String(userOrLogin.type || userOrLogin.userType || "").toLowerCase();
    if (type === "bot") return true;
    const login2 = userOrLogin.login || userOrLogin.author || "";
    if (login2 && isBotAccount(login2, detail)) return true;
    return false;
  }
  const login = String(userOrLogin || "").trim();
  if (!login) return false;
  const key = login.toLowerCase();
  const map = detail?.actorIsBot;
  if (map instanceof Map && map.has(key)) return Boolean(map.get(key));
  if (map && typeof map === "object" && Object.prototype.hasOwnProperty.call(map, key)) {
    return Boolean(map[key]);
  }
  if (/\[bot\]$/i.test(login)) return true;
  return false;
}
function buildUnifiedReviewerRows(detail) {
  const d = detail || {};
  const authorKey = String(d.author || "").trim().toLowerCase();
  const statusBy = /* @__PURE__ */ new Map();
  const botBy = /* @__PURE__ */ new Map();
  for (const r of d.reviews || []) {
    if (!r?.author) continue;
    const key = String(r.author).toLowerCase();
    if (authorKey && key === authorKey) continue;
    statusBy.set(key, String(r.state || "COMMENTED"));
    if (isBotAccount(r, d) || isBotAccount(r.author, d)) botBy.set(key, true);
  }
  const rows = /* @__PURE__ */ new Map();
  for (const login of d.requestedReviewers || []) {
    const raw = String(login || "").trim();
    if (!raw) continue;
    const key = raw.toLowerCase();
    if (authorKey && key === authorKey) continue;
    const bot = botBy.get(key) || isBotAccount(raw, d);
    rows.set(key, {
      login: raw,
      status: statusBy.get(key) || "PENDING",
      isBot: bot
    });
  }
  for (const [key, state] of statusBy) {
    if (authorKey && key === authorKey) continue;
    if (rows.has(key)) {
      const row = rows.get(key);
      row.status = state;
      if (botBy.get(key)) row.isBot = true;
    } else {
      const rev = (d.reviews || []).find(
        (r) => String(r.author || "").toLowerCase() === key
      );
      rows.set(key, {
        login: rev?.author || key,
        status: state,
        isBot: botBy.get(key) || isBotAccount(rev, d) || isBotAccount(rev?.author || key, d)
      });
    }
  }
  return [...rows.values()].sort((a, b) => a.login.localeCompare(b.login));
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalSearchableSelect = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
