/**
 * AUTO-GENERATED from src/modal/lib/session-view.ts
 * SOURCE OF TRUTH: src/modal/lib/session-view.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  OPEN_MODAL_KEY: () => OPEN_MODAL_KEY,
  OPEN_MODAL_MAX_AGE_MS: () => OPEN_MODAL_MAX_AGE_MS,
  STORAGE_PREFIX: () => STORAGE_PREFIX,
  clearOpenModal: () => clearOpenModal,
  clearSessionView: () => clearSessionView,
  loadOpenModal: () => loadOpenModal,
  loadSessionView: () => loadSessionView,
  parseOpenModal: () => parseOpenModal,
  parseSessionView: () => parseSessionView,
  saveOpenModal: () => saveOpenModal,
  saveSessionView: () => saveSessionView,
  serializeOpenModal: () => serializeOpenModal,
  serializeSessionView: () => serializeSessionView,
  sessionViewKey: () => sessionViewKey
});
module.exports = __toCommonJS(stdin_exports);
const STORAGE_PREFIX = "prp:view:";
const OPEN_MODAL_KEY = "prp:modal:open";
const OPEN_MODAL_MAX_AGE_MS = 12 * 60 * 60 * 1e3;
function sessionViewKey(owner, repo, number) {
  return `${STORAGE_PREFIX}${String(owner || "").toLowerCase()}/${String(repo || "").toLowerCase()}#${Number(number)}`;
}
function serializeOpenModal(payload) {
  if (!payload || typeof payload !== "object") return null;
  const owner = String(payload.owner || "").trim();
  const repo = String(payload.repo || "").trim();
  const number = Number(payload.number);
  if (!owner || !repo || !Number.isFinite(number) || number <= 0) return null;
  const pageRaw = String(payload.page || "").trim().toLowerCase();
  const page = pageRaw === "diff" || pageRaw === "files" || pageRaw === "review" ? "diff" : pageRaw === "conversation" || pageRaw === "centered" || pageRaw === "conv" ? "conversation" : null;
  const position = payload.position != null && String(payload.position).trim() ? String(payload.position).trim() : null;
  const snap = {
    v: 1,
    owner,
    repo,
    number,
    at: Number(payload.at) || Date.now()
  };
  if (page) snap.page = page;
  if (position) snap.position = position;
  return snap;
}
function parseOpenModal(raw, opts = {}) {
  let obj = raw;
  if (typeof raw === "string") {
    try {
      obj = JSON.parse(raw);
    } catch {
      return null;
    }
  }
  if (!obj || typeof obj !== "object" || obj.v !== 1) return null;
  const owner = String(obj.owner || "").trim();
  const repo = String(obj.repo || "").trim();
  const number = Number(obj.number);
  if (!owner || !repo || !Number.isFinite(number) || number <= 0) return null;
  const now = Number.isFinite(opts.now) ? opts.now : Date.now();
  const maxAge = Number.isFinite(opts.maxAgeMs) && opts.maxAgeMs > 0 ? opts.maxAgeMs : OPEN_MODAL_MAX_AGE_MS;
  const at = Number(obj.at) || 0;
  if (at > 0 && now - at > maxAge) return null;
  const pageRaw = String(obj.page || "").trim().toLowerCase();
  const page = pageRaw === "diff" ? "diff" : pageRaw === "conversation" ? "conversation" : null;
  const position = obj.position != null && String(obj.position).trim() ? String(obj.position).trim() : null;
  return { owner, repo, number, page, position };
}
function saveOpenModal(storage, payload) {
  if (!storage || typeof storage.setItem !== "function") return false;
  const snap = serializeOpenModal({ ...payload, at: Date.now() });
  if (!snap) return false;
  try {
    storage.setItem(OPEN_MODAL_KEY, JSON.stringify(snap));
    return true;
  } catch {
    return false;
  }
}
function loadOpenModal(storage, opts) {
  if (!storage || typeof storage.getItem !== "function") return null;
  try {
    return parseOpenModal(storage.getItem(OPEN_MODAL_KEY), opts);
  } catch {
    return null;
  }
}
function clearOpenModal(storage) {
  if (!storage || typeof storage.removeItem !== "function") return;
  try {
    storage.removeItem(OPEN_MODAL_KEY);
  } catch {
  }
}
function serializeSessionView(state) {
  if (!state || typeof state !== "object") return null;
  const collapsed = state.collapsedFiles instanceof Set ? [...state.collapsedFiles] : Array.isArray(state.collapsedFiles) ? state.collapsedFiles.slice() : [];
  const viewed = state.viewedPaths instanceof Set ? [...state.viewedPaths] : Array.isArray(state.viewedPaths) ? state.viewedPaths.slice() : [];
  return {
    v: 1,
    layoutMode: state.layoutMode === "diff" ? "diff" : "centered",
    diffMode: state.diffMode === "split" ? "split" : "unified",
    collapsedFiles: collapsed.filter((p) => typeof p === "string" && p),
    viewedPaths: viewed.filter((p) => typeof p === "string" && p),
    activeFilePath: typeof state.activeFilePath === "string" ? state.activeFilePath : null
  };
}
function parseSessionView(raw) {
  let obj = raw;
  if (typeof raw === "string") {
    try {
      obj = JSON.parse(raw);
    } catch {
      return null;
    }
  }
  if (!obj || typeof obj !== "object" || obj.v !== 1) return null;
  return {
    layoutMode: obj.layoutMode === "diff" ? "diff" : "centered",
    diffMode: obj.diffMode === "split" ? "split" : "unified",
    collapsedFiles: Array.isArray(obj.collapsedFiles) ? obj.collapsedFiles.filter((p) => typeof p === "string") : [],
    viewedPaths: Array.isArray(obj.viewedPaths) ? obj.viewedPaths.filter((p) => typeof p === "string") : [],
    activeFilePath: typeof obj.activeFilePath === "string" ? obj.activeFilePath : null
  };
}
function loadSessionView(storage, owner, repo, number) {
  if (!storage || typeof storage.getItem !== "function") return null;
  try {
    const key = sessionViewKey(owner, repo, number);
    return parseSessionView(storage.getItem(key));
  } catch {
    return null;
  }
}
function saveSessionView(storage, owner, repo, number, state) {
  if (!storage || typeof storage.setItem !== "function") return false;
  const snap = serializeSessionView(state);
  if (!snap) return false;
  try {
    storage.setItem(sessionViewKey(owner, repo, number), JSON.stringify(snap));
    return true;
  } catch {
    return false;
  }
}
function clearSessionView(storage, owner, repo, number) {
  if (!storage || typeof storage.removeItem !== "function") return;
  try {
    storage.removeItem(sessionViewKey(owner, repo, number));
  } catch {
  }
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalSessionView = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
