/**
 * AUTO-GENERATED from src/modal/lib/shortcut-policy.ts
 * SOURCE OF TRUTH: src/modal/lib/shortcut-policy.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  CONTEXT_THREAD_SHORTCUT: () => CONTEXT_THREAD_SHORTCUT,
  CONVERSATION_SCROLL_SHORTCUT: () => CONVERSATION_SCROLL_SHORTCUT,
  DIFF_OPT_ARROW_SHORTCUT: () => DIFF_OPT_ARROW_SHORTCUT,
  DIFF_PAGE_SCROLL_SHORTCUT: () => DIFF_PAGE_SCROLL_SHORTCUT,
  FILE_NAV_SHORTCUT: () => FILE_NAV_SHORTCUT,
  FOCUSED_THREAD_SHORTCUT: () => FOCUSED_THREAD_SHORTCUT,
  GITHUB_COMMAND_PALETTE_SELECTOR: () => GITHUB_COMMAND_PALETTE_SELECTOR,
  GITHUB_PALETTE_ESCAPE_GRACE_MS: () => GITHUB_PALETTE_ESCAPE_GRACE_MS,
  REVIEW_FILTER_SHORTCUT: () => REVIEW_FILTER_SHORTCUT,
  STEP_NAV_SHORTCUT: () => STEP_NAV_SHORTCUT,
  TOGGLE_SIDE_PANEL_SHORTCUT: () => TOGGLE_SIDE_PANEL_SHORTCUT,
  TOGGLE_VIEWED_SHORTCUT: () => TOGGLE_VIEWED_SHORTCUT,
  __resetGithubPaletteWatchForTests: () => __resetGithubPaletteWatchForTests,
  activeFileNavIndex: () => activeFileNavIndex,
  applyScrollerDelta: () => applyScrollerDelta,
  buildModalOptHoldSlots: () => buildModalOptHoldSlots,
  conversationCommentFocusAnchor: () => conversationCommentFocusAnchor,
  fileNavShortcutLabel: () => fileNavShortcutLabel,
  findGithubCommandPaletteDialog: () => findGithubCommandPaletteDialog,
  isGithubCommandPaletteOpen: () => isGithubCommandPaletteOpen,
  isInsideGithubCommandPalette: () => isInsideGithubCommandPalette,
  isOptionGlyphKey: () => isOptionGlyphKey,
  keyTokenFromCode: () => keyTokenFromCode,
  listConversationCommentFocusTargets: () => listConversationCommentFocusTargets,
  nextScrollTopByPage: () => nextScrollTopByPage,
  normalizeShortcutKey: () => normalizeShortcutKey,
  optArrowScrollDeltaPx: () => optArrowScrollDeltaPx,
  pickConversationCommentFocusTarget: () => pickConversationCommentFocusTarget,
  resolveAdjacentFileNav: () => resolveAdjacentFileNav,
  resolveModalShortcutAction: () => resolveModalShortcutAction,
  shortcutKeyFromEvent: () => shortcutKeyFromEvent,
  shouldIgnoreModalEscapeForGithubPalette: () => shouldIgnoreModalEscapeForGithubPalette,
  sidePanelShortcutLabel: () => sidePanelShortcutLabel,
  stepConversationCommentFocus: () => stepConversationCommentFocus,
  stepNavShortcutLabel: () => stepNavShortcutLabel,
  toggleReviewFilter: () => toggleReviewFilter,
  touchGithubCommandPaletteOpen: () => touchGithubCommandPaletteOpen
});
module.exports = __toCommonJS(stdin_exports);
const STEP_NAV_SHORTCUT = {
  /** Physical K → previous (↑) */
  prev: {
    key: "k",
    code: "KeyK",
    action: "stepNavPrev",
    /** Canonical token for formatShortcut */
    chord: "opt+k",
    labelMac: "\u2325K",
    labelWin: "Alt+K"
  },
  /** Physical J → next (↓) */
  next: {
    key: "j",
    code: "KeyJ",
    action: "stepNavNext",
    chord: "opt+j",
    labelMac: "\u2325J",
    labelWin: "Alt+J"
  }
};
const FILE_NAV_SHORTCUT = {
  prev: {
    key: "[",
    code: "BracketLeft",
    action: "navFilePrev",
    chord: "opt+shift+[",
    labelMac: "\u2325\u21E7[",
    labelWin: "Alt+Shift+["
  },
  next: {
    key: "]",
    code: "BracketRight",
    action: "navFileNext",
    chord: "opt+shift+]",
    labelMac: "\u2325\u21E7]",
    labelWin: "Alt+Shift+]"
  }
};
const DIFF_PAGE_SCROLL_SHORTCUT = {
  prev: {
    key: "arrowup",
    code: "ArrowUp",
    action: "scrollDiffPagePrev",
    chord: "opt+shift+arrowup",
    labelMac: "\u2325\u21E7\u2191",
    labelWin: "Alt+Shift+\u2191"
  },
  next: {
    key: "arrowdown",
    code: "ArrowDown",
    action: "scrollDiffPageNext",
    chord: "opt+shift+arrowdown",
    labelMac: "\u2325\u21E7\u2193",
    labelWin: "Alt+Shift+\u2193"
  }
};
const DIFF_OPT_ARROW_SHORTCUT = {
  /** How many selectable lines to move the caret per chord */
  selectionSteps: 8,
  /** Scroll multiplier of selectionSteps × rowHeight (1 = track caret) */
  scrollStepScale: 1,
  /** Approx row height used for conversation Opt-arrow scroll steps */
  conversationRowHeight: 48,
  prev: {
    key: "arrowup",
    code: "ArrowUp",
    action: "optArrowScrollSelectPrev",
    chord: "opt+arrowup",
    labelMac: "\u2325\u2191",
    labelWin: "Alt+\u2191"
  },
  next: {
    key: "arrowdown",
    code: "ArrowDown",
    action: "optArrowScrollSelectNext",
    chord: "opt+arrowdown",
    labelMac: "\u2325\u2193",
    labelWin: "Alt+\u2193"
  }
};
const CONVERSATION_SCROLL_SHORTCUT = {
  optPrev: {
    action: "scrollConversationOptPrev",
    chord: "opt+arrowup",
    labelMac: "\u2325\u2191",
    labelWin: "Alt+\u2191"
  },
  optNext: {
    action: "scrollConversationOptNext",
    chord: "opt+arrowdown",
    labelMac: "\u2325\u2193",
    labelWin: "Alt+\u2193"
  },
  pagePrev: {
    action: "scrollConversationPagePrev",
    chord: "opt+shift+arrowup",
    labelMac: "\u2325\u21E7\u2191",
    labelWin: "Alt+Shift+\u2191"
  },
  pageNext: {
    action: "scrollConversationPageNext",
    chord: "opt+shift+arrowdown",
    labelMac: "\u2325\u21E7\u2193",
    labelWin: "Alt+Shift+\u2193"
  }
};
function optArrowScrollDeltaPx(dir, rowHeight, viewportHeight = 0) {
  const d = dir < 0 ? -1 : 1;
  const rh = Math.max(1, Number(rowHeight) || 22);
  const steps = Number(DIFF_OPT_ARROW_SHORTCUT.selectionSteps) || 8;
  const scale = Number(DIFF_OPT_ARROW_SHORTCUT.scrollStepScale) || 1;
  let dy = d * steps * rh * scale;
  const vp = Math.max(0, Number(viewportHeight) || 0);
  if (vp > 0) {
    const cap = Math.floor(vp * 0.5);
    if (Math.abs(dy) > cap) dy = d * cap;
  }
  return dy;
}
const TOGGLE_VIEWED_SHORTCUT = {
  key: "r",
  code: "KeyR",
  action: "toggleViewedActiveFile",
  chord: "opt+shift+r",
  labelMac: "\u2325\u21E7R",
  labelWin: "Alt+Shift+R"
};
const TOGGLE_SIDE_PANEL_SHORTCUT = {
  key: "b",
  code: "KeyB",
  action: "toggleSidePanel",
  chord: "opt+b",
  labelMac: "\u2325B",
  labelWin: "Alt+B"
};
const REVIEW_FILTER_SHORTCUT = {
  unresolved: {
    key: "u",
    code: "KeyU",
    filter: "unresolved",
    action: "toggleReviewFilterUnresolved",
    chord: "opt+u",
    labelMac: "\u2325U",
    labelWin: "Alt+U"
  },
  resolved: {
    key: "r",
    code: "KeyR",
    filter: "resolved",
    action: "toggleReviewFilterResolved",
    chord: "opt+r",
    labelMac: "\u2325R",
    labelWin: "Alt+R"
  },
  pending: {
    key: "p",
    code: "KeyP",
    filter: "pending",
    action: "toggleReviewFilterPending",
    chord: "opt+p",
    labelMac: "\u2325P",
    labelWin: "Alt+P"
  }
};
const CONTEXT_THREAD_SHORTCUT = {
  fold: {
    key: "f",
    code: "KeyF",
    action: "contextThreadFold",
    chord: "opt+f",
    labelMac: "\u2325F",
    labelWin: "Alt+F"
  },
  gotoDiff: {
    key: "d",
    code: "KeyD",
    action: "contextThreadGotoDiff",
    chord: "opt+d",
    labelMac: "\u2325D",
    labelWin: "Alt+D"
  },
  comment: {
    key: "c",
    code: "KeyC",
    action: "contextThreadComment",
    chord: "opt+c",
    labelMac: "\u2325C",
    labelWin: "Alt+C"
  },
  resolve: {
    key: "r",
    code: "KeyR",
    action: "contextThreadResolve",
    chord: "opt+ctrl+r",
    labelMac: "\u2325\u2303R",
    labelWin: "Alt+Ctrl+R",
    /** Requires Control (not ⌘) + Option */
    ctrl: true
  }
};
const FOCUSED_THREAD_SHORTCUT = CONTEXT_THREAD_SHORTCUT;
function toggleReviewFilter(current, target) {
  const t = String(target || "").toLowerCase();
  if (t !== "unresolved" && t !== "resolved" && t !== "pending") {
    return current ?? null;
  }
  const cur = current == null || current === "" ? null : String(current).toLowerCase();
  if (cur === t) return null;
  return t;
}
function nextScrollTopByPage(scrollTop, clientHeight, scrollHeight, delta) {
  const top = Math.max(0, Number(scrollTop) || 0);
  const vh = Math.max(0, Number(clientHeight) || 0);
  const sh = Math.max(0, Number(scrollHeight) || 0);
  if (vh <= 0) return top;
  const step = Math.max(40, Math.floor(vh * 0.9));
  const d = delta < 0 ? -step : step;
  const max = Math.max(0, sh - vh);
  const next = top + d;
  return Math.min(max, Math.max(0, next));
}
function filePathOf(file) {
  return String(file?.filename || file?.path || "").trim();
}
function activeFileNavIndex(files, activePath) {
  const list = Array.isArray(files) ? files : [];
  const path = String(activePath || "").trim();
  if (!list.length || !path) return -1;
  return list.findIndex((f) => filePathOf(f) === path);
}
function resolveAdjacentFileNav(files, activePath, delta) {
  const list = Array.isArray(files) ? files : [];
  const total = list.length;
  if (total <= 0) return { index: -1, total: 0, path: null };
  const d = delta < 0 ? -1 : 1;
  let idx = activeFileNavIndex(list, activePath);
  if (idx < 0) {
    idx = d > 0 ? -1 : 0;
  }
  const next = ((idx + d) % total + total) % total;
  const path = filePathOf(list[next]);
  return { index: next, total, path: path || null };
}
const GITHUB_COMMAND_PALETTE_SELECTOR = "#command-palette-pjax-container, dialog.js-command-palette-dialog, command-palette";
const GITHUB_PALETTE_ESCAPE_GRACE_MS = 500;
let _githubPaletteLastOpenAt = 0;
function findGithubCommandPaletteDialog(doc = typeof document !== "undefined" ? document : null) {
  if (!doc || typeof doc.getElementById !== "function") return null;
  try {
    return doc.getElementById("command-palette-pjax-container") || (typeof doc.querySelector === "function" ? doc.querySelector("dialog.js-command-palette-dialog") : null);
  } catch {
    return null;
  }
}
function isInsideGithubCommandPalette(el) {
  if (!el || typeof el.closest !== "function") return false;
  try {
    return Boolean(
      el.closest(GITHUB_COMMAND_PALETTE_SELECTOR)
    );
  } catch {
    return false;
  }
}
function isGithubCommandPaletteOpen(doc = typeof document !== "undefined" ? document : null) {
  if (!doc || typeof doc.getElementById !== "function") return false;
  try {
    const d = findGithubCommandPaletteDialog(doc);
    if (!d) return false;
    return Boolean(d.open);
  } catch {
  }
  return false;
}
function touchGithubCommandPaletteOpen(doc = typeof document !== "undefined" ? document : null, now = Date.now()) {
  const open = isGithubCommandPaletteOpen(doc);
  if (open) _githubPaletteLastOpenAt = now;
  return open;
}
function shouldIgnoreModalEscapeForGithubPalette(doc = typeof document !== "undefined" ? document : null, opts = {}) {
  const now = Number.isFinite(opts.now) ? opts.now : Date.now();
  const grace = Number.isFinite(opts.graceMs) ? Math.max(0, opts.graceMs) : GITHUB_PALETTE_ESCAPE_GRACE_MS;
  if (isGithubCommandPaletteOpen(doc)) {
    _githubPaletteLastOpenAt = now;
    return true;
  }
  if (_githubPaletteLastOpenAt > 0 && now - _githubPaletteLastOpenAt <= grace) {
    return true;
  }
  return false;
}
function __resetGithubPaletteWatchForTests() {
  _githubPaletteLastOpenAt = 0;
}
function keyTokenFromCode(code) {
  const c = String(code || "");
  if (!c) return null;
  const letter = c.match(/^Key([A-Z])$/i);
  if (letter) return letter[1].toLowerCase();
  const digit = c.match(/^Digit([0-9])$/i) || c.match(/^Numpad([0-9])$/i);
  if (digit) return digit[1];
  switch (c) {
    case "BracketLeft":
      return "[";
    case "BracketRight":
      return "]";
    case "Period":
      return ".";
    case "Comma":
      return ",";
    case "Slash":
      return "/";
    case "Backslash":
      return "\\";
    case "Minus":
      return "-";
    case "Equal":
      return "=";
    case "Semicolon":
      return ";";
    case "Quote":
      return "'";
    case "Backquote":
      return "`";
    case "Enter":
    case "NumpadEnter":
      return "enter";
    case "Escape":
      return "escape";
    case "Space":
      return " ";
    case "Tab":
      return "tab";
    case "Backspace":
      return "backspace";
    case "Delete":
      return "delete";
    case "ArrowUp":
      return "arrowup";
    case "ArrowDown":
      return "arrowdown";
    case "ArrowLeft":
      return "arrowleft";
    case "ArrowRight":
      return "arrowright";
    default:
      return null;
  }
}
function isOptionGlyphKey(key) {
  const k = String(key || "");
  if (!k) return false;
  if (/^[a-zA-Z0-9]$/.test(k)) return false;
  if (/^[[\]. ,/\\;'`=-]$/.test(k)) return false;
  if (/^(escape|enter|tab|backspace|delete|arrowup|arrowdown|arrowleft|arrowright| |space)$/i.test(
    k
  )) {
    return false;
  }
  return true;
}
function normalizeShortcutKey(opts = {}) {
  const fromCode = keyTokenFromCode(opts.code);
  if (fromCode != null) return fromCode;
  const raw = String(opts.key || "");
  if (isOptionGlyphKey(raw)) {
    return raw.toLowerCase();
  }
  if (raw === " ") return " ";
  return raw.toLowerCase();
}
function shortcutKeyFromEvent(e) {
  if (!e) return "";
  return normalizeShortcutKey({
    key: e.key,
    code: e.code,
    alt: Boolean(e.altKey)
  });
}
function buildModalOptHoldSlots(opts = {}) {
  const stack = Array.isArray(opts.stackItems) ? opts.stackItems : [];
  const isMac = opts.isMac !== false;
  const slots = [];
  for (let i = 0; i < Math.min(stack.length, 9); i++) {
    const it = stack[i] || {};
    const num = Number(it.number);
    if (!Number.isFinite(num) || num <= 0) continue;
    slots.push({
      id: `stack-digit-${i + 1}`,
      label: isMac ? `\u2325${i + 1}` : `Alt+${i + 1}`,
      chord: `opt+${i + 1}`,
      target: "stack",
      digit: i + 1,
      number: num
    });
  }
  const layout = String(opts.layoutMode || "");
  if (opts.searchOpen || layout === "diff" || layout === "centered" || layout === "conversation") {
    slots.push({
      id: "step-prev",
      label: isMac ? STEP_NAV_SHORTCUT.prev.labelMac : STEP_NAV_SHORTCUT.prev.labelWin,
      chord: STEP_NAV_SHORTCUT.prev.chord,
      target: "step-prev"
    });
    slots.push({
      id: "step-next",
      label: isMac ? STEP_NAV_SHORTCUT.next.labelMac : STEP_NAV_SHORTCUT.next.labelWin,
      chord: STEP_NAV_SHORTCUT.next.chord,
      target: "step-next"
    });
  }
  return slots;
}
function stepNavShortcutLabel(which, isMac = false) {
  const s = STEP_NAV_SHORTCUT[which];
  return isMac ? s.labelMac : s.labelWin;
}
function fileNavShortcutLabel(which, isMac = false) {
  const s = FILE_NAV_SHORTCUT[which];
  return isMac ? s.labelMac : s.labelWin;
}
function sidePanelShortcutLabel(isMac = false) {
  return isMac ? TOGGLE_SIDE_PANEL_SHORTCUT.labelMac : TOGGLE_SIDE_PANEL_SHORTCUT.labelWin;
}
function resolveModalShortcutAction(opts = {}) {
  const mod = Boolean(opts.mod);
  const shift = Boolean(opts.shift);
  const alt = Boolean(opts.alt);
  const ctrl = Boolean(opts.ctrl);
  const key = normalizeShortcutKey({
    key: opts.key,
    code: opts.code,
    alt
  });
  const paletteOpen = Boolean(opts.paletteOpen);
  const layout = String(opts.layoutMode || "");
  const contextThreadActive = Boolean(
    opts.contextThreadActive ?? opts.conversationCommentFocused
  );
  if (opts.githubPaletteOpen) return null;
  if (key === "escape") {
    if (paletteOpen) return "closePalette";
    if (opts.editingBody || opts.editingComment) return "cancelEdit";
    return "escapeNav";
  }
  if (paletteOpen) return null;
  if (contextThreadActive && alt && !shift) {
    if (ctrl && !mod && key === "r") {
      return CONTEXT_THREAD_SHORTCUT.resolve.action;
    }
    if (!ctrl && !mod) {
      if (key === "f" && !opts.editableTarget) {
        return CONTEXT_THREAD_SHORTCUT.fold.action;
      }
      if (key === "d" && !opts.editableTarget) {
        return CONTEXT_THREAD_SHORTCUT.gotoDiff.action;
      }
      if (key === "c") {
        return CONTEXT_THREAD_SHORTCUT.comment.action;
      }
    }
  }
  if (alt && !mod && !ctrl && shift && (key === "[" || key === "]")) {
    if (opts.editableTarget) return null;
    if (String(opts.layoutMode || "") !== "diff") return null;
    return key === "[" ? FILE_NAV_SHORTCUT.prev.action : FILE_NAV_SHORTCUT.next.action;
  }
  if (alt && !mod && !ctrl && shift && (key === "arrowup" || key === "arrowdown")) {
    if (opts.editableTarget) return null;
    if (layout === "diff") {
      return key === "arrowup" ? DIFF_PAGE_SCROLL_SHORTCUT.prev.action : DIFF_PAGE_SCROLL_SHORTCUT.next.action;
    }
    if (layout === "centered" || layout === "conversation") {
      return key === "arrowup" ? CONVERSATION_SCROLL_SHORTCUT.pagePrev.action : CONVERSATION_SCROLL_SHORTCUT.pageNext.action;
    }
    return null;
  }
  if (alt && !mod && !ctrl && !shift && (key === "arrowup" || key === "arrowdown")) {
    if (opts.editableTarget) return null;
    if (layout === "diff") {
      return key === "arrowup" ? DIFF_OPT_ARROW_SHORTCUT.prev.action : DIFF_OPT_ARROW_SHORTCUT.next.action;
    }
    if (layout === "centered" || layout === "conversation") {
      return key === "arrowup" ? CONVERSATION_SCROLL_SHORTCUT.optPrev.action : CONVERSATION_SCROLL_SHORTCUT.optNext.action;
    }
    return null;
  }
  if (alt && !mod && !ctrl && shift && key === "r") {
    if (opts.editableTarget) return null;
    if (layout !== "diff") return null;
    return TOGGLE_VIEWED_SHORTCUT.action;
  }
  if (alt && !mod && !ctrl && !shift && (key === "j" || key === "k")) {
    if (opts.editableTarget && !opts.searchOpen) return null;
    if (!opts.searchOpen && layout !== "diff" && layout !== "centered" && layout !== "conversation") {
      return null;
    }
    return key === "k" ? STEP_NAV_SHORTCUT.prev.action : STEP_NAV_SHORTCUT.next.action;
  }
  if (alt && !mod && !ctrl && !shift && (key === "u" || key === "r" || key === "p")) {
    if (opts.editableTarget) return null;
    if (layout !== "diff") return null;
    if (key === "u") return REVIEW_FILTER_SHORTCUT.unresolved.action;
    if (key === "r") return REVIEW_FILTER_SHORTCUT.resolved.action;
    return REVIEW_FILTER_SHORTCUT.pending.action;
  }
  if (alt && !mod && !ctrl && !shift && !opts.editableTarget) {
    if (key === "[") return "navAdjacentPrev";
    if (key === "]") return "navAdjacentNext";
    if (/^[1-9]$/.test(key)) return `navStackDigit${key}`;
  }
  if (!alt && !mod && (key === "arrowup" || key === "arrowdown") && String(opts.layoutMode || "") === "diff") {
    if (opts.editableTarget) return null;
    if (shift) {
      return key === "arrowup" ? "extendSelectionUp" : "extendSelectionDown";
    }
    return key === "arrowup" ? "moveSelectionUp" : "moveSelectionDown";
  }
  if (opts.editableTarget) return null;
  if (mod && !alt && !shift && !ctrl && key === "f") return "openSearch";
  if (!alt || mod) return null;
  if (ctrl) return null;
  if (shift && key === "k") return "openPalette";
  if (shift && key === "f") return "toggleFullscreen";
  if (shift && key === "c") {
    if (opts.conversationCommentFocused) return "clearConversationCommentFocus";
    return "focusConversationComment";
  }
  if (shift && key === "e") {
    if (opts.presentation === "embed" || opts.isEmbed) return "restoreNativeView";
    return null;
  }
  if (shift) return null;
  if (key === "b") return TOGGLE_SIDE_PANEL_SHORTCUT.action;
  if (key === "." || key === "period") return "toggleDiff";
  return null;
}
function conversationCommentFocusAnchor(item) {
  if (!item || item.id == null) return null;
  const kind = String(item.kind || "");
  const id = String(item.id);
  if (kind === "issue-comment") return `issue-comment:${id}`;
  if (kind === "review") return `review:${id}`;
  if (kind === "review-group") return `review-group:${id}`;
  if (kind === "review-thread" || kind === "review-comment") {
    return `review-comment:${id}`;
  }
  return null;
}
function pickConversationCommentFocusTarget(items) {
  const list = Array.isArray(items) ? items : [];
  for (const item of list) {
    if (!item || item.pending) continue;
    const anchor = conversationCommentFocusAnchor(item);
    if (!anchor) continue;
    return {
      id: String(item.id),
      kind: String(item.kind || ""),
      anchor
    };
  }
  return null;
}
function pushThreadFocusTarget(out, thread) {
  if (!thread || thread.id == null) return;
  out.push({
    id: String(thread.id),
    kind: "review-thread",
    anchor: `review-comment:${thread.id}`
  });
}
function listConversationCommentFocusTargets(items) {
  const list = Array.isArray(items) ? items : [];
  const out = [];
  for (const item of list) {
    if (!item) continue;
    if (item.kind === "review-group" && item.pending) continue;
    if (item.kind === "review-group") {
      out.push({
        id: String(item.id),
        kind: "review-group",
        anchor: `review-group:${item.id}`
      });
      for (const t of item.threads || []) {
        pushThreadFocusTarget(out, t);
      }
      continue;
    }
    if (item.kind === "review-thread" || item.kind === "review-comment") {
      pushThreadFocusTarget(out, item);
      continue;
    }
    const anchor = conversationCommentFocusAnchor(item);
    if (!anchor) continue;
    out.push({
      id: String(item.id),
      kind: String(item.kind || ""),
      anchor
    });
  }
  return out;
}
function stepConversationCommentFocus(items, currentAnchor, delta) {
  const targets = listConversationCommentFocusTargets(items);
  if (!targets.length) return null;
  const d = delta < 0 ? -1 : 1;
  const cur = String(currentAnchor || "").trim();
  let idx = cur ? targets.findIndex((t) => t.anchor === cur) : -1;
  if (idx < 0) {
    return d > 0 ? targets[0] : targets[targets.length - 1];
  }
  const next = ((idx + d) % targets.length + targets.length) % targets.length;
  return targets[next];
}
function applyScrollerDelta(el, deltaPx) {
  if (!el || typeof el.scrollTop !== "number") return 0;
  const top = Math.max(0, Number(el.scrollTop) || 0);
  const vh = Math.max(0, Number(el.clientHeight) || 0);
  const sh = Math.max(0, Number(el.scrollHeight) || 0);
  const max = Math.max(0, sh - vh);
  const next = Math.min(max, Math.max(0, top + (Number(deltaPx) || 0)));
  el.scrollTop = next;
  return next;
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalShortcutPolicy = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
