/**
 * AUTO-GENERATED from src/modal/lib/theme.ts
 * SOURCE OF TRUTH: src/modal/lib/theme.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  resolveGithubTheme: () => resolveGithubTheme
});
module.exports = __toCommonJS(stdin_exports);
function resolveGithubTheme(doc, win) {
  const html = doc?.documentElement;
  const body = doc?.body;
  const attr = html?.getAttribute?.("data-color-mode") || body?.getAttribute?.("data-color-mode") || html?.getAttribute?.("data-color-mode") || "";
  const darkTheme = html?.getAttribute?.("data-dark-theme") || body?.getAttribute?.("data-dark-theme") || "";
  const lightTheme = html?.getAttribute?.("data-light-theme") || body?.getAttribute?.("data-light-theme") || "";
  let mode = "light";
  const normalized = String(attr || "").toLowerCase();
  if (normalized === "dark") mode = "dark";
  else if (normalized === "light") mode = "light";
  else if (normalized === "auto") {
    try {
      const mql = win?.matchMedia?.("(prefers-color-scheme: dark)") || typeof globalThis !== "undefined" && globalThis.matchMedia?.("(prefers-color-scheme: dark)");
      mode = mql?.matches ? "dark" : "light";
    } catch {
      mode = "light";
    }
  } else {
    const cls = `${html?.className || ""} ${body?.className || ""}`;
    if (/\bdark\b|color-bg-default-dark/i.test(cls)) mode = "dark";
    else if (html?.style?.colorScheme === "dark") mode = "dark";
    else {
      try {
        const mql = win?.matchMedia?.("(prefers-color-scheme: dark)");
        if (mql?.matches) mode = "dark";
      } catch {
      }
    }
  }
  return {
    mode,
    className: mode === "dark" ? "prp-theme-dark" : "prp-theme-light",
    colorMode: normalized || mode,
    darkTheme,
    lightTheme
  };
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalTheme = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
