/**
 * AUTO-GENERATED from src/modal/lib/ui-polish.ts
 * SOURCE OF TRUTH: src/modal/lib/ui-polish.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  STACK_PATH_HOVER_MS: () => STACK_PATH_HOVER_MS,
  applyMagicLinksToHtml: () => applyMagicLinksToHtml,
  buildStackBranchSelectOptions: () => buildStackBranchSelectOptions,
  buildStackPathModel: () => buildStackPathModel,
  buildStackStrip: () => buildStackStrip,
  encodeGitRefPath: () => encodeGitRefPath,
  enhanceMarkdownHtml: () => enhanceMarkdownHtml,
  githubAvatarUrl: () => githubAvatarUrl,
  githubCommitUrl: () => githubCommitUrl,
  githubIssueUrl: () => githubIssueUrl,
  githubLabelUrl: () => githubLabelUrl,
  githubPullUrl: () => githubPullUrl,
  githubTreeUrl: () => githubTreeUrl,
  githubUserUrl: () => githubUserUrl,
  indexStackPulls: () => indexStackPulls,
  linkifyMentionsAndIssues: () => linkifyMentionsAndIssues,
  pickStackChild: () => pickStackChild,
  reduceStackPathHover: () => reduceStackPathHover,
  stackBranchHasPathPicker: () => stackBranchHasPathPicker,
  uniqueLogins: () => uniqueLogins,
  uniqueReviewsByAuthor: () => uniqueReviewsByAuthor
});
module.exports = __toCommonJS(stdin_exports);
function uniqueLogins(list) {
  const out = [];
  const seen = /* @__PURE__ */ new Set();
  for (const item of list || []) {
    const login = typeof item === "string" ? item : item?.login || item?.author || item?.name || "";
    const raw = String(login || "").trim();
    if (!raw) continue;
    const key = raw.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(raw);
  }
  return out;
}
function uniqueReviewsByAuthor(reviews) {
  const by = /* @__PURE__ */ new Map();
  for (const r of reviews || []) {
    if (!r || !r.author) continue;
    const key = String(r.author).toLowerCase();
    by.set(key, r);
  }
  return [...by.values()];
}
function githubAvatarUrl(login, size = 40) {
  const u = String(login || "").trim().replace(/^@/, "");
  if (!u) return "";
  const s = Number(size);
  const px = Number.isFinite(s) && s > 0 ? Math.min(460, Math.floor(s)) : 40;
  return `https://github.com/${encodeURIComponent(u)}.png?size=${px}`;
}
function githubUserUrl(login) {
  const u = String(login || "").trim().replace(/^@/, "");
  if (!u) return "";
  return `https://github.com/${encodeURIComponent(u)}`;
}
function githubLabelUrl(owner, repo, labelName) {
  const o = String(owner || "").trim();
  const r = String(repo || "").trim();
  const name = String(labelName || "").trim();
  if (!o || !r || !name) return "";
  return `https://github.com/${encodeURIComponent(o)}/${encodeURIComponent(r)}/labels/${encodeURIComponent(name)}`;
}
function githubIssueUrl(owner, repo, number) {
  const o = String(owner || "").trim();
  const r = String(repo || "").trim();
  const n = Number(number);
  if (!o || !r || !Number.isFinite(n) || n <= 0) return "";
  return `https://github.com/${encodeURIComponent(o)}/${encodeURIComponent(r)}/issues/${n}`;
}
function githubPullUrl(owner, repo, number) {
  const o = String(owner || "").trim();
  const r = String(repo || "").trim();
  const n = Number(number);
  if (!o || !r || !Number.isFinite(n) || n <= 0) return "";
  return `https://github.com/${encodeURIComponent(o)}/${encodeURIComponent(r)}/pull/${n}`;
}
function encodeGitRefPath(ref) {
  const raw = String(ref || "").trim();
  if (!raw) return "";
  return raw.split("/").map((seg) => encodeURIComponent(seg)).join("/");
}
function githubTreeUrl(owner, repo, ref) {
  const o = String(owner || "").trim();
  const r = String(repo || "").trim();
  const path = encodeGitRefPath(ref);
  if (!o || !r || !path) return "";
  return `https://github.com/${encodeURIComponent(o)}/${encodeURIComponent(r)}/tree/${path}`;
}
function githubCommitUrl(owner, repo, sha) {
  const o = String(owner || "").trim();
  const r = String(repo || "").trim();
  const s = String(sha || "").trim();
  if (!o || !r || !s) return "";
  return `https://github.com/${encodeURIComponent(o)}/${encodeURIComponent(r)}/commit/${encodeURIComponent(s)}`;
}
function escapeHtmlLite(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function linkifyMentionsAndIssues(html, ctx = {}) {
  const owner = ctx.owner || "";
  const repo = ctx.repo || "";
  let out = String(html || "");
  const parts = out.split(/(<[^>]+>)/g);
  for (let i = 0; i < parts.length; i++) {
    if (parts[i].startsWith("<")) continue;
    let t = parts[i];
    t = t.replace(/(^|[^A-Za-z0-9_/-])@([A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?)/g, (m, pre, user) => {
      const href = githubUserUrl(user);
      if (!href) return m;
      return `${pre}<a class="prp-entity-link prp-entity-link--user" href="${href}" target="_blank" rel="noreferrer">@${escapeHtmlLite(user)}</a>`;
    });
    if (owner && repo) {
      t = t.replace(/(^|[^A-Za-z0-9_/])#(\d+)\b/g, (m, pre, num) => {
        const href = githubIssueUrl(owner, repo, num);
        if (!href) return m;
        return `${pre}<a class="prp-entity-link prp-entity-link--issue" href="${href}" target="_blank" rel="noreferrer">#${num}</a>`;
      });
    }
    parts[i] = t;
  }
  return parts.join("");
}
function applyMagicLinksToHtml(html, magicLinks) {
  const links = Array.isArray(magicLinks) ? magicLinks : [];
  if (!links.length) return String(html || "");
  const sorted = links.filter((l) => l && l.key && l.url).slice().sort((a, b) => String(b.key).length - String(a.key).length);
  const parts = String(html || "").split(/(<[^>]+>)/g);
  for (let i = 0; i < parts.length; i++) {
    if (parts[i].startsWith("<")) continue;
    let t = parts[i];
    for (const { key, url } of sorted) {
      const safeKey = String(key);
      if (!safeKey || t.indexOf(safeKey) === -1) continue;
      const re = new RegExp(
        `(?<![\\w/])(${safeKey.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")})(?![\\w/])`,
        "g"
      );
      t = t.replace(re, (m) => {
        return `<a class="prp-entity-link prp-entity-link--magic" href="${escapeHtmlLite(url)}" target="_blank" rel="noreferrer">${escapeHtmlLite(m)}</a>`;
      });
    }
    parts[i] = t;
  }
  return parts.join("");
}
function enhanceMarkdownHtml(html, { owner, repo, magicLinks } = {}) {
  let out = String(html || "");
  out = linkifyMentionsAndIssues(out, { owner, repo });
  out = applyMagicLinksToHtml(out, magicLinks);
  return out;
}
function indexStackPulls(prs) {
  const list = Array.isArray(prs) ? prs : [];
  const byNumber = /* @__PURE__ */ new Map();
  const byHead = /* @__PURE__ */ new Map();
  const childrenOf = /* @__PURE__ */ new Map();
  for (const pr of list) {
    if (!pr || pr.number == null) continue;
    byNumber.set(Number(pr.number), pr);
    if (pr.headRef) byHead.set(pr.headRef, pr);
    if (pr.baseRef && pr.headRef) {
      if (!childrenOf.has(pr.baseRef)) childrenOf.set(pr.baseRef, []);
      childrenOf.get(pr.baseRef).push(pr);
    }
  }
  for (const arr of childrenOf.values()) {
    arr.sort((a, b) => Number(b.number) - Number(a.number));
  }
  return { byNumber, byHead, childrenOf };
}
function stripItem(pr, curNum, depth) {
  return {
    number: Number(pr.number),
    title: pr.title || "",
    headRef: pr.headRef || "",
    baseRef: pr.baseRef || "",
    htmlUrl: pr.htmlUrl || pr.html_url || "",
    draft: Boolean(pr.draft),
    current: Number(pr.number) === curNum,
    depth
  };
}
function pickStackChild(kids, parentHeadRef, pathSelections = {}) {
  const list = Array.isArray(kids) ? kids : [];
  if (!list.length) return null;
  const pref = pathSelections?.[parentHeadRef];
  if (pref != null) {
    const hit = list.find((c) => Number(c.number) === Number(pref));
    if (hit) return hit;
  }
  return list[0];
}
function buildStackPathModel(prs, currentNumber, pathSelections = {}) {
  const curNum = Number(currentNumber);
  const empty = { items: [], branches: [] };
  if (!Number.isFinite(curNum)) return empty;
  const { byNumber, byHead, childrenOf } = indexStackPulls(prs);
  const current = byNumber.get(curNum);
  if (!current) {
    return {
      items: [
        {
          number: curNum,
          title: "",
          headRef: "",
          baseRef: "",
          htmlUrl: "",
          current: true,
          depth: 0
        }
      ],
      branches: []
    };
  }
  const ancestors = [];
  const seenUp = /* @__PURE__ */ new Set();
  let p = current;
  while (p && p.baseRef && byHead.has(p.baseRef)) {
    const parent = byHead.get(p.baseRef);
    if (!parent || parent === p) break;
    if (seenUp.has(parent.number)) break;
    seenUp.add(parent.number);
    ancestors.unshift(parent);
    p = parent;
  }
  const toOption = (c) => ({
    number: Number(c.number),
    title: c.title || "",
    headRef: c.headRef || "",
    baseRef: c.baseRef || "",
    htmlUrl: c.htmlUrl || c.html_url || "",
    draft: Boolean(c.draft)
  });
  const descendants = [];
  const seenDown = /* @__PURE__ */ new Set([current.number]);
  let node = current;
  while (node?.headRef) {
    const kids = (childrenOf.get(node.headRef) || []).filter(
      (c) => !seenDown.has(c.number)
    );
    if (!kids.length) break;
    const child = pickStackChild(kids, node.headRef, pathSelections);
    if (!child) break;
    seenDown.add(child.number);
    descendants.push(child);
    node = child;
  }
  const chain = [...ancestors, current, ...descendants];
  const branches = [];
  const seenParents = /* @__PURE__ */ new Set();
  for (let depth = 0; depth < chain.length; depth++) {
    const pr = chain[depth];
    if (!pr?.baseRef) continue;
    const parent = byHead.get(pr.baseRef);
    if (!parent?.headRef) continue;
    const parentHeadRef = parent.headRef;
    if (seenParents.has(parentHeadRef)) continue;
    const kids = childrenOf.get(parentHeadRef) || [];
    if (kids.length < 2) continue;
    seenParents.add(parentHeadRef);
    let selected = pickStackChild(kids, parentHeadRef, pathSelections);
    const onChain = kids.find(
      (c) => chain.some((x) => Number(x.number) === Number(c.number))
    );
    if (pathSelections?.[parentHeadRef] == null && onChain) selected = onChain;
    if (!selected) selected = pr;
    branches.push({
      parentNumber: Number(parent.number),
      parentHeadRef,
      /** Anchor chip = this degree’s node on the strip */
      levelNumber: Number(selected.number),
      selectedNumber: Number(selected.number),
      depth,
      options: kids.map(toOption)
    });
  }
  const items = chain.map((pr, depth) => stripItem(pr, curNum, depth));
  return { items, branches };
}
function buildStackStrip(prs, currentNumber, pathSelections = {}) {
  return buildStackPathModel(prs, currentNumber, pathSelections).items;
}
const STACK_PATH_HOVER_MS = 450;
function stackBranchHasPathPicker(branch) {
  return Boolean(branch && Array.isArray(branch.options) && branch.options.length >= 2);
}
function buildStackBranchSelectOptions(branch) {
  const opts = Array.isArray(branch?.options) ? branch.options : [];
  return opts.map((o) => {
    const num = Number(o.number);
    const title = o.title ? String(o.title) : "";
    const head = o.headRef ? String(o.headRef) : "";
    return {
      id: String(num),
      label: title ? `#${num} \xB7 ${title}` : `#${num}${head ? ` (${head})` : ""}`,
      keywords: [title, head, o.baseRef, String(num)].filter(Boolean),
      meta: {
        kind: "pr",
        number: num,
        headRef: head,
        baseRef: o.baseRef || "",
        htmlUrl: o.htmlUrl || "",
        selected: Number(branch?.selectedNumber) === num
      }
    };
  });
}
function reduceStackPathHover(state, event) {
  const cur = state || { openKey: null, armedKey: null };
  const type = event?.type;
  const key = event?.key == null ? null : String(event.key);
  if (type === "enter") {
    if (!key) {
      return { openKey: cur.openKey, armedKey: null, scheduleOpen: false, cancelTimer: true };
    }
    if (cur.openKey === key) {
      return { openKey: cur.openKey, armedKey: key, scheduleOpen: false, cancelTimer: true };
    }
    return { openKey: cur.openKey, armedKey: key, scheduleOpen: true, cancelTimer: true };
  }
  if (type === "leave") {
    return { openKey: cur.openKey, armedKey: null, scheduleOpen: false, cancelTimer: true };
  }
  if (type === "timer-fire") {
    if (cur.armedKey && cur.armedKey === key) {
      return { openKey: key, armedKey: null, scheduleOpen: false, cancelTimer: true };
    }
    return { openKey: cur.openKey, armedKey: cur.armedKey, scheduleOpen: false, cancelTimer: false };
  }
  if (type === "close") {
    return { openKey: null, armedKey: null, scheduleOpen: false, cancelTimer: true };
  }
  if (type === "open-now") {
    return { openKey: key, armedKey: null, scheduleOpen: false, cancelTimer: true };
  }
  return { openKey: cur.openKey, armedKey: cur.armedKey, scheduleOpen: false, cancelTimer: false };
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalUiPolish = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
