/**
 * AUTO-GENERATED from src/modal/lib/virtual-range.ts
 * SOURCE OF TRUTH: src/modal/lib/virtual-range.ts
 * Do not edit this file — run: npm run build:pure
 */
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  calculateVisibleRange: () => calculateVisibleRange,
  clamp: () => clamp,
  isIndexVisible: () => isIndexVisible,
  rowBoundsForIndex: () => rowBoundsForIndex,
  scrollTopForIndex: () => scrollTopForIndex,
  scrollTopToRevealIndex: () => scrollTopToRevealIndex
});
module.exports = __toCommonJS(stdin_exports);
function clamp(n, min, max) {
  return Math.max(min, Math.min(max, n));
}
function calculateVisibleRange(opts) {
  const totalRows = Math.max(0, Number(opts.totalRows) || 0);
  const rowHeight = Math.max(1, Number(opts.rowHeight) || 1);
  const viewportHeight = Math.max(0, Number(opts.viewportHeight) || 0);
  const scrollTop = Math.max(0, Number(opts.scrollTop) || 0);
  const overscanRaw = Number(opts.overscan);
  const overscan = Math.max(
    0,
    Number.isFinite(overscanRaw) ? overscanRaw : 5
  );
  const offsets = Array.isArray(opts.offsets) ? opts.offsets : null;
  if (offsets && offsets.length === totalRows + 1 && totalRows > 0) {
    const totalHeight2 = Math.max(0, Number(offsets[totalRows]) || 0);
    let rawStart2 = 0;
    let lo = 0;
    let hi = totalRows - 1;
    while (lo <= hi) {
      const mid = lo + hi >> 1;
      if (offsets[mid + 1] <= scrollTop) lo = mid + 1;
      else hi = mid - 1;
    }
    rawStart2 = clamp(lo, 0, totalRows - 1);
    const viewEnd = scrollTop + viewportHeight;
    let rawEnd = rawStart2;
    while (rawEnd < totalRows - 1 && offsets[rawEnd + 1] < viewEnd) {
      rawEnd += 1;
    }
    const start2 = clamp(rawStart2 - overscan, 0, totalRows - 1);
    const end2 = clamp(rawEnd + overscan, 0, totalRows - 1);
    const offsetY2 = offsets[start2] || 0;
    return { start: start2, end: end2, offsetY: offsetY2, totalHeight: totalHeight2 };
  }
  const totalHeight = totalRows * rowHeight;
  if (totalRows === 0) {
    return { start: 0, end: -1, offsetY: 0, totalHeight: 0 };
  }
  const rawStart = Math.floor(scrollTop / rowHeight);
  const visibleCount = Math.ceil(viewportHeight / rowHeight) + 1;
  const start = clamp(rawStart - overscan, 0, totalRows - 1);
  const end = clamp(rawStart + visibleCount + overscan - 1, 0, totalRows - 1);
  const offsetY = start * rowHeight;
  return { start, end, offsetY, totalHeight };
}
function isIndexVisible(index, range) {
  if (!range || range.end < range.start) return false;
  return index >= range.start && index <= range.end;
}
function scrollTopForIndex(index, rowHeight, viewportHeight, totalRows, offsets, opts) {
  const total = Math.max(0, totalRows);
  const i = clamp(Number(index) || 0, 0, Math.max(0, total - 1));
  const alignRaw = String(opts?.align || "quarter");
  const align = alignRaw === "start" || alignRaw === "center" || alignRaw === "third" ? alignRaw : "quarter";
  const vh = Math.max(0, Number(viewportHeight) || 0);
  const explicitPad = opts?.pad != null && Number.isFinite(Number(opts.pad)) ? Math.max(0, Number(opts.pad)) : null;
  if (Array.isArray(offsets) && offsets.length === total + 1) {
    const totalHeight = offsets[total] || 0;
    const y = offsets[i] || 0;
    const h = Math.max(1, (offsets[i + 1] || y) - y);
    const maxScroll2 = Math.max(0, totalHeight - vh);
    if (align === "center") {
      return clamp(y - vh / 2 + h / 2, 0, maxScroll2);
    }
    if (align === "third") {
      return clamp(y - vh / 3, 0, maxScroll2);
    }
    const pad2 = explicitPad != null ? explicitPad : align === "start" ? 0 : Math.floor(vh / 4);
    return clamp(y - pad2, 0, maxScroll2);
  }
  const rh = Math.max(1, rowHeight);
  const maxScroll = Math.max(0, total * rh - vh);
  if (align === "center") {
    return clamp(i * rh - vh / 2 + rh / 2, 0, maxScroll);
  }
  if (align === "third") {
    return clamp(i * rh - vh / 3, 0, maxScroll);
  }
  const pad = explicitPad != null ? explicitPad : align === "start" ? 0 : Math.floor(vh / 4);
  return clamp(i * rh - pad, 0, maxScroll);
}
function rowBoundsForIndex(index, rowHeight, totalRows, offsets) {
  const total = Math.max(0, Number(totalRows) || 0);
  const i = clamp(Number(index) || 0, 0, Math.max(0, total - 1));
  if (Array.isArray(offsets) && offsets.length === total + 1) {
    const y = Number(offsets[i]) || 0;
    const next = Number(offsets[i + 1]) || y;
    return {
      y,
      h: Math.max(1, next - y),
      totalHeight: Math.max(0, Number(offsets[total]) || 0)
    };
  }
  const rh = Math.max(1, Number(rowHeight) || 1);
  return {
    y: i * rh,
    h: rh,
    totalHeight: total * rh
  };
}
function scrollTopToRevealIndex(index, currentScrollTop, rowHeight, viewportHeight, totalRows, offsets, opts) {
  const vp = Math.max(0, Number(viewportHeight) || 0);
  if (vp <= 0) return Math.max(0, Number(currentScrollTop) || 0);
  const { y, h, totalHeight } = rowBoundsForIndex(
    index,
    rowHeight,
    totalRows,
    offsets
  );
  const maxScroll = Math.max(0, totalHeight - vp);
  const cur = clamp(Number(currentScrollTop) || 0, 0, maxScroll);
  const padBoth = Math.max(0, Number(opts?.pad) || 0);
  const padTop = Math.max(
    0,
    opts?.padTop != null ? Number(opts.padTop) : padBoth
  );
  const padBottom = Math.max(
    0,
    opts?.padBottom != null ? Number(opts.padBottom) : padBoth
  );
  const maxInset = Math.max(0, Math.floor(vp / 2) - 1);
  const topInset = Math.min(padTop, maxInset);
  const bottomInset = Math.min(padBottom, maxInset);
  const viewTop = cur + topInset;
  const viewBottom = cur + vp - bottomInset;
  const rowBottom = y + h;
  if (y >= viewTop && rowBottom <= viewBottom) {
    return cur;
  }
  if (y < viewTop) {
    return clamp(y - topInset, 0, maxScroll);
  }
  return clamp(rowBottom - vp + bottomInset, 0, maxScroll);
}


  var api = module.exports && module.exports.__esModule
    ? (module.exports.default && typeof module.exports.default === 'object'
        ? Object.assign({}, module.exports, module.exports.default)
        : module.exports.default || module.exports)
    : module.exports;
  // Prefer named exports map over default-only
  if (api && typeof api === 'object' && api.__esModule) {
    var flat = {};
    for (var k in api) {
      if (k !== 'default' && k !== '__esModule' && Object.prototype.hasOwnProperty.call(api, k)) {
        flat[k] = api[k];
      }
    }
    if (api.default && typeof api.default === 'object') {
      for (var dk in api.default) {
        if (Object.prototype.hasOwnProperty.call(api.default, dk) && flat[dk] === undefined) {
          flat[dk] = api.default[dk];
        }
      }
    }
    if (Object.keys(flat).length) api = flat;
  }
  global.PRModalVirtualRange = api;

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
