/**
 * SOURCE OF TRUTH — GitHub fetch API composition entry.
 */

export * from './detail-sides-comments';
export * from './detail-sides-files';
export * from './http';
export * from './mappers';
export * from './misc';
export * from './mutations-comments';
export * from './mutations-meta';
export * from './pending-review';
export * from './pr-detail';
export * from './pulls';
export * from './reactions';
export * from './review-threads-bulk';
export * from './review-threads-map';
export * from './review-threads-page';
export * from './timeline-items';
export * from './viewer';

import {
  COMMENT_PAGE_SIZE,
  fetchCompareFiles,
  fetchConflictFilePaths,
  fetchIssueOrPrSummaries,
  fetchPrCommentsPage,
  fetchPrIssueComments,
  fetchPrReviews,
  fetchPrSidebarMeta,
  fetchPrTimelineEvents,
  resolvePrMergeability,
} from './detail-sides-comments';
import {
  fetchAllPrCommits,
  fetchAllPrFiles,
  fetchPrChecks,
  fetchPrCommits,
  fetchPrDevelopment,
  fetchPrFiles,
} from './detail-sides-files';
import {
  GQL_COST_LOG_MAX,
  apiGraphql,
  apiJson,
  apiJsonWithLink,
  apiSend,
  buildApiHeaders,
  clearGraphqlCostLog,
  decodeBase64Utf8,
  escapeRegExp,
  fetchNowMs,
  fetchRestCollectionAll,
  getGraphqlCostLog,
  githubGraphqlUrl,
  githubRestUrl,
  gqlCostHeaderUsedPrev,
  gqlCostLogEntries,
  graphqlCostPure,
  headerInt,
  injectRateLimitCostFieldLocal,
  labelGraphqlOperationLocal,
  logParallelRestSummary,
  mapWithConcurrency,
  normalizeApiCtx,
  parseLinkNextUrl,
  parseLinkRelPage,
  recordGraphqlCostEntry,
  sanitizeGraphqlVariablesLocal,
  sleepMs,
  summarizeGraphqlCostLog,
  summarizeGraphqlCostLogLocal,
  timedFetch,
} from './http';
import {
  GQL_REACTION_TO_REST,
  commentsPageHelpers,
  extractReactorLogins,
  extractRepoMergeMethodFlags,
  extractViewerCanMergeAsAdmin,
  mapAndAnnotateFiles,
  mapApiPullRequest,
  mapGraphqlReactionGroups,
  mapGraphqlReviewCommentNode,
  mapGraphqlReviewCommentToRest,
  mapIssueComment,
  mapPrCommitRow,
  mapRestReactions,
  mapReviewComment,
  mapViewerSubscription,
} from './mappers';
import {
  REST_TO_GQL_REACTION,
} from './misc';
import {
  closePullRequest,
  deleteIssueComment,
  deleteReviewComment,
  postIssueComment,
  postReviewComment,
  reopenPullRequest,
  replyToReviewComment,
  resolveReviewThread,
  submitPullReview,
  updatePullState,
} from './mutations-comments';
import {
  addAssignees,
  createRepoLabel,
  createRepoMilestone,
  defaultNewLabelColor,
  deleteHeadBranch,
  editIssueComment,
  editReviewComment,
  fetchRepoLabels,
  fetchRepoMilestones,
  fetchRepoTags,
  fetchTagsForCommits,
  mergePullRequest,
  removeAssignees,
  removeReviewers,
  requestReviewers,
  setIssueLabels,
  setIssueMilestone,
  setPullRequestDraftStage,
  updatePullBranch,
  updatePullRequest,
} from './mutations-meta';
import {
  createPendingPullReview,
  deletePendingPullReview,
  ensureViewerPendingReview,
  fetchViewerPendingReviewBundle,
  fetchViewerPendingReviewComments,
  findViewerPendingReview,
  mergePendingReviewComments,
  pickViewerPendingFromReviews,
  postReviewCommentViaPendingGraphql,
  replyViaPendingReviewGraphql,
  replyViaThreadGraphql,
  resolveParentCommentNodeId,
  submitPendingPullReview,
} from './pending-review';
import {
  fetchPrDetail,
} from './pr-detail';
import {
  attachMagicLinks,
  buildAutolinkUrl,
  fetchDanglingPulls,
  fetchOpenPulls,
  fetchOpenPullsPublic,
  fetchPrHeadProbe,
  fetchPullByNumber,
  fetchRepoAutolinks,
  findDanglingPrNumbers,
  matchAutolinksInText,
  prMatchText,
} from './pulls';
import {
  fetchReactableReactionGroups,
  fetchReactableReactors,
  toggleCommentReaction,
} from './reactions';
import {
  dropReviewThreadsFromDetail,
  emptyReviewThreadsMeta,
  fetchPullReviewThreads,
  fetchPullReviewThreadsBundle,
  fetchReviewThreadsByIds,
  mergeReviewThreadsPageIntoDetail,
} from './review-threads-bulk';
import {
  TIMELINE_ITEMS_PAGE_SIZE,
  fetchPrTimelineItemsPage,
  fetchPrTimelineShell,
  mapGraphqlTimelineNode,
  mapGraphqlTimelineNodes,
} from './timeline-items';
import {
  REVIEW_THREADS_API_MAX,
  REVIEW_THREADS_BY_IDS_NODE_SELECTION,
  REVIEW_THREADS_FIRST_QUERY,
  REVIEW_THREADS_LAST_QUERY,
  REVIEW_THREADS_PAGE_SIZE,
  REVIEW_THREAD_COMMENTS_FIELDS,
  REVIEW_THREAD_SHELL_FIELDS,
  buildRestReviewThreadsPageFromCommentsLocal,
  chooseReviewThreadsTransportLocal,
  mapReviewThreadNodes,
  mergeCommentsBulkIntoThreadsPage,
  selectEagerCommentThreadIdsLocal,
} from './review-threads-map';
import {
  collectUnresolvedThreadNodeIds,
  fetchReviewThreadsPage,
  isGraphqlReviewThreadNodeIdLocal,
  restReviewThreadsFallbackPage,
} from './review-threads-page';
import {
  applyReviewSuggestion,
  deleteIssueSubscription,
  fetchPullRequestSubscription,
  fetchViewerLogin,
  fetchViewerViewedPaths,
  getRepoFileText,
  markFileAsViewed,
  resolvePullRequestNodeId,
  setIssueSubscription,
  unmarkFileAsViewed,
  uploadRepoFile,
} from './viewer';

export const fetchApi = {

  normalizeApiCtx,
  mapApiPullRequest,
  buildApiHeaders,
  findDanglingPrNumbers,
  mapWithConcurrency,
  fetchOpenPullsPublic,
  fetchPullByNumber,
  fetchPrHeadProbe,
  fetchDanglingPulls,
  fetchRepoAutolinks,
  buildAutolinkUrl,
  matchAutolinksInText,
  prMatchText,
  attachMagicLinks,
  fetchOpenPulls,
  fetchPrDetail,
  fetchPrCommentsPage,
  fetchPrCommits,
  fetchAllPrCommits,
  fetchAllPrFiles,
  fetchPrFiles,
  fetchPrIssueComments,
  fetchPrTimelineEvents,
  fetchPrTimelineItemsPage,
  fetchPrTimelineShell,
  mapGraphqlTimelineNode,
  mapGraphqlTimelineNodes,
  TIMELINE_ITEMS_PAGE_SIZE,
  fetchPrReviews,
  fetchPrChecks,
  fetchPrDevelopment,
  fetchPrSidebarMeta,
  fetchIssueOrPrSummaries,
  fetchReactableReactionGroups,
  fetchReactableReactors,
  fetchCompareFiles,
  mapAndAnnotateFiles,
  fetchPullReviewThreads,
  fetchPullReviewThreadsBundle,
  fetchReviewThreadsPage,
  chooseReviewThreadsTransportLocal,
  buildRestReviewThreadsPageFromCommentsLocal,
  fetchReviewThreadsByIds,
  collectUnresolvedThreadNodeIds,
  dropReviewThreadsFromDetail,
  mapGraphqlReviewCommentNode,
  mergeReviewThreadsPageIntoDetail,
  emptyReviewThreadsMeta,
  getGraphqlCostLog,
  clearGraphqlCostLog,
  summarizeGraphqlCostLog,
  injectRateLimitCostFieldLocal,
  labelGraphqlOperationLocal,
  REVIEW_THREADS_API_MAX,
  REVIEW_THREADS_PAGE_SIZE,
  postIssueComment,
  submitPullReview,
  postReviewComment,
  replyToReviewComment,
  findViewerPendingReview,
  ensureViewerPendingReview,
  pickViewerPendingFromReviews,
  fetchViewerPendingReviewComments,
  fetchViewerPendingReviewBundle,
  createPendingPullReview,
  submitPendingPullReview,
  deletePendingPullReview,
  mergePendingReviewComments,
  resolveReviewThread,
  updatePullState,
  closePullRequest,
  reopenPullRequest,
  deleteReviewComment,
  deleteIssueComment,
  toggleCommentReaction,
  updatePullRequest,
  editIssueComment,
  editReviewComment,
  requestReviewers,
  removeReviewers,
  addAssignees,
  removeAssignees,
  setIssueLabels,
  fetchRepoLabels,
  createRepoLabel,
  fetchRepoMilestones,
  createRepoMilestone,
  fetchRepoTags,
  fetchTagsForCommits,
  defaultNewLabelColor,
  mergePullRequest,
  updatePullBranch,
  deleteHeadBranch,
  fetchViewerViewedPaths,
  markFileAsViewed,
  unmarkFileAsViewed,
  setIssueSubscription,
  deleteIssueSubscription,
  fetchPullRequestSubscription,
  resolvePullRequestNodeId,
  setIssueMilestone,
  setPullRequestDraftStage,
  applyReviewSuggestion,
  getRepoFileText,
  uploadRepoFile,
  fetchViewerLogin,
  apiJson,
  apiSend,
  apiGraphql,
};

if (typeof globalThis !== 'undefined') {
  (globalThis as any).PRTreeFetch = fetchApi;
}
try {
  // @ts-expect-error classic
  if (typeof module !== 'undefined' && module?.exports !== undefined) module.exports = fetchApi;
} catch {}
